int highest_patch(void);
void c_version(Invocation* invo);
void maybe_intro_message(void);
void c_intro(Invocation*);
int libMain(void);
void init0(void);
int appMain(int argc, char** argv);
int is_not_a_term(void);
int is_not_a_term_or_gui(void);
void free_vbuf(void);
void may_trigger_safestate(Boole safe);
void state_no_longer_safe(CS reason);
Boole get_was_safe_state(void);
void may_trigger_safestateagain(void);
int work_pending(void);
void mainLoop(Boole inCommPort);
void exitEegl(int exitval);
void mainerr_arg_missing(CS str);
CS mainProgramVersion();
void __attribute__((noinline)) __bp();
void sig_winch(int);
void sig_tstp(int);
void reset_signals(void);
int eeHandleSignal(int sig);
void may_core_dump(void);
void mch_exit(int r);
Tyme eeTime(void);
CS get_ctime(Tyme thetime, int add_newline);
void f_localtime(Arr(Var), OUT Var* returnVar);
void f_reltime(Arr(Var) argVars, OUT Var* returnVar);
void f_reltimefloat(Arr(Var) argVars, OUT Var* returnVar);
void f_reltimestr(Arr(Var) argVars, OUT Var* returnVar);
void f_strftime(Arr(Var) argVars, OUT Var* returnVar);
void f_strptime(Var* argVars, Var* returnVar);
long proftime_time_left(ProfTime *due, ProfTime *now);
Timer* create_timer(long msec, int repeat);
void timer_start(Timer *timer);
long check_due_timer(void);
void stop_timer(Timer *timer);
int timer_valid(Timer *timer);
void timer_free_all(void);
void f_timer_info(Arr(Var) argVars, OUT Var* returnVar);
void f_timer_pause(Arr(Var) argVars, OUT Var*);
void f_timer_start(Arr(Var) argVars, OUT Var* returnVar);
void f_timer_stop(Arr(Var) argVars, OUT Var*);
void f_timer_stopall(Arr(Var), OUT Var*);
Tyme get8ctime(FILE *fd);
int put_time(FILE *fd, Tyme the_time);
void time_to_bytes(Tyme the_time, CS buf);
void add_time(CS buf, Unt buflen, Tyme tt);
void profile_start(ProfTime *tm);
void profile_setlimit(long msec, ProfTime *tm);
int profile_passed_limit(ProfTime *tm);
void profile_end(ProfTime *tm);
void profile_sub(ProfTime *tm, ProfTime *tm2);
void profile_zero(ProfTime *tm);
CS profile_msg(ProfTime *tm);
Long elapsed(TimeSpec* start);
void stop_timeout(void);
volatile SigAtomic * start_timeout(long msec);
void delete_timer(void);
void stop_timeout(void);
volatile SigAtomic* start_timeout(long msec);
Channel* add_channel(void);
int has_any_channel(void);
int channel_still_useful(Channel *channel);
int channel_can_close(Channel* channel);
int channel_unref(Channel* channel);
void mch_delay(long msec, int flags);
void ch_close_part(Channel *channel, ChannelFdKind part);
void channel_set_pipes(Channel *channel, Socket in, Socket out, Socket err);
void channel_set_job(Channel* channel, Job* job, JobOptions* options);
void channel_write_in(Channel* channel);
void chaFreeBook(Book* book);
void channel_write_any_lines(void);
void channel_write_new_lines(Book* book);
ReadChunk * channel_peek(Channel *channel, ChannelFdKind part);
CS channel_first_nl(ReadChunk* node);
void channel_consume(Channel *channel, ChannelFdKind part, int len);
int channel_collapse(Channel *channel, ChannelFdKind part, int want_nl);
int channel_is_open(Channel *channel);
void channel_clear(Channel* channel);
void channel_free_all(void);
int channel_in_blocking_wait(void);
Channel * get_channel_arg(Var* tv, int check_open, int reading, ChannelFdKind part);
void channel_set_nonblock(Channel* channel, ChannelFdKind part);
int channel_send(Channel* channel, ChannelFdKind part, CS buf_arg, int len_arg, char* fun);
int channel_parse_messages(void);
int channel_any_readahead(void);
void f_ch_canread(Var* argvars, Var* returnVar);
void f_ch_close(Arr(Var) argvars, Var*);
void f_ch_close_in(Arr(Var) argvars, Var*);
void f_ch_getbufnr(Arr(Var) argvars, Var* returnVar);
void f_ch_getjob(Arr(Var) argvars, Var* returnVar);
void f_ch_info(Arr(Var) argvars, Var* returnVar);
void f_ch_open(Arr(Var) argvars, Var* returnVar);
void f_ch_read(Arr(Var) argvars, Var* returnVar);
void f_ch_readblob(Arr(Var) argvars, Var* returnVar);
void f_ch_readraw(Arr(Var) argvars, Var* returnVar);
void f_ch_evalexpr(Arr(Var) argvars, Var* returnVar);
void f_ch_sendexpr(Arr(Var) argvars, Var* returnVar);
void f_ch_evalraw(Arr(Var) argvars, Var* returnVar);
void f_ch_sendraw(Arr(Var) argvars, Var* returnVar);
void f_ch_setoptions(Arr(Var) argvars, Var*);
void f_ch_status(Arr(Var) argvars, Var* returnVar);
void channel_to_string_buf(OUT CS builder, Var* varp);
PolyWithStatus chCallShell(Text shellComm, Unt opt);
int mch_create_pty_channel(Job* job, JobOptions* options);
void chBreakcheck(Boole force);
SigHandler motSignalHandler(int sig, SigHandler func);
void mch_early_init(void);
long mch_get_pid(void);
int mch_process_running(long pid);
int motChannelPollSetup(int nfd_in, OUT Arr(PollFd) fds_in, OUT int* towait);
int motPollCheck(int ret_in, Arr(PollFd) fds);
int mch_get_uname(uid_t uid, CS s, int len);
void mch_get_host_name(CS s, int len);
int chJobGetCopyId(Job* job);
void chJobSetCopyId(Job* job, int newVal);
Channel* motJobGetChannel(Job* job);
Job* motChannelGetJob(Channel* ch);
int motJobGetFd(Job* job, Unt part);
Boole motJobIsKeepOpen(Job* job);
Callback chJobGetExitCb(Job* job);
JobStatus chJobGetStatus(Job* job);
void chJobSetStatus(Job* job, JobStatus newVal);
Arr(Byte) chJobGetTty(Job* job, Boole out);
int chSendSignalToJob(Job* job, CS how);
void free_job_options(JobOptions* opt);
void mch_clear_job(Job* job);
int get_job_options(Var* tv, OUT JobOptions* opt, int supported, int supported2);
void job_free_all(void);
void job_unref(Job* job);
Job * job_alloc(void);
void job_set_options(Job* job, JobOptions* opt);
void job_stop_on_exit(void);
int has_pending_job(void);
Boole job_check_ended(void);
Job* startJob(Arr(Var) argvars, Multistring* argv_arg, JobOptions* opt_arg, Job** term_job);
CS job_status(Job* job);
int job_stop(Job* job, Arr(Var) argvars, CS type);
void invoke_prompt_callback(void);
int invoke_prompt_interrupt(void);
CS prompt_text(void);
int prompt_curpos_editable(void);
void f_prompt_setcallback(Arr(Var) argvars, Var*);
void f_prompt_setinterrupt(Arr(Var) argvars, Var*);
void f_prompt_getprompt(Arr(Var) argvars, Var* returnVar);
void f_prompt_setprompt(Arr(Var) argvars, Var*);
void f_job_getchannel(Arr(Var) argvars, OUT Var* returnVar);
void f_job_info(Var* argvars, Var* returnVar);
void f_job_setoptions(Arr(Var) argvars, Var*);
void f_startJob(Arr(Var) argvars, OUT Var* returnVar);
void f_job_status(Arr(Var) argvars, Var* returnVar);
void f_job_stop(Arr(Var) argvars, Var* returnVar);
void job_to_string_buf(OUT CS builder, Var* varp);
Multistring chBuildArgv(Text cmd);
void ch_logfile(CS fname, CS opt);
int ch_log_active(void);
void ch_log(Channel* ch, char const* fmt, ...);
void lo(char const* fmt, ...);
void ch_error(Channel* ch, char const* fmt, ...);
void f_ch_log(Arr(Var) argvars, Var*);
void f_ch_logfile(Arr(Var) argvars, Var*);
CS get_users(Expand*, int idx);
int match_user(CS name);
void free_homedir(void);
void free_users(void);
void c_mkrc(Invocation* invo);
int put_eol(FILE *fd);
int put_line(FILE *fd, CS s);
int get_eeglinfo_parameter(int type);
void check_marks_read(void);
int read_eeglinfo(
   CS file,       //file name or NULL to use default name
   Unt flags       //EIF_WANT_INFO et al.
);
void write_eeglinfo(CS file, Boole forceit);
