int highest_patch(void);
void c_version(Invocation* invo);
void maybe_intro_message(void);
void c_intro(Invocation*);
int libMain(void);
void init0(void);
int appMain(int argc, char** argv);
int is_not_a_term(void);
int is_not_a_term_or_gui(void);
void free_vbuf(void);
void may_trigger_safestate(Boole safe);
void state_no_longer_safe(CS reason);
Boole get_was_safe_state(void);
void may_trigger_safestateagain(void);
int work_pending(void);
void mainLoop(Boole inCommPort);
void exitEegl(int exitval);
void mainerr_arg_missing(CS str);
CS mainProgramVersion();
void __attribute__((noinline)) __bp();
void mch_exit(int r);
Tyme eeTime(void);
CS get_ctime(Tyme thetime, int add_newline);
void f_localtime(Arr(Var), OUT Var* returnVar);
void f_reltime(Arr(Var) argVars, OUT Var* returnVar);
void f_reltimefloat(Arr(Var) argVars, OUT Var* returnVar);
void f_reltimestr(Arr(Var) argVars, OUT Var* returnVar);
void f_strftime(Arr(Var) argVars, OUT Var* returnVar);
void f_strptime(Var* argVars, Var* returnVar);
long proftime_time_left(ProfTime *due, ProfTime *now);
Timer* create_timer(long msec, int repeat);
void timer_start(Timer *timer);
long check_due_timer(void);
void stop_timer(Timer *timer);
int set_ref_in_timer(int copyID);
int timer_valid(Timer *timer);
void timer_free_all(void);
void f_timer_info(Arr(Var) argVars, OUT Var* returnVar);
void f_timer_pause(Arr(Var) argVars, OUT Var*);
void f_timer_start(Arr(Var) argVars, OUT Var* returnVar);
void f_timer_stop(Arr(Var) argVars, OUT Var*);
void f_timer_stopall(Arr(Var), OUT Var*);
Tyme get8ctime(FILE *fd);
int put_time(FILE *fd, Tyme the_time);
void time_to_bytes(Tyme the_time, CS buf);
void add_time(CS buf, Unt buflen, Tyme tt);
void profile_start(ProfTime *tm);
void profile_setlimit(long msec, ProfTime *tm);
int profile_passed_limit(ProfTime *tm);
void profile_end(ProfTime *tm);
void profile_sub(ProfTime *tm, ProfTime *tm2);
void profile_zero(ProfTime *tm);
CS profile_msg(ProfTime *tm);
Long elapsed(TimeSpec* start);
void stop_timeout(void);
volatile sig_atomic_t * start_timeout(long msec);
void delete_timer(void);
void stop_timeout(void);
volatile sig_atomic_t* start_timeout(long msec);
CS get_users(Expand*, int idx);
int match_user(CS name);
void free_homedir(void);
void free_users(void);
void c_mkrc(Invocation* invo);
int put_eol(FILE *fd);
int put_line(FILE *fd, CS s);
int get_eeglinfo_parameter(int type);
void check_marks_read(void);
int read_eeglinfo(
   CS file,       //file name or NULL to use default name
   Unt flags       //EIF_WANT_INFO et al.
);
void write_eeglinfo(CS file, Boole forceit);
