" Name:         Retro Box
" Description:  Retro groove color scheme similar to gruvbox originally designed by morhetz <morhetz@gmail.com>
" Author:       Maxim Kim <habamax@gmail.com>, ported from gruvbox8 of Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Maxim Kim <habamax@gmail.com>, ported from gruvbox8 of Lifepillar <lifepillar@lifepillar.me>
" Website:      https://www.github.com/vim/colorschemes
" License:      Vim License (see `:help license`)
" Last Change:  2025 Jan 07

" Generated by Colortemplate v2.2.3

hi clear
let g:colors_name = 'retrobox'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)

hi! link CursorColumn CursorLine
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link VisualNOS Visual
hi! link Tag Special
hi! link lCursor Cursor
hi! link MessageWindow PMenu
hi! link PopupNotification Todo
hi! link PopupSelected PmenuSel
hi! link CurSearch IncSearch
hi! link Terminal Normal

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#1c1c1c', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984', '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2']
  endif
  hi Normal fg=#ebdbb2 bg=#1c1c1c deco=NONE cterm=NONE
  hi CursorLineNr fg=#fabd2f bg=#1c1c1c deco=bold cterm=bold
  hi FoldColumn fg=#928374 bg=#1c1c1c deco=NONE cterm=NONE
  hi SignColumn fg=#928374 bg=#1c1c1c deco=NONE cterm=NONE
  hi VertSplit fg=#303030 bg=#1c1c1c deco=NONE cterm=NONE
  hi ColorColumn fg=NONE bg=#000000 deco=NONE cterm=NONE
  hi Comment fg=#928374 bg=NONE deco=NONE cterm=NONE
  hi CursorLine fg=NONE bg=#303030 deco=NONE cterm=NONE
  hi Error fg=#fb4934 bg=#1c1c1c deco=bold,reverse cterm=bold,reverse
  hi ErrorMsg fg=#1c1c1c bg=#fb4934 deco=bold cterm=bold
  hi Folded fg=#928374 bg=#121212 deco=NONE cterm=NONE
  hi LineNr fg=#7c6f64 bg=NONE deco=NONE cterm=NONE
  hi MatchParen fg=NONE bg=#504945 deco=bold,underline cterm=bold,underline
  hi NonText fg=#504945 bg=NONE deco=NONE cterm=NONE
  hi Pmenu fg=#ebdbb2 bg=#3c3836 deco=NONE cterm=NONE
  hi PmenuSbar fg=NONE bg=#3c3836 deco=NONE cterm=NONE
  hi PmenuSel fg=#3c3836 bg=#83a598 deco=bold cterm=bold
  hi PmenuThumb fg=NONE bg=#7c6f64 deco=NONE cterm=NONE
  hi PmenuKind fg=#fb4934 bg=#3c3836 deco=NONE cterm=NONE
  hi PmenuKindSel fg=#fb4934 bg=#83a598 deco=NONE cterm=NONE
  hi PmenuExtra fg=#a89984 bg=#3c3836 deco=NONE cterm=NONE
  hi PmenuExtraSel fg=#303030 bg=#83a598 deco=NONE cterm=NONE
  hi PmenuMatch fg=#b16286 bg=#3c3836 deco=NONE cterm=NONE
  hi PmenuMatchSel fg=#b16286 bg=#83a598 deco=bold cterm=bold
  hi SpecialKey fg=#928374 bg=NONE deco=NONE cterm=NONE
  hi StatusLine fg=#504945 bg=#ebdbb2 deco=bold,reverse cterm=bold,reverse
  hi StatusLineNC fg=#3c3836 bg=#a89984 deco=reverse cterm=reverse
  hi TabLine fg=#a89984 bg=#3c3836 deco=NONE cterm=NONE
  hi TabLineFill fg=#ebdbb2 bg=#3c3836 deco=NONE cterm=NONE
  hi TabLineSel fg=#fbf1c7 bg=#1c1c1c deco=bold cterm=bold
  hi ToolbarButton fg=#fbf1c7 bg=#303030 deco=bold cterm=bold
  hi ToolbarLine fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual fg=#1c1c1c bg=#83a598 deco=NONE cterm=NONE
  hi WildMenu fg=#83a598 bg=#504945 deco=bold cterm=bold
  hi EndOfBuffer fg=#504945 bg=NONE deco=NONE cterm=NONE
  hi Conceal fg=#504945 bg=NONE deco=NONE cterm=NONE
  hi Cursor fg=#1c1c1c bg=#fbf1c7 deco=NONE cterm=NONE
  hi DiffAdd fg=#b8bb26 bg=#1c1c1c deco=reverse cterm=reverse
  hi DiffChange fg=#8ec07c bg=#1c1c1c deco=reverse cterm=reverse
  hi DiffDelete fg=#fb4934 bg=#1c1c1c deco=reverse cterm=reverse
  hi DiffText fg=#fabd2f bg=#1c1c1c deco=reverse cterm=reverse
  hi Directory fg=#b8bb26 bg=NONE deco=bold cterm=bold
  hi IncSearch fg=#fe8019 bg=#1c1c1c deco=reverse cterm=reverse
  hi ModeMsg fg=#fabd2f bg=NONE deco=bold cterm=bold
  hi MoreMsg fg=#fabd2f bg=NONE deco=bold cterm=bold
  hi Question fg=#fe8019 bg=NONE deco=bold cterm=bold
  hi Search fg=#98971a bg=#1c1c1c deco=reverse cterm=reverse
  hi QuickFixLine fg=#8ec07c bg=#1c1c1c deco=reverse cterm=reverse
  hi SpellBad fg=#fb4934 bg=NONE guisp=#fb4934 deco=undercurl cterm=underline
  hi SpellCap fg=#83a598 bg=NONE guisp=#83a598 deco=undercurl cterm=underline
  hi SpellLocal fg=#8ec07c bg=NONE guisp=#8ec07c deco=undercurl cterm=underline
  hi SpellRare fg=#d3869b bg=NONE guisp=#d3869b deco=undercurl cterm=underline
  hi Title fg=#b8bb26 bg=NONE deco=bold cterm=bold
  hi WarningMsg fg=#fb4934 bg=NONE deco=bold cterm=bold
  hi Boolean fg=#d3869b bg=NONE deco=NONE cterm=NONE
  hi Character fg=#d3869b bg=NONE deco=NONE cterm=NONE
  hi Conditional fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Constant fg=#d3869b bg=NONE deco=NONE cterm=NONE
  hi Define fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi Debug fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Delimiter fg=#fe8019 bg=NONE deco=NONE cterm=NONE
  hi Error fg=#fb4934 bg=#1c1c1c deco=bold,reverse cterm=bold,reverse
  hi Exception fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Float fg=#d3869b bg=NONE deco=NONE cterm=NONE
  hi Function fg=#b8bb26 bg=NONE deco=bold cterm=bold
  hi Identifier fg=#83a598 bg=NONE deco=NONE cterm=NONE
  hi Ignore fg=fg bg=NONE deco=NONE cterm=NONE
  hi Include fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi Keyword fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Label fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Macro fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi Number fg=#d3869b bg=NONE deco=NONE cterm=NONE
  hi Operator fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi PreCondit fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi PreProc fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi Repeat fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi SpecialChar fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi SpecialComment fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi Statement fg=#fb4934 bg=NONE deco=NONE cterm=NONE
  hi StorageClass fg=#fe8019 bg=NONE deco=NONE cterm=NONE
  hi Special fg=#fe8019 bg=NONE deco=NONE cterm=NONE
  hi String fg=#b8bb26 bg=NONE deco=NONE cterm=NONE
  hi Structure fg=#8ec07c bg=NONE deco=NONE cterm=NONE
  hi Todo fg=fg bg=#1c1c1c deco=bold cterm=bold
  hi Type fg=#fabd2f bg=NONE deco=NONE cterm=NONE
  hi Typedef fg=#fabd2f bg=NONE deco=NONE cterm=NONE
  hi Underlined fg=#83a598 bg=NONE deco=underline cterm=underline
  hi CursorIM fg=#1c1c1c bg=#fbf1c7 deco=NONE cterm=NONE
else
  " Light background
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#3c3836', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#7c6f64', '#928374', '#9d0006', '#79740e', '#b57614', '#076678', '#8f3f71', '#427b58', '#fbf1c7']
  endif
  hi Normal fg=#3c3836 bg=#fbf1c7 deco=NONE cterm=NONE
  hi CursorLineNr fg=#b57614 bg=#fbf1c7 deco=bold cterm=bold
  hi FoldColumn fg=#928374 bg=#fbf1c7 deco=NONE cterm=NONE
  hi SignColumn fg=#3c3836 bg=#fbf1c7 deco=NONE cterm=NONE
  hi VertSplit fg=#bdae93 bg=#fbf1c7 deco=NONE cterm=NONE
  hi ColorColumn fg=NONE bg=#ebe1b7 deco=NONE cterm=NONE
  hi Comment fg=#928374 bg=NONE deco=NONE cterm=NONE
  hi CursorLine fg=NONE bg=#e5d4b1 deco=NONE cterm=NONE
  hi Error fg=#9d0006 bg=#fbf1c7 deco=bold,reverse cterm=bold,reverse
  hi ErrorMsg fg=#fbf1c7 bg=#9d0006 deco=bold cterm=bold
  hi Folded fg=#928374 bg=#ffffd7 deco=NONE cterm=NONE
  hi LineNr fg=#a89984 bg=NONE deco=NONE cterm=NONE
  hi MatchParen fg=NONE bg=#e5d4b1 deco=bold,underline cterm=bold,underline
  hi NonText fg=#e5d4b1 bg=NONE deco=NONE cterm=NONE
  hi Pmenu fg=#3c3836 bg=#e5d4b1 deco=NONE cterm=NONE
  hi PmenuSbar fg=NONE bg=#e5d4b1 deco=NONE cterm=NONE
  hi PmenuSel fg=#e5d4b1 bg=#076678 deco=bold cterm=bold
  hi PmenuThumb fg=NONE bg=#a89984 deco=NONE cterm=NONE
  hi PmenuKind fg=#9d0006 bg=#e5d4b1 deco=NONE cterm=NONE
  hi PmenuKindSel fg=#9d0006 bg=#076678 deco=NONE cterm=NONE
  hi PmenuExtra fg=#7c6f64 bg=#e5d4b1 deco=NONE cterm=NONE
  hi PmenuExtraSel fg=#bdae93 bg=#076678 deco=NONE cterm=NONE
  hi PmenuMatch fg=#8f3f71 bg=#e5d4b1 deco=NONE cterm=NONE
  hi PmenuMatchSel fg=#d3869b bg=#076678 deco=bold cterm=bold
  hi SpecialKey fg=#928374 bg=NONE deco=NONE cterm=NONE
  hi StatusLine fg=#bdae93 bg=#3c3836 deco=bold,reverse cterm=bold,reverse
  hi StatusLineNC fg=#ebdbb2 bg=#3c3836 deco=reverse cterm=reverse
  hi TabLine fg=#665c54 bg=#ebdbb2 deco=NONE cterm=NONE
  hi TabLineFill fg=#ebdbb2 bg=#ebdbb2 deco=NONE cterm=NONE
  hi TabLineSel fg=#282828 bg=#fbf1c7 deco=bold cterm=bold
  hi ToolbarButton fg=#282828 bg=#bdae93 deco=bold cterm=bold
  hi ToolbarLine fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Visual fg=#fbf1c7 bg=#076678 deco=NONE cterm=NONE
  hi WildMenu fg=#076678 bg=#e5d4b1 deco=bold cterm=bold
  hi EndOfBuffer fg=#e5d4b1 bg=NONE deco=NONE cterm=NONE
  hi Conceal fg=#a89984 bg=NONE deco=NONE cterm=NONE
  hi Cursor fg=#fbf1c7 bg=#282828 deco=NONE cterm=NONE
  hi DiffAdd fg=#79740e bg=#fbf1c7 deco=reverse cterm=reverse
  hi DiffChange fg=#427b58 bg=#fbf1c7 deco=reverse cterm=reverse
  hi DiffDelete fg=#9d0006 bg=#fbf1c7 deco=reverse cterm=reverse
  hi DiffText fg=#b57614 bg=#fbf1c7 deco=reverse cterm=reverse
  hi Directory fg=#79740e bg=NONE deco=bold cterm=bold
  hi IncSearch fg=#ff5f00 bg=#fbf1c7 deco=reverse cterm=reverse
  hi ModeMsg fg=#3c3836 bg=NONE deco=bold cterm=bold
  hi MoreMsg fg=#3c3836 bg=NONE deco=bold cterm=bold
  hi Question fg=#ff5f00 bg=NONE deco=bold cterm=bold
  hi Search fg=#98971a bg=#fbf1c7 deco=reverse cterm=reverse
  hi QuickFixLine fg=#427b58 bg=#fbf1c7 deco=reverse cterm=reverse
  hi SpellBad fg=#9d0006 bg=NONE guisp=#9d0006 deco=undercurl cterm=underline
  hi SpellCap fg=#076678 bg=NONE guisp=#076678 deco=undercurl cterm=underline
  hi SpellLocal fg=#427b58 bg=NONE guisp=#427b58 deco=undercurl cterm=underline
  hi SpellRare fg=#8f3f71 bg=NONE guisp=#8f3f71 deco=undercurl cterm=underline
  hi Title fg=#79740e bg=NONE deco=bold cterm=bold
  hi WarningMsg fg=#9d0006 bg=NONE deco=bold cterm=bold
  hi Boolean fg=#8f3f71 bg=NONE deco=NONE cterm=NONE
  hi Character fg=#8f3f71 bg=NONE deco=NONE cterm=NONE
  hi Conditional fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Constant fg=#8f3f71 bg=NONE deco=NONE cterm=NONE
  hi Define fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi Debug fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Delimiter fg=#ff5f00 bg=NONE deco=NONE cterm=NONE
  hi Error fg=#9d0006 bg=#fbf1c7 deco=bold,reverse cterm=bold,reverse
  hi Exception fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Float fg=#8f3f71 bg=NONE deco=NONE cterm=NONE
  hi Function fg=#79740e bg=NONE deco=bold cterm=bold
  hi Identifier fg=#076678 bg=NONE deco=NONE cterm=NONE
  hi Ignore fg=fg bg=NONE deco=NONE cterm=NONE
  hi Include fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi Keyword fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Label fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Macro fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi Number fg=#8f3f71 bg=NONE deco=NONE cterm=NONE
  hi Operator fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi PreCondit fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi PreProc fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi Repeat fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi SpecialChar fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi SpecialComment fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi Statement fg=#9d0006 bg=NONE deco=NONE cterm=NONE
  hi StorageClass fg=#ff5f00 bg=NONE deco=NONE cterm=NONE
  hi Special fg=#ff5f00 bg=NONE deco=NONE cterm=NONE
  hi String fg=#79740e bg=NONE deco=NONE cterm=NONE
  hi Structure fg=#427b58 bg=NONE deco=NONE cterm=NONE
  hi Todo fg=fg bg=#fbf1c7 deco=bold cterm=bold
  hi Type fg=#b57614 bg=NONE deco=NONE cterm=NONE
  hi Typedef fg=#b57614 bg=NONE deco=NONE cterm=NONE
  hi Underlined fg=#076678 bg=NONE deco=underline cterm=underline
  hi CursorIM fg=#fbf1c7 bg=#282828 deco=NONE cterm=NONE
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=187 ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=214 ctermbg=234 cterm=bold
    hi FoldColumn ctermfg=102 ctermbg=234 cterm=NONE
    hi SignColumn ctermfg=102 ctermbg=234 cterm=NONE
    hi VertSplit ctermfg=236 ctermbg=234 cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=16 cterm=NONE
    hi Comment ctermfg=102 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
    hi Error ctermfg=203 ctermbg=234 cterm=bold,reverse
    hi ErrorMsg ctermfg=234 ctermbg=203 cterm=bold
    hi Folded ctermfg=102 ctermbg=233 cterm=NONE
    hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=239 cterm=bold,underline
    hi NonText ctermfg=239 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=187 ctermbg=237 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=237 cterm=NONE
    hi PmenuSel ctermfg=237 ctermbg=109 cterm=bold
    hi PmenuThumb ctermfg=NONE ctermbg=243 cterm=NONE
    hi PmenuKind ctermfg=203 ctermbg=237 cterm=NONE
    hi PmenuKindSel ctermfg=203 ctermbg=109 cterm=NONE
    hi PmenuExtra ctermfg=102 ctermbg=237 cterm=NONE
    hi PmenuExtraSel ctermfg=236 ctermbg=109 cterm=NONE
    hi PmenuMatch ctermfg=132 ctermbg=237 cterm=NONE
    hi PmenuMatchSel ctermfg=132 ctermbg=109 cterm=bold
    hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=239 ctermbg=187 cterm=bold,reverse
    hi StatusLineNC ctermfg=237 ctermbg=102 cterm=reverse
    hi TabLine ctermfg=102 ctermbg=237 cterm=NONE
    hi TabLineFill ctermfg=187 ctermbg=237 cterm=NONE
    hi TabLineSel ctermfg=230 ctermbg=234 cterm=bold
    hi ToolbarButton ctermfg=230 ctermbg=236 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Visual ctermfg=234 ctermbg=109 cterm=NONE
    hi WildMenu ctermfg=109 ctermbg=239 cterm=bold
    hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=239 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=234 ctermbg=230 cterm=NONE
    hi DiffAdd ctermfg=142 ctermbg=234 cterm=reverse
    hi DiffChange ctermfg=107 ctermbg=234 cterm=reverse
    hi DiffDelete ctermfg=203 ctermbg=234 cterm=reverse
    hi DiffText ctermfg=214 ctermbg=234 cterm=reverse
    hi Directory ctermfg=142 ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=208 ctermbg=234 cterm=reverse
    hi ModeMsg ctermfg=214 ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=214 ctermbg=NONE cterm=bold
    hi Question ctermfg=208 ctermbg=NONE cterm=bold
    hi Search ctermfg=100 ctermbg=234 cterm=reverse
    hi QuickFixLine ctermfg=107 ctermbg=234 cterm=reverse
    hi SpellBad ctermfg=203 ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=109 ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=107 ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=175 ctermbg=NONE cterm=underline
    hi Title ctermfg=142 ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=203 ctermbg=NONE cterm=bold
    hi Boolean ctermfg=175 ctermbg=NONE cterm=NONE
    hi Character ctermfg=175 ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=175 ctermbg=NONE cterm=NONE
    hi Define ctermfg=107 ctermbg=NONE cterm=NONE
    hi Debug ctermfg=203 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=208 ctermbg=NONE cterm=NONE
    hi Error ctermfg=203 ctermbg=234 cterm=bold,reverse
    hi Exception ctermfg=203 ctermbg=NONE cterm=NONE
    hi Float ctermfg=175 ctermbg=NONE cterm=NONE
    hi Function ctermfg=142 ctermbg=NONE cterm=bold
    hi Identifier ctermfg=109 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=107 ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=203 ctermbg=NONE cterm=NONE
    hi Label ctermfg=203 ctermbg=NONE cterm=NONE
    hi Macro ctermfg=107 ctermbg=NONE cterm=NONE
    hi Number ctermfg=175 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=107 ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=107 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=107 ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=203 ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=203 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=203 ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
    hi Special ctermfg=208 ctermbg=NONE cterm=NONE
    hi String ctermfg=142 ctermbg=NONE cterm=NONE
    hi Structure ctermfg=107 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=234 cterm=bold
    hi Type ctermfg=214 ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=214 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=109 ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=234 ctermbg=230 cterm=NONE
  else
    " Light background
    hi Normal ctermfg=237 ctermbg=230 cterm=NONE
    hi CursorLineNr ctermfg=172 ctermbg=230 cterm=bold
    hi FoldColumn ctermfg=102 ctermbg=230 cterm=NONE
    hi SignColumn ctermfg=237 ctermbg=230 cterm=NONE
    hi VertSplit ctermfg=144 ctermbg=230 cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=229 cterm=NONE
    hi Comment ctermfg=102 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=188 cterm=NONE
    hi Error ctermfg=124 ctermbg=230 cterm=bold,reverse
    hi ErrorMsg ctermfg=230 ctermbg=124 cterm=bold
    hi Folded ctermfg=102 ctermbg=231 cterm=NONE
    hi LineNr ctermfg=137 ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=188 cterm=bold,underline
    hi NonText ctermfg=188 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=237 ctermbg=188 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=188 cterm=NONE
    hi PmenuSel ctermfg=188 ctermbg=23 cterm=bold
    hi PmenuThumb ctermfg=NONE ctermbg=137 cterm=NONE
    hi PmenuKind ctermfg=124 ctermbg=188 cterm=NONE
    hi PmenuKindSel ctermfg=124 ctermbg=23 cterm=NONE
    hi PmenuExtra ctermfg=243 ctermbg=188 cterm=NONE
    hi PmenuExtraSel ctermfg=144 ctermbg=23 cterm=NONE
    hi PmenuMatch ctermfg=126 ctermbg=188 cterm=NONE
    hi PmenuMatchSel ctermfg=175 ctermbg=23 cterm=bold
    hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=144 ctermbg=237 cterm=bold,reverse
    hi StatusLineNC ctermfg=187 ctermbg=237 cterm=reverse
    hi TabLine ctermfg=59 ctermbg=187 cterm=NONE
    hi TabLineFill ctermfg=187 ctermbg=187 cterm=NONE
    hi TabLineSel ctermfg=235 ctermbg=230 cterm=bold
    hi ToolbarButton ctermfg=235 ctermbg=144 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Visual ctermfg=230 ctermbg=23 cterm=NONE
    hi WildMenu ctermfg=23 ctermbg=188 cterm=bold
    hi EndOfBuffer ctermfg=188 ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=137 ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=230 ctermbg=235 cterm=NONE
    hi DiffAdd ctermfg=64 ctermbg=230 cterm=reverse
    hi DiffChange ctermfg=29 ctermbg=230 cterm=reverse
    hi DiffDelete ctermfg=124 ctermbg=230 cterm=reverse
    hi DiffText ctermfg=172 ctermbg=230 cterm=reverse
    hi Directory ctermfg=64 ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=202 ctermbg=230 cterm=reverse
    hi ModeMsg ctermfg=237 ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=237 ctermbg=NONE cterm=bold
    hi Question ctermfg=202 ctermbg=NONE cterm=bold
    hi Search ctermfg=100 ctermbg=230 cterm=reverse
    hi QuickFixLine ctermfg=29 ctermbg=230 cterm=reverse
    hi SpellBad ctermfg=124 ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=23 ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=29 ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=126 ctermbg=NONE cterm=underline
    hi Title ctermfg=64 ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=124 ctermbg=NONE cterm=bold
    hi Boolean ctermfg=126 ctermbg=NONE cterm=NONE
    hi Character ctermfg=126 ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=124 ctermbg=NONE cterm=NONE
    hi Constant ctermfg=126 ctermbg=NONE cterm=NONE
    hi Define ctermfg=29 ctermbg=NONE cterm=NONE
    hi Debug ctermfg=124 ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=202 ctermbg=NONE cterm=NONE
    hi Error ctermfg=124 ctermbg=230 cterm=bold,reverse
    hi Exception ctermfg=124 ctermbg=NONE cterm=NONE
    hi Float ctermfg=126 ctermbg=NONE cterm=NONE
    hi Function ctermfg=64 ctermbg=NONE cterm=bold
    hi Identifier ctermfg=23 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=29 ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=124 ctermbg=NONE cterm=NONE
    hi Label ctermfg=124 ctermbg=NONE cterm=NONE
    hi Macro ctermfg=29 ctermbg=NONE cterm=NONE
    hi Number ctermfg=126 ctermbg=NONE cterm=NONE
    hi Operator ctermfg=29 ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=29 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=29 ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=124 ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=124 ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=124 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=124 ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=202 ctermbg=NONE cterm=NONE
    hi Special ctermfg=202 ctermbg=NONE cterm=NONE
    hi String ctermfg=64 ctermbg=NONE cterm=NONE
    hi Structure ctermfg=29 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=230 cterm=bold
    hi Type ctermfg=172 ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=172 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=23 ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=230 ctermbg=235 cterm=NONE
  endif
  unlet s:t_Co
  finish
endif

if s:t_Co >= 16
  if &background ==# 'dark'
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi ColorColumn ctermfg=Black ctermbg=DarkYellow cterm=NONE
    hi Comment ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=Black cterm=reverse
    hi ErrorMsg ctermfg=Black ctermbg=Red cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Folded ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=Black cterm=bold,underline
    hi NonText ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=White ctermbg=DarkGray cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=Blue cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Blue cterm=NONE
    hi PmenuKind ctermfg=DarkRed ctermbg=DarkGray cterm=NONE
    hi PmenuKindSel ctermfg=DarkRed ctermbg=Blue cterm=NONE
    hi PmenuExtra ctermfg=gray ctermbg=DarkGray cterm=NONE
    hi PmenuExtraSel ctermfg=Black ctermbg=Blue cterm=NONE
    hi PmenuMatch ctermfg=White ctermbg=DarkGray cterm=bold
    hi PmenuMatchSel ctermfg=Black ctermbg=Blue cterm=bold
    hi SignColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=gray ctermbg=Black cterm=bold,reverse
    hi StatusLineNC ctermfg=gray ctermbg=Black cterm=reverse
    hi TabLine ctermfg=Black ctermbg=DarkGray cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=DarkGray cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Black cterm=bold
    hi ToolbarButton ctermfg=White ctermbg=DarkGray cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=Black ctermbg=gray cterm=NONE
    hi Visual ctermfg=Black ctermbg=Blue cterm=NONE
    hi WildMenu ctermfg=White ctermbg=Black cterm=bold
    hi EndOfBuffer ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=Black ctermbg=White cterm=NONE
    hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
    hi DiffChange ctermfg=Cyan ctermbg=Black cterm=reverse
    hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
    hi DiffText ctermfg=Yellow ctermbg=Black cterm=reverse
    hi Directory ctermfg=Green ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=Magenta ctermbg=Black cterm=reverse
    hi ModeMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Search ctermfg=DarkGreen ctermbg=Black cterm=reverse
    hi QuickFixLine ctermfg=Cyan ctermbg=Black cterm=reverse
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=Blue ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=underline
    hi Title ctermfg=Green ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
    hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=Black cterm=bold,reverse
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Function ctermfg=Green ctermbg=NONE cterm=bold
    hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Label ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=Black cterm=bold
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=Black ctermbg=White cterm=NONE
  else
    " Light background
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi ColorColumn ctermfg=White ctermbg=Grey cterm=NONE
    hi Comment ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=reverse
    hi ErrorMsg ctermfg=White ctermbg=Red cterm=NONE
    hi FoldColumn ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Folded ctermfg=Grey ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Grey ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=NONE ctermbg=White cterm=bold,underline
    hi NonText ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=Black ctermbg=Grey cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
    hi PmenuSel ctermfg=White ctermbg=Blue cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Blue cterm=NONE
    hi PmenuKind ctermfg=DarkRed ctermbg=Grey cterm=NONE
    hi PmenuKindSel ctermfg=DarkRed ctermbg=Blue cterm=NONE
    hi PmenuExtra ctermfg=DarkGray ctermbg=Grey cterm=NONE
    hi PmenuExtraSel ctermfg=White ctermbg=Blue cterm=NONE
    hi PmenuMatch ctermfg=Black ctermbg=Grey cterm=bold
    hi PmenuMatchSel ctermfg=White ctermbg=Blue cterm=bold
    hi SignColumn ctermfg=Grey ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=Grey ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=DarkGray ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Grey ctermbg=DarkGray cterm=reverse
    hi TabLine ctermfg=DarkGray ctermbg=Grey cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Grey cterm=NONE
    hi TabLineSel ctermfg=DarkGray ctermbg=White cterm=bold
    hi ToolbarButton ctermfg=Black ctermbg=Grey cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=DarkGray ctermbg=Grey cterm=NONE
    hi Visual ctermfg=White ctermbg=Blue cterm=NONE
    hi WildMenu ctermfg=Black ctermbg=White cterm=bold
    hi EndOfBuffer ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=White ctermbg=DarkGray cterm=NONE
    hi DiffAdd ctermfg=Green ctermbg=White cterm=reverse
    hi DiffChange ctermfg=Cyan ctermbg=White cterm=reverse
    hi DiffDelete ctermfg=Red ctermbg=White cterm=reverse
    hi DiffText ctermfg=Yellow ctermbg=White cterm=reverse
    hi Directory ctermfg=Green ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=Magenta ctermbg=White cterm=reverse
    hi ModeMsg ctermfg=Black ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Black ctermbg=NONE cterm=bold
    hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Search ctermfg=DarkGreen ctermbg=White cterm=reverse
    hi QuickFixLine ctermfg=Cyan ctermbg=White cterm=reverse
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=Blue ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=underline
    hi Title ctermfg=Green ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
    hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=bold,reverse
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Function ctermfg=Green ctermbg=NONE cterm=bold
    hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Label ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=White cterm=bold
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=White ctermbg=DarkGray cterm=NONE
  endif
  unlet s:t_Co
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    hi Normal ctermfg=gray ctermbg=Black cterm=NONE
    hi ColorColumn ctermfg=Black ctermbg=gray cterm=NONE
    hi Comment ctermfg=gray ctermbg=NONE cterm=bold
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=Black cterm=reverse
    hi ErrorMsg ctermfg=Black ctermbg=Red cterm=NONE
    hi FoldColumn ctermfg=gray ctermbg=NONE cterm=NONE
    hi Folded ctermfg=gray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=gray ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=gray ctermbg=NONE cterm=bold,underline
    hi NonText ctermfg=gray ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=DarkGray ctermbg=White cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi PmenuSel ctermfg=Black ctermbg=Blue cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Blue cterm=NONE
    hi PmenuKind ctermfg=Red ctermbg=White cterm=NONE
    hi PmenuKindSel ctermfg=Red ctermbg=Blue cterm=NONE
    hi PmenuExtra ctermfg=DarkGray ctermbg=White cterm=NONE
    hi PmenuExtraSel ctermfg=DarkGray ctermbg=Blue cterm=NONE
    hi PmenuMatch ctermfg=DarkGray ctermbg=White cterm=bold
    hi PmenuMatchSel ctermfg=Black ctermbg=Blue cterm=bold
    hi SignColumn ctermfg=gray ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=gray ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=gray ctermbg=Black cterm=bold,reverse
    hi StatusLineNC ctermfg=gray ctermbg=Black cterm=reverse
    hi TabLine ctermfg=Black ctermbg=gray cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=gray cterm=NONE
    hi TabLineSel ctermfg=gray ctermbg=Black cterm=NONE
    hi ToolbarButton ctermfg=Black ctermbg=gray cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=Black ctermbg=gray cterm=NONE
    hi Visual ctermfg=Black ctermbg=Blue cterm=NONE
    hi WildMenu ctermfg=Blue ctermbg=DarkGray cterm=bold
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=Black ctermbg=White cterm=NONE
    hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
    hi DiffChange ctermfg=Cyan ctermbg=Black cterm=reverse
    hi DiffDelete ctermfg=Red ctermbg=Black cterm=reverse
    hi DiffText ctermfg=Yellow ctermbg=Black cterm=reverse
    hi Directory ctermfg=Green ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=Magenta ctermbg=Black cterm=reverse
    hi ModeMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Yellow ctermbg=NONE cterm=bold
    hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Search ctermfg=DarkGreen ctermbg=Black cterm=reverse
    hi QuickFixLine ctermfg=Cyan ctermbg=Black cterm=reverse
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=Blue ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=underline
    hi Title ctermfg=Green ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
    hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=Black cterm=bold,reverse
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Function ctermfg=Green ctermbg=NONE cterm=bold
    hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Label ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=Black cterm=bold
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=Black ctermbg=White cterm=NONE
  else
    " Light background
    hi Normal ctermfg=Black ctermbg=Grey cterm=NONE
    hi ColorColumn ctermfg=White ctermbg=Black cterm=NONE
    hi Comment ctermfg=Black ctermbg=NONE cterm=bold
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=reverse
    hi ErrorMsg ctermfg=White ctermbg=Red cterm=NONE
    hi FoldColumn ctermfg=Black ctermbg=NONE cterm=NONE
    hi Folded ctermfg=Black ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Black ctermbg=NONE cterm=NONE
    hi MatchParen ctermfg=Black ctermbg=NONE cterm=bold,underline
    hi NonText ctermfg=Black ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=Grey ctermbg=Black cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=Grey cterm=NONE
    hi PmenuSel ctermfg=White ctermbg=Blue cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Blue cterm=NONE
    hi PmenuKind ctermfg=Red ctermbg=Black cterm=NONE
    hi PmenuKindSel ctermfg=Red ctermbg=Blue cterm=NONE
    hi PmenuExtra ctermfg=Grey ctermbg=Black cterm=NONE
    hi PmenuExtraSel ctermfg=Grey ctermbg=Blue cterm=NONE
    hi PmenuMatch ctermfg=Grey ctermbg=Black cterm=bold
    hi PmenuMatchSel ctermfg=White ctermbg=Blue cterm=bold
    hi SignColumn ctermfg=Black ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=Black ctermbg=NONE cterm=NONE
    hi StatusLine ctermfg=Black ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Black ctermbg=White cterm=reverse
    hi TabLine ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=White cterm=NONE
    hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi VertSplit ctermfg=White ctermbg=Black cterm=NONE
    hi Visual ctermfg=White ctermbg=Blue cterm=NONE
    hi WildMenu ctermfg=Blue ctermbg=Grey cterm=bold
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Conceal ctermfg=Grey ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=White ctermbg=DarkGray cterm=NONE
    hi DiffAdd ctermfg=Green ctermbg=White cterm=reverse
    hi DiffChange ctermfg=Cyan ctermbg=White cterm=reverse
    hi DiffDelete ctermfg=Red ctermbg=White cterm=reverse
    hi DiffText ctermfg=Yellow ctermbg=White cterm=reverse
    hi Directory ctermfg=Green ctermbg=NONE cterm=bold
    hi IncSearch ctermfg=Magenta ctermbg=White cterm=reverse
    hi ModeMsg ctermfg=Black ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=Black ctermbg=NONE cterm=bold
    hi Question ctermfg=Magenta ctermbg=NONE cterm=bold
    hi Search ctermfg=DarkGreen ctermbg=White cterm=reverse
    hi QuickFixLine ctermfg=Cyan ctermbg=White cterm=reverse
    hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
    hi SpellCap ctermfg=Blue ctermbg=NONE cterm=underline
    hi SpellLocal ctermfg=Cyan ctermbg=NONE cterm=underline
    hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=underline
    hi Title ctermfg=Green ctermbg=NONE cterm=bold
    hi WarningMsg ctermfg=Red ctermbg=NONE cterm=bold
    hi Boolean ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Character ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Conditional ctermfg=Red ctermbg=NONE cterm=NONE
    hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Define ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Debug ctermfg=Red ctermbg=NONE cterm=NONE
    hi Delimiter ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=bold,reverse
    hi Exception ctermfg=Red ctermbg=NONE cterm=NONE
    hi Float ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Function ctermfg=Green ctermbg=NONE cterm=bold
    hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=fg ctermbg=NONE cterm=NONE
    hi Include ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Keyword ctermfg=Red ctermbg=NONE cterm=NONE
    hi Label ctermfg=Red ctermbg=NONE cterm=NONE
    hi Macro ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreCondit ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Repeat ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialChar ctermfg=Red ctermbg=NONE cterm=NONE
    hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
    hi Statement ctermfg=Red ctermbg=NONE cterm=NONE
    hi StorageClass ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi String ctermfg=Green ctermbg=NONE cterm=NONE
    hi Structure ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Todo ctermfg=fg ctermbg=White cterm=bold
    hi Type ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=Blue ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=White ctermbg=DarkGray cterm=NONE
  endif
  unlet s:t_Co
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi CurSearch term=reverse
  hi CursorLineFold term=underline
  hi CursorLineSign term=underline
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co
  finish
endif

" Color: neutralred              #cc241d        160            DarkRed
" Color: neutralgreen            #98971a        100            DarkGreen
" Color: neutralyellow           #d79921        172            DarkYellow
" Color: neutralblue             #458588        66             DarkBlue
" Color: neutralpurple           #b16286        132            DarkMagenta
" Color: neutralaqua             #689d6a        71             DarkCyan
" Color: neutralorange           #d65d0e        166            LightRed
" Background: dark
" Color: bg0                     #1c1c1c        234            Black
" Color: bg1                     #3c3836        237            DarkGray
" Color: bg2                     #504945        239            DarkGray
" Color: bg3                     #303030        236
" Color: bg4                     #7c6f64        243
" Color: bg5                     #000000        16             DarkGray
" Color: bg6                     #121212        233            DarkGray
" Color: fg0                     #fbf1c7        230            White
" Color: fg1                     #ebdbb2        187            White
" Color: fg2                     #d5c4a1        187
" Color: fg3                     #bdae93        144
" Color: fg4                     #a89984        102            gray
" Color: grey                    #928374        102            DarkGray
" Color: red                     #fb4934        203            Red
" Color: green                   #b8bb26        142            Green
" Color: yellow                  #fabd2f        214            Yellow
" Color: blue                    #83a598        109            Blue
" Color: purple                  #d3869b        175            Magenta
" Color: aqua                    #8ec07c        107            Cyan
" Color: orange                  #fe8019        208            Magenta
" Term colors: bg0  neutralred neutralgreen neutralyellow neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red        green        yellow        blue        purple        aqua        fg1
" Background: light
" Color: bg0                     #fbf1c7        230            White
" Color: bg1                     #ebdbb2        187            Grey
" Color: bg2                     #e5d4b1        188            Grey
" Color: bg3                     #bdae93        144
" Color: bg4                     #a89984        137            Grey
" Color: bg5                     #ebe1b7        229            Grey
" Color: bg6                     #ffffd7        231            Grey
" Color: fg0                     #282828        235            DarkGray
" Color: fg1                     #3c3836        237            Black
" Color: fg2                     #503836        237
" Color: fg3                     #665c54        59
" Color: fg4                     #7c6f64        243            Black
" Color: grey                    #928374        102            DarkGray
" Color: red                     #9d0006        124            Red
" Color: green                   #79740e        64             Green
" Color: yellow                  #b57614        172            Yellow
" Color: blue                    #076678        23             Blue
" Color: purple                  #8f3f71        126            Magenta
" Color: lightpurple             #d3869b        175            Magenta
" Color: aqua                    #427b58        29             Cyan
" Color: orange                  #ff5f00        202            Magenta
" Term colors: fg1  neutralred neutralgreen neutralyellow neutralblue neutralpurple neutralaqua fg4
" Term colors: grey red        green        yellow        blue        purple        aqua        bg0
" Background: any
" vim: et ts=8 sw=2 sts=2
