/* src/channel.c */
Channel *add_channel(void);
int has_any_channel(void);
int channel_still_useful(Channel *channel);
int channel_can_close(Channel *channel);
int channel_unref(Channel *channel);
int free_unused_channels_contents(int copyID, int mask);
void free_unused_channels(int copyID, int mask);
void mch_delay(long msec, int flags);
void ch_close_part(Channel *channel, ChannelFdKind part);
void channel_set_pipes(Channel *channel, Socket in, Socket out, Socket err);
void channel_set_job(Channel *channel, Job *job, JobOptions *options);
void channel_write_in(Channel *channel);
void chaFreeBook(Book *book);
void channel_write_any_lines(void);
void channel_write_new_lines(Book *book);
ReadChunk *channel_peek(Channel *channel, ChannelFdKind part);
CS channel_first_nl(ReadChunk *node);
void channel_consume(Channel *channel, ChannelFdKind part, int len);
int channel_collapse(Channel *channel, ChannelFdKind part, int want_nl);
int channel_can_write_to(Channel *channel);
int channel_is_open(Channel *channel);
void channel_clear(Channel *channel);
void channel_free_all(void);
int channel_in_blocking_wait(void);
Channel *get_channel_arg(Var *tv, int check_open, int reading, ChannelFdKind part);
void channel_set_nonblock(Channel *channel, ChannelFdKind part);
int channel_send(Channel *channel, ChannelFdKind part, CS buf_arg, int len_arg, char *fun);
int channel_select_setup(int maxfd_in, void *rfds_in, void *wfds_in, TimeVal *tv, TimeVal **tvp);
int channel_select_check(int ret_in, void *rfds_in, void *wfds_in);
int channel_parse_messages(void);
int channel_any_readahead(void);
int set_ref_in_channel(int copyID);
void f_ch_canread(Var *argvars, Var *returnVar);
void f_ch_close(Var *argvars, Var *returnVar);
void f_ch_close_in(Var *argvars, Var *returnVar);
void f_ch_getbufnr(Var *argvars, Var *returnVar);
void f_ch_getjob(Var *argvars, Var *returnVar);
void f_ch_info(Var *argvars, Var *returnVar);
void f_ch_open(Var *argvars, Var *returnVar);
void f_ch_read(Var *argvars, Var *returnVar);
void f_ch_readblob(Var *argvars, Var *returnVar);
void f_ch_readraw(Var *argvars, Var *returnVar);
void f_ch_evalexpr(Var *argvars, Var *returnVar);
void f_ch_sendexpr(Var *argvars, Var *returnVar);
void f_ch_evalraw(Var *argvars, Var *returnVar);
void f_ch_sendraw(Var *argvars, Var *returnVar);
void f_ch_setoptions(Var *argvars, Var *returnVar);
void f_ch_status(Var *argvars, Var *returnVar);
void channel_to_string_buf(CS builder, Var *varp);
void build_argv_from_string(CS cmd, Byte ***argv, int *argc);
int build_argv_from_list(List *l, Byte ***argv, int *argc);
void setIgnoreSigTstp(int newVal);
void set_signals(void);
int chCallShell(CS cmd, CS extraArg, Unt options);
int mch_create_pty_channel(Job *job, JobOptions *options);
void chBreakcheck(Boole force);
SigHandler mch_signal(int sig, SigHandler func);
void mch_early_init(void);
long mch_get_pid(void);
int mch_process_running(long pid);
void may_core_dump(void);
void sig_winch(int sigarg);
void sig_tstp(int sigarg);
void reset_signals(void);
int eeHandleSignal(int sig);
int mch_get_uname(uid_t uid, CS s, int len);
void mch_get_host_name(CS s, int len);
int mch_signal_job(Job *job, CS how);
void free_job_options(JobOptions *opt);
void mch_clear_job(Job *job);
int get_job_options(Var *tv, JobOptions *opt, int supported, int supported2);
void job_free_all(void);
int job_any_running(void);
void job_cleanup(Job *job);
int set_ref_in_job(int copyID);
void job_unref(Job *job);
int free_unused_jobs_contents(int copyID, int mask);
void free_unused_jobs(int copyID, int mask);
Job *job_alloc(void);
void job_set_options(Job *job, JobOptions *opt);
void job_stop_on_exit(void);
int has_pending_job(void);
int job_check_ended(void);
Job *startJob(Var *argvars, Byte **argv_arg, JobOptions *opt_arg, Job **term_job);
CS job_status(Job *job);
int job_stop(Job *job, Var *argvars, CS type);
void invoke_prompt_callback(void);
int invoke_prompt_interrupt(void);
CS prompt_text(void);
void init_prompt(int cmdchar_todo);
int prompt_curpos_editable(void);
void f_prompt_setcallback(Var *argvars, Var *returnVar);
void f_prompt_setinterrupt(Var *argvars, Var *returnVar);
void f_prompt_getprompt(Var *argvars, Var *returnVar);
void f_prompt_setprompt(Var *argvars, Var *returnVar);
void f_job_getchannel(Var *argvars, Var *returnVar);
void f_job_info(Var *argvars, Var *returnVar);
void f_job_setoptions(Var *argvars, Var *returnVar);
void f_startJob(Var *argvars, Var *returnVar);
void f_job_status(Var *argvars, Var *returnVar);
void f_job_stop(Var *argvars, Var *returnVar);
void job_to_string_buf(CS builder, Var *varp);
int unix_build_argv(CS cmd, Byte ***argvp, CS extraArg, CS *shcf_tofree);
void ch_logfile(CS fname, CS opt);
int ch_log_active(void);
void f_ch_log(Var *argvars, Var *returnVar);
void f_ch_logfile(Var *argvars, Var *returnVar);
void server_to_input_buf(CS str);
CS eval_client_expr_to_string(CS expr);
int sendToLocalEm(CS cmd, int asExpr, Byte **result);
void exec_on_server(MainParams *params);
void prepare_server(MainParams *params);
void f_remote_expr(Var *argvars, Var *returnVar);
void f_remote_foreground(Var *argvars, Var *returnVar);
void f_remote_peek(Var *argvars, Var *returnVar);
void f_remote_read(Var *argvars, Var *returnVar);
void f_remote_send(Var *argvars, Var *returnVar);
void f_remote_startserver(Var *argvars, Var *returnVar);
void f_server2client(Var *argvars, Var *returnVar);
void f_serverlist(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
