/* src/clipboard.c */
YankReg *get_y_regs(void);
YankReg *get_y_register(int reg);
YankReg *get_y_current(void);
YankReg *get_y_previous(void);
void set_y_current(YankReg *yreg);
void set_y_previous(YankReg *yreg);
void reset_y_append(void);
int get_expr_register(void);
void set_expr_line(CS new_line, Invocation *invo);
CS get_expr_line(void);
int valid_yank_reg(int regname, int writing);
int get_yank_register(int regname, int writing);
void *get_register(int name, int copy);
void put_register(int name, void *reg);
void free_register(void *reg);
int yank_register_mline(int regname);
int do_record(int c);
int get_execreg_lastc(void);
void set_execreg_lastc(int lastc);
int do_execreg(int regname, int colon, int addcr, int silent);
int insert_reg(int regname, int literally_arg);
int get_spec_reg(int regname, CS *retVal, int *allocated, int errmsg);
int cmdline_paste_reg(int regname, int literally_arg, int remcr);
void shift_delete_registers(void);
void yank_do_autocmd(Operator *opArg, YankReg *reg);
void init_yank(void);
void clear_registers(void);
void free_yank_all(void);
int op_yank(Operator *opArg, int deleting, int mess);
void do_put(int regname, CS expr_result, Unt dir, long count, Unt flags);
int get_register_name(int num);
int get_unname_register(void);
void c_display(Invocation *invo);
void dnd_yank_drag_data(CS str, long len);
Byte get_reg_type(int regname, long *reglen);
CS get_reg_contents(int regname, int flags);
void write_reg_contents(int name, CS str, int maxlen, int must_append);
void write_reg_contents_lst(int name, Byte **strings, int maxlen, int must_append, int yank_type, long block_len);
void write_reg_contents_ex(int name, CS str, int maxlen, int must_append, int yank_type, long block_len);
void clip_init(int can_use);
void clip_update_selection(ClipBoard *clip);
void clip_own_selection(ClipBoard *cbd);
void clip_lose_selection(ClipBoard *cbd);
void start_global_changes(void);
void end_global_changes(void);
void clip_auto_select(void);
void clip_modeless(int button, int is_click, int is_drag);
void clip_start_selection(int col, int row, int repeated_click);
void clip_process_selection(int button, int col, int row, Unt repeated_click);
void clip_clear_selection(ClipBoard *cbd);
void clip_may_clear_selection(int row1, int row2);
void clip_scroll_selection(int rows);
void clip_copy_modeless_selection(int both);
void open_app_context(void);
void x11_setup_atoms(Display *dpy);
void clip_x11_request_selection(Widget myShell, Display *dpy, ClipBoard *cbd);
void clip_x11_lose_selection(Widget myShell, ClipBoard *cbd);
int clip_x11_own_selection(Widget myShell, ClipBoard *cbd);
void clip_x11_set_selection(ClipBoard *cbd);
void yank_cut_buffer0(Display *dpy, ClipBoard *cbd);
void clip_free_selection(ClipBoard *cbd);
void clip_get_selection(ClipBoard *cbd);
int clip_convert_selection(Byte **str, Ulong *len, ClipBoard *cbd);
int may_get_selection(int regname);
void adjust_clip_reg(int *rp);
/* eegl: set ft=c : */
