/* src/data.c */
void ga_clear(ArrayList *gap);
void ga_clear_strings(ArrayList *gap);
int ga_copy_strings(ArrayList *from, ArrayList *to);
void ga_init(ArrayList *gap);
void ga_init2(ArrayList *gap, Unt itemsize, int growsize);
int ga_grow(ArrayList *gap, int n);
int ga_grow_id(ArrayList *gap, int n, AllocId id);
int ga_grow_inner(ArrayList *gap, int n);
CS ga_concat_strings(ArrayList *gap, char *sep);
int ga_copy_string(ArrayList *gap, CS p);
int ga_add_string(ArrayList *gap, CS p);
void ga_concat(ArrayList *gap, CS s);
void ga_concat_len(ArrayList *gap, CS s, Unt len);
int ga_append(ArrayList *gap, int c);
void append_ga_line(ArrayList *gap);
void list_add_watch(List *l, ListWatch *lw);
void list_rem_watch(List *l, ListWatch *lwrem);
List *list_alloc(void);
List *list_alloc_id(AllocId id);
List *list_alloc_with_items(int count);
void list_set_item(List *l, int idx, Var *tv);
void allocReturnList(Var *returnVar);
int allocReturnList_id(Var *returnVar, AllocId id);
void returnVar_list_set(Var *returnVar, List *l);
void list_unref(List *l);
int list_free_nonref(int copyID);
void list_free_items(int copyID);
void list_free(List *l);
ListItem *listitem_alloc(void);
void listitem_free(List *l, ListItem *item);
void listitem_remove(List *l, ListItem *item);
long list_len(List *l);
int list_equal(List *l1, List *l2, int ic);
ListItem *list_find(List *l, long n);
long list_find_nr(List *l, long idx, Boole *errorp);
CS list_find_str(List *l, long idx);
ListItem *list_find_index(List *l, long *idx);
long list_idx_of_item(List *l, ListItem *item);
void list_append(List *l, ListItem *item);
int list_append_tv(List *l, Var *newVal);
int listAppendBag(List *list, Bag *bag);
int list_append_list(List *list1, List *list2);
int list_append_string(List *l, CS str, int len);
int list_append_number(List *l, Long n);
int list_insert_tv(List *l, Var *tv, ListItem *item);
void list_insert(List *l, ListItem *ni, ListItem *item);
ListItem *check_range_index_one(List *l, long *n1, int quiet);
int check_range_index_two(List *l, long *n1, ListItem *li1, long *n2, int quiet);
int list_assign_range(List *dest, List *src, long idx1_arg, long idx2, int empty_idx2, CS op, Text varname);
void f_flatten(Var *argvars, Var *returnVar);
void f_flattennew(Var *argvars, Var *returnVar);
void list2items(Var *argvars, Var *returnVar);
void string2items(Var *argvars, Var *returnVar);
int list_extend(List *l1, List *l2, ListItem *bef);
int list_concat(List *l1, List *l2, Var *tv);
List *list_slice(List *ol, long n1, long n2);
int list_slice_or_index(List *list, int range, Long n1_arg, Long n2_arg, int exclusive, Var *returnVar, int verbose);
List *list_copy(List *orig, int deep, int top, int copyID);
void list_remove(List *l, ListItem *item, ListItem *item2);
CS list2string(Var *tv, int copyID, int restore_copyID);
int list_join(ArrayList *gap, List *l, CS sep, int echo_style, int restore_copyID, int copyID);
void f_join(Var *argvars, Var *returnVar);
int eval_list(Byte **arg, Var *returnVar, EvalCtx *evalarg, int do_error);
int write_list(FILE *fd, List *list, int binary);
void init_static_list(StaticList10 *sl);
void f_list2str(Var *argvars, Var *returnVar);
void f_sort(Var *argvars, Var *returnVar);
void f_uniq(Var *argvars, Var *returnVar);
int filter_map_one(Var *tv, Var *expr, FilterMap filtermap, Var *newtv, int *remp);
void f_filter(Var *argvars, Var *returnVar);
void f_map(Var *argvars, Var *returnVar);
void f_mapnew(Var *argvars, Var *returnVar);
void f_foreach(Var *argvars, Var *returnVar);
void f_add(Var *argvars, Var *returnVar);
void f_count(Var *argvars, Var *returnVar);
void f_extend(Var *argvars, Var *returnVar);
void f_extendnew(Var *argvars, Var *returnVar);
void f_insert(Var *argvars, Var *returnVar);
void f_remove(Var *argvars, Var *returnVar);
void f_reverse(Var *argvars, Var *returnVar);
void f_reduce(Var *argvars, Var *returnVar);
void f_slice(Var *argvars, Var *returnVar);
int cmp_keyvalue_value(const void *a, const void *b);
int cmp_keyvalue_value_n(const void *a, const void *b);
int cmp_keyvalue_value_i(const void *a, const void *b);
int cmp_keyvalue_value_ni(const void *a, const void *b);
DictStringInt128 *dictStringInt128New(Byte const *text, Int *values, Int size, Arena *a);
DictStringInt128 *dictStringInt128NewJustIndices(Byte const *text, Int size, Arena *a);
Boole containsKey_DictStringInt128(Byte const *needle, DictStringInt128 *restrict haystack);
Int get_DictStringInt128(Byte const *needle, DictStringInt128 *restrict haystack);
Int get_Text_DictStringInt128(Text needle, DictStringInt128 *restrict haystack);
Int getOrDefault_DictStringInt128(Byte const *needle, Int defaultValue, DictStringInt128 *restrict haystack);
Int getOrDefault_Text_DictStringInt128(Text needle, Int defaultValue, DictStringInt128 *restrict haystack);
Int getKv_Text_DictStringInt128(Unt *key, Text needle, DictStringInt128 *restrict haystack);
void hash_init(EeSet *ht);
int check_hashtab_frozen(EeSet *ht, CS command);
void hash_clear(EeSet *ht);
void hash_clear_all(EeSet *ht, int off);
EeSetItem *hash_find(EeSet *ht, Text key);
EeSetItem *hash_lookup(EeSet *ht, Text key, Hash hash);
void hash_debug_results(void);
int hash_add(EeSet *ht, Text key, CS command);
int hash_add_item(EeSet *ht, EeSetItem *hi, Text newItem, Hash hash);
int hash_remove(EeSet *ht, EeSetItem *hi, CS command);
void hash_lock(EeSet *ht);
void hash_lock_size(EeSet *ht, int size);
void hash_unlock(EeSet *ht);
Hash calcHash(Text const key);
void sha256_start(ContextSha256 *ctx);
void sha256_update(ContextSha256 *ctx, CS input, Unt length);
void sha256_finish(ContextSha256 *ctx, Byte digest[32]);
CS sha256_bytes(CS buf, int buf_len, CS salt, int salt_len);
CS sha256_key(CS buf, CS salt, int salt_len);
int sha256_self_test(void);
void sha2_seed(CS header, int header_len, CS salt, int salt_len);
void *mergesort_list(void *head, void *(*get_next)(void *), void (*set_next)(void *, void *), void *(*get_prev)(void *), void (*set_prev)(void *, void *), int (*compare)(const void *, const void *));
ExpandMatch expandMatchOfArrayList(ArrayList al);
void addExpandMatch(CS m, ExpandMatch *t);
int type_any_or_unknown(TypeSpec *type);
char *vartype_name(VarTag type);
Var *allocVar(void);
Var *allocStringVar(CS s);
void freeVar(Var *varp);
void clearVar(Var *varp);
void initVarToNull(Var *varp);
Long tv_get_number(Var *varp);
Long varGetNumberChk(Var *varp, Boole *denote);
Boole tv_get_bool(Var *varp);
double tv_get_float(Var *varp);
int check_for_unknown_arg(Var *args, int idx);
int check_for_string_arg(Var *args, int idx);
int check_for_nonempty_string_arg(Var *args, int idx);
int check_for_opt_string_arg(Var *args, int idx);
int check_for_number_arg(Var *args, int idx);
int check_for_opt_number_arg(Var *args, int idx);
int check_for_float_or_nr_arg(Var *args, int idx);
int check_for_bool_arg(Var *args, int idx);
int check_for_opt_bool_arg(Var *args, int idx);
int check_for_opt_bool_or_number_arg(Var *args, int idx);
int check_for_blob_arg(Var *args, int idx);
int confirmVarIsList(Var *arg, int idx);
int confirmVarIsNonnullList(Var *args, int idx);
int confirmVarIsOptionalList(Var *args, int idx);
int check_for_dict_arg(Var *args, int idx);
int check_for_nonnull_dict_arg(Var *args, int idx);
int check_for_oself_arg(Var *args, int idx);
int check_for_opt_nonnull_dict_arg(Var *args, int idx);
int check_for_chan_or_job_arg(Var *args, int idx);
int check_for_opt_chan_or_job_arg(Var *args, int idx);
int check_for_job_arg(Var *args, int idx);
int check_for_opt_job_arg(Var *args, int idx);
int check_for_string_or_number_arg(Var *args, int idx);
int check_for_opt_string_or_number_arg(Var *args, int idx);
int check_for_buffer_arg(Var *args, int idx);
int check_for_opt_buffer_arg(Var *args, int idx);
int check_for_lnum_arg(Var *args, int idx);
int check_for_opt_lnum_arg(Var *args, int idx);
int check_for_string_or_blob_arg(Var *args, int idx);
int check_for_string_or_list_arg(Var *args, int idx);
int check_for_opt_string_or_list_arg(Var *args, int idx);
int check_for_string_or_dict_arg(Var *args, int idx);
int check_for_string_or_number_or_list_arg(Var *args, int idx);
int check_for_opt_string_or_number_or_list_arg(Var *args, int idx);
int check_for_repeat_func_arg(Var *args, int idx);
int check_for_string_list_or_dict_arg(Var *args, int idx);
int check_for_string_or_func_arg(Var *args, int idx);
int check_for_list_or_blob_arg(Var *args, int idx);
int check_for_list_arg(Var *args, int idx);
int check_for_list_or_or_blob_arg(Var *args, int idx);
int check_for_list_or_dict_arg(Var *args, int idx);
int check_for_list_or_dict_or_blob_arg(Var *args, int idx);
int check_for_list_dict_blob_or_string_arg(Var *args, int idx);
int check_for_opt_buffer_or_dict_arg(Var *args, int idx);
CS tv_get_string(Var *varp);
CS tv_get_string_strict(Var *varp);
CS tv_get_string_buf(Var *varp, CS buf);
CS convertVarToStringSingleUse(Var *varp);
CS convertVarToString(Var *varp, CS buf);
CS convertVarToString_strict(Var *varp, CS buf, int strict);
CS tv_stringify(Var *varp, CS buf);
int tv_check_lock(Var *tv, Text name, Boole use_gettext);
void copy_tv(Var *to, Var *from);
int typval_compare(Var *tv1, Var *tv2, ExprType type, Boole ignoreCase);
int typval_compare_list(Var *tv1, Var *tv2, ExprType type, Boole ic, int *res);
int typval_compare_null(Var *tv1, Var *tv2);
int typval_compare_blob(Var *tv1, Var *tv2, ExprType type, int *res);
int typval_compare_dict(Var *tv1, Var *tv2, ExprType type, int ic, int *res);
int typval_compare_func(Var *tv1, Var *tv2, ExprType type, int ic, int *res);
int typval_compare_string(Var *tv1, Var *tv2, ExprType type, Boole ignoreCase, int *res);
CS typval_tostring(Var *arg, int quotes);
int tv_islocked(Var *tv);
int tv_equal(Var *tv1, Var *tv2, int ic);
int eval_option(Byte **arg, Var *returnVar, int evaluate);
int eval_number(CS *arg, Var *returnVar, int evaluate, int want_string);
CS tv2string(Var *tv, Byte **tofree, CS numbuf, int copyID);
int eval_env_var(CS *arg, Var *returnVar, int evaluate);
LineNr tv_get_lnum(Var *argvars);
LineNr daGetLnumFromBookOrVar(Var *argvars, Book *book);
Book *daGetBook(Var *tv, Boole curtab_only);
Book *daGetBookFromArg(Var *tv);
int equal_type(TypeSpec *type1, TypeSpec *type2, int flags);
ExprType get_compare_type(CS p, int *len, int *type_is);
int tv2bool(Var *tv);
Bag *allocBag(void);
Bag *allocBag_id(AllocId id);
Bag *allocBag_lock(int lock);
void allocReturnDict(Var *returnVar);
void returnVar_dict_set(Var *returnVar, Bag *d);
CS char_from_string(CS str, Long index);
Text textOfDi(DictItem *di);
Text textOfDi16(DictItem16 *di);
Text textOfItem(EeSetItem *si);
int bagAdd(Bag *b, DictItem *item);
int bagAddNumber(Bag *d, CS key, Long nr);
int bagAdd_bool(Bag *d, CS key, Long nr);
int bagAddString(Bag *d, CS key, CS str);
int bagAddString_len(Bag *d, CS key, CS str, int len);
int bagAddList(Bag *d, CS key, List *list);
int bagAddVar(Bag *b, CS key, Var *tv);
int bagAddCallback(Bag *d, CS key, Callback *cb);
int bagAddFn(Bag *d, CS key, UserFunc *fp);
void bagIterateStart(Var *var, DictIterator *iter);
CS bagIterateNext(DictIterator *iter, Var **tv_result);
int bagAddBag(Bag *d, CS key, Bag *dict);
Ulong bagSize(Bag *b);
DictItem *bagFind(Bag *b, Text const key);
int bagHasKey(Bag *b, Text key);
int bagGetVar(Bag *d, Text key, Var *returnVar);
CS bagGetString(Bag *d, Text key, Boole save);
Long bagGetNumber(Bag *d, Text key);
Long bagGetNumber_def(Bag *b, Text const key, int def);
Long bagGetNumber_check(Bag *b, Text const key);
Boole bagGetBool(Bag *d, Text key, Boole def);
CS bagToString(Var *tv, int copyID, int restore_copyID);
int bagEval(CS *arg, Var *returnVar, EvalCtx *evalarg, int literal);
int bagEvalLiteral(CS *arg, Var *returnVar, EvalCtx *evalarg);
void bagExtend(Bag *d1, Bag *d2, CS action);
DictItem *bagLookup(EeSetItem *hi);
int bagEqual(Bag *d1, Bag *d2, int ic);
long bagCount(Bag *d, Var *needle, int ic);
void bagExtend_func(Var *argvars, CS arg_errmsg, int is_new, Var *returnVar);
void bagFilterMap(Bag *d, FilterMap filtermap, CS arg_errmsg, Var *expr, Var *returnVar);
void bagRemove(Var *argvars, Var *returnVar, CS arg_errmsg);
void f_items(Var *argvars, Var *returnVar);
void f_keys(Var *argvars, Var *returnVar);
void f_values(Var *argvars, Var *returnVar);
void bagSetItemsRo(Bag *di);
void f_has_key(Var *argvars, Var *returnVar);
CS string_slice(CS str, Long first, Long last, int exclusive);
void bagUnref(Bag *d);
int dict_free_nonref(int copyID);
void hashtab_free_contents(EeSet *ht);
void dict_free_items(int copyID);
void dict_free_contents(Bag *d);
DictItem *dictitem_alloc(Text value);
void dictitem_remove(Bag *bag, DictItem *item, CS command);
void dictitem_free(DictItem *item);
Bag *dict_copy(Bag *orig, int deep, int top, int copyID);
int dictWrongFuncName(Bag *b, Var *tv, Text name);
CS json_encode(Var *val, int options);
CS json_encode_nr_expr(int nr, Var *val, int options);
CS json_encode_lsp_msg(Var *val);
int json_decode(Var *res, JsReader *reader);
int json_find_end(JsReader *reader);
void f_json_decode(Var *argvars, Var *returnVar);
void f_json_encode(Var *argvars, Var *returnVar);
int string2float(CS text, double *value, Boole skip_quotes);
void f_abs(Var *argvars, Var *returnVar);
void f_acos(Var *argvars, Var *returnVar);
void f_asin(Var *argvars, Var *returnVar);
void f_atan(Var *argvars, Var *returnVar);
void f_atan2(Var *argvars, Var *returnVar);
void f_ceil(Var *argvars, Var *returnVar);
void f_cos(Var *argvars, Var *returnVar);
void f_cosh(Var *argvars, Var *returnVar);
void f_exp(Var *argvars, Var *returnVar);
void f_float2nr(Var *argvars, Var *returnVar);
void f_floor(Var *argvars, Var *returnVar);
void f_fmod(Var *argvars, Var *returnVar);
void f_isinf(Var *argvars, Var *returnVar);
void f_isnan(Var *argvars, Var *returnVar);
void f_log(Var *argvars, Var *returnVar);
void f_log10(Var *argvars, Var *returnVar);
void f_pow(Var *argvars, Var *returnVar);
void f_sqrt(Var *argvars, Var *returnVar);
void f_str2float(Var *argvars, Var *returnVar);
void f_tan(Var *argvars, Var *returnVar);
void f_tanh(Var *argvars, Var *returnVar);
void f_trunc(Var *argvars, Var *returnVar);
void f_round(Var *argvars, Var *returnVar);
void f_sin(Var *argvars, Var *returnVar);
void f_sinh(Var *argvars, Var *returnVar);
void f_assert_equal(Var *argvars, Var *returnVar);
void f_assert_equalfile(Var *argvars, Var *returnVar);
void f_assert_notequal(Var *argvars, Var *returnVar);
void f_assert_exception(Var *argvars, Var *returnVar);
void f_assert_fails(Var *argvars, Var *returnVar);
void f_assert_false(Var *argvars, Var *returnVar);
void f_assert_inrange(Var *argvars, Var *returnVar);
void f_assert_match(Var *argvars, Var *returnVar);
void f_assert_notmatch(Var *argvars, Var *returnVar);
void f_assert_report(Var *argvars, Var *returnVar);
void f_assert_true(Var *argvars, Var *returnVar);
void f_test_alloc_fail(Var *argvars, Var *returnVar);
void f_test_autochdir(Var *argvars, Var *returnVar);
void f_test_feedinput(Var *argvars, Var *returnVar);
void f_test_getvalue(Var *argvars, Var *returnVar);
void f_test_option_not_set(Var *argvars, Var *returnVar);
void f_test_override(Var *argvars, Var *returnVar);
void f_test_refcount(Var *argvars, Var *returnVar);
void f_test_garbagecollect_now(Var *argvars, Var *returnVar);
void f_test_garbagecollect_soon(Var *argvars, Var *returnVar);
void f_test_ignore_error(Var *argvars, Var *returnVar);
void f_test_null_blob(Var *argvars, Var *returnVar);
void f_test_null_channel(Var *argvars, Var *returnVar);
void f_test_null_dict(Var *argvars, Var *returnVar);
void f_test_null_job(Var *argvars, Var *returnVar);
void f_test_null_list(Var *argvars, Var *returnVar);
void f_test_null_function(Var *argvars, Var *returnVar);
void f_test_null_partial(Var *argvars, Var *returnVar);
void f_test_null_string(Var *argvars, Var *returnVar);
void f_test_unknown(Var *argvars, Var *returnVar);
void f_test_void(Var *argvars, Var *returnVar);
void f_test_setmouse(Var *argvars, Var *returnVar);
void f_test_settime(Var *argvars, Var *returnVar);
int check_can_index(Var *var, int evaluate, int verbose);
int eval_index_inner(Var *returnVar, int is_range, Var *var1, Var *var2, int exclusive, CS key, int keylen, int verbose);
int binarySearch_Unt(Unt key, int start, int end, Unt *arr);
Blob *blob_alloc(void);
int returnVar_blob_alloc(Var *returnVar);
void returnVar_blob_set(Var *returnVar, Blob *b);
int blob_copy(Blob *from, Var *to);
void blob_free(Blob *b);
void blob_unref(Blob *b);
long blob_len(Blob *b);
int blob_get(Blob *b, int idx);
void blob_set(Blob *blob, int idx, int byte);
void blob_set_append(Blob *blob, int idx, int byte);
int blob_equal(Blob *b1, Blob *b2);
CS blob2string(Blob *blob, Byte **tofree, Byte *numbuf);
Blob *string2blob(CS str);
int blob_slice_or_index(Blob *blob, int is_range, Long n1, Long n2, int exclusive, Var *returnVar);
int check_blob_index(long bloblen, Long n1, int quiet);
int check_blob_range(long bloblen, Long n1, Long n2, int quiet);
int blob_set_range(Blob *dest, long n1, long n2, Var *src);
void blob_add(Var *argvars, Var *returnVar);
void blob_remove(Var *argvars, Var *returnVar, CS arg_errmsg);
void blob_filter_map(Blob *blob_arg, FilterMap filtermap, Var *expr, CS arg_errmsg, Var *returnVar);
void blob_insert_func(Var *argvars, Var *returnVar);
void blob_reduce(Var *argvars, Var *expr, Var *returnVar);
void blob_reverse(Blob *b, Var *returnVar);
void f_blob2list(Var *argvars, Var *returnVar);
void f_list2blob(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
