/* src/diff.c */
void diff_buf_delete(Book *book);
void diff_buf_adjust(Portal *po);
void diff_buf_add(Book *book);
void diff_invalidate(Book *book);
void diff_mark_adjust(LineNr line1, LineNr line2, long amount, long amount_after);
void diff_redraw(int dofold);
int diff_internal(void);
void c_diffupdate(Invocation *invo);
void c_diffpatch(Invocation *invo);
void c_diffsplit(Invocation *invo);
void c_diffthis(Invocation *invo);
void diff_win_options(Portal *wp, int addbuf);
void c_diffoff(Invocation *invo);
void diff_clear(Tab *t);
int diff_check_with_linestatus(Portal *wp, LineNr lnum, LineDiffStatus *linestatus);
int diff_check_fill(Portal *wp, LineNr lnum);
void diff_set_topline(Portal *fromPort, Portal *toPort);
int diffanchors_changed(CS newVal, Boole buflocal);
int diffopt_changed(void);
int diffopt_horizontal(void);
int diffopt_hiddenoff(void);
int diffopt_closeoff(void);
void diff_update_line(LineNr lnum);
int diff_change_parse(DiffLine *diffline, DifflineChange *change, int *change_start, int *change_end);
int diff_find_change(Portal *wp, LineNr lnum, DiffLine *diffline);
int diff_infold(Portal *wp, LineNr lnum);
void nvDiffGetPut(int put, long count);
void c_diffgetput(Invocation *invo);
Boole diffIsBookInDiffMode(Book *book);
int diff_move_to(int dir, long count);
LineNr diff_get_corresponding_line(Book *buf1, LineNr lnum1);
LineNr diff_lnum_win(LineNr lnum, Portal *wp);
void f_diff_filler(Var *argvars, Var *returnVar);
void f_diff_hlID(Var *argvars, Var *returnVar);
void f_diff(Var *argvars, Var *returnVar);
int xdl_num_out(char *out, long val);
void *xdl_alloc_grow_helper(void *p, long nr, long *alloc, Unt size);
/* eegl: set ft=c : */
