/* src/do.c */
void do_ascii(Invocation *invo);
void c_align(Invocation *invo);
void c_sort(Invocation *invo);
void c_uniq(Invocation *invo);
int do_move(LineNr line1, LineNr line2, LineNr dest);
void free_prev_shellcmd(void);
void do_bang(int addr_count, Invocation *invo, Boole forceit, Boole do_in, Boole do_out);
void do_shell(CS cmd, Unt flags);
int prompt_for_number(int *mouse_used);
CS make_filter_cmd(CS cmd, CS inputFName, CS outputFName);
void append_redir(CS buf, int buflen, CS opt, CS fname);
void do_fixdel(Invocation *invo);
void c_file(Invocation *invo);
void c_update(Invocation *invo);
void c_write(Invocation *invo);
int do_write(Invocation *invo);
int copy_option_part(CS *option, CS builder, int maxlen, char *sep_chars);
int check_overwrite(Invocation *invo, Book *book, Byte *fname, Byte *fullFName, int other);
void c_wnext(Invocation *invo);
void do_wqall(Invocation *invo);
int getfile(int fnum, CS ffname_arg, CS sfname_arg, int setpm, LineNr lnum, Boole forceit);
int startEditingFile(int fnum, CS fullFName, CS sfname, Invocation *invo, LineNr newlnum, Unt flags, Portal *oldPort);
void c_append(Invocation *invo);
void c_change(Invocation *invo);
void c_z(Invocation *invo);
Byte *skip_substitute(Byte *start, int delimiter);
void c_substitute(Invocation *invo);
int do_sub_msg(int count_only);
Byte *get_old_sub(void);
void set_old_sub(Byte *val);
void free_old_sub(void);
void c_global(Invocation *invo);
void global_exe(Byte *cmd);
int prepare_tagpreview(int undo_sync, int use_previewpopup, UsePopup use_popup);
void c_smile(Invocation *invo);
void c_drop(Invocation *invo);
CS skipEeglGrepPat(CS p, Byte **s, Unt *flags);
void c_oldfiles(Invocation *invo);
void c_listDo(Invocation *invo);
void c_compiler(Invocation *invo);
void c_checktime(Invocation *invo);
int autowrite(Book *book, int forceit);
void doFlushAllBooks(void);
int check_changed(Book *book, int flags);
void dialog_changed(Book *book, int checkall);
int check_changed_any(int hidden, int unload);
int check_fname(void);
int bookWrite_all(Book *book, int forceit);
int executeCommLine(Byte *cmd);
void handle_did_throw(void);
int getline_equal(LineGetter fgetline, void *cookie, LineGetter func);
void *getline_cookie(LineGetter fgetline, void *cookie);
CS getline_peek(LineGetter fgetline, void *cookie);
int doCommand(CS commline, LineGetter fgetline, void *cookie, Unt flags);
CS ex_errmsg(CS msg, CS arg);
CS ex_range_without_command(Invocation *invo);
int checkforcmd(Byte **pp, char *cmd, int len);
int checkforcmd_noparen(Byte **pp, char *cmd, int len);
int parse_command_modifiers(Invocation *invo, CS *errorMsg, CommandModifier *cmod, int skip_only);
void applyCommModifiers(CommandModifier *cmod);
void undoCommModifier(CommandModifier *cmod);
int parse_cmd_address(Invocation *invo, CS *errorMsg, int silent);
CS skip_option_env_lead(CS start);
int number_method(CS cmd);
Byte *findCommand(Invocation *invo, int *full, int (*lookup)(Byte *, Unt, int cmd));
int modifier_len(CS cmd);
int cmd_exists(Byte *name);
void f_fullcommand(Var *argvars, Var *returnVar);
CommIndex commandGetInd(Byte *cmd, int len);
long commandGetFlags(CommIndex idx);
CS skip_range(CS cmd_start, int skip_star, Unt *ctx);
LineNr doGetCommandAddress(Invocation *invo, CS *ptr, CommandAddress addressKind, int skip, int silent, int to_other_file, int address_count);
void c_ni(Invocation *invo);
int expand_filename(Invocation *invo, Byte **commline, CS *errorMsg);
void separateNextCommand(Invocation *invo, int keep_backslash);
Byte *skip_cmd_arg(Byte *p, int rembs);
int get_bad_opt(Byte *p, Invocation *invo);
int expand_argopt(CS pat, Expand *xp, RegMatch *rmp, ExpandMatch *matches);
void c_autocmd(Invocation *invo);
void c_doautocmd(Invocation *invo);
void c_bunload(Invocation *invo);
void c_book(Invocation *invo);
void c_bmodified(Invocation *invo);
void c_bnext(Invocation *invo);
void c_bprevious(Invocation *invo);
void c_brewind(Invocation *invo);
void c_blast(Invocation *invo);
int endsComm(CS c);
CS find_nextcmd(Byte *p);
CS check_nextcmd(CS p);
void set_nextcmd(Invocation *invo, CS arg);
CS get_command_name(Expand *xp, int idx);
void c_hilite(Invocation *invo);
void not_exiting(void);
void c_quit(Invocation *invo);
void c_cquit(Invocation *invo);
int before_quit_all(Invocation *invo);
void c_quit_all(Invocation *invo);
void c_close(Invocation *invo);
void c_pclose(Invocation *invo);
void c_tabclose(Invocation *invo);
void c_tabonly(Invocation *invo);
void tabClose(void);
void tabCloseOther(Tab *t);
void c_only(Invocation *invo);
void c_hide(Invocation *invo);
void c_exit(Invocation *invo);
void c_print(Invocation *invo);
void c_goto(Invocation *invo);
void c_shell(Invocation *invo);
void c_preserve(Invocation *invo);
void c_recover(Invocation *invo);
void c_wrongmodifier(Invocation *invo);
int expand_findfunc(CS pat, ExpandMatch *matches);
CS setFindFn(OptionChange *cha);
void doFreeFindFnOption(void);
int set_ref_in_findfunc(int copyID);
void c_splitview(Invocation *invo);
void tabNew(void);
void c_tabnext(Invocation *invo);
void c_tabmove(Invocation *invo);
void c_tabs(Invocation *invo);
void c_mode(Invocation *invo);
void c_resize(Invocation *invo);
void c_find(Invocation *invo);
void c_open(Invocation *invo);
void c_edit(Invocation *invo);
void do_exedit(Invocation *invo, Portal *old_curPor);
void c_swapname(Invocation *invo);
void c_syncbind(Invocation *invo);
void c_read(Invocation *invo);
void free_cd_dir(void);
void post_chdir(CdScopeKind scope);
void trigger_DirChangedPre(Byte *acmd_fname, Byte *new_dir);
int changedir_func(CS new_dir, CdScopeKind scope);
void c_cd(Invocation *invo);
void c_pwd(Invocation *invo);
void c_equal(Invocation *invo);
void c_sleep(Invocation *invo);
void do_sleep(long msec, int hide_cursor);
void c_wincmd(Invocation *invo);
void c_portPos(Invocation *invo);
void c_operators(Invocation *invo);
void c_put(Invocation *invo);
void c_iput(Invocation *invo);
void c_copymove(Invocation *invo);
void c_join(Invocation *invo);
void c_at(Invocation *invo);
void c_bang(Invocation *invo);
void c_undo(Invocation *invo);
void c_wundo(Invocation *invo);
void c_rundo(Invocation *invo);
void c_redo(Invocation *invo);
void c_later(Invocation *invo);
void c_redir(Invocation *invo);
void c_redraw(Invocation *invo);
void redraw_cmd(int clear);
void c_redrawstatus(Invocation *invo);
void c_redrawtabpanel(Invocation *invo);
int eeMkdir_emsg(Byte *name, int prot);
FILE *open_exfile(Byte *fname, int forceit, char *mode);
void c_mark(Invocation *invo);
void update_topline_cursor(void);
int save_current_state(SaveState *sst);
void restore_current_state(SaveState *sst);
void c_normal(Invocation *invo);
void c_startinsert(Invocation *invo);
void c_stopinsert(Invocation *invo);
void exec_normal_cmd(Byte *cmd, int remap, int silent);
void exec_normal(int was_typed, int use_vpeekc, int may_use_terminal_loop);
void c_checkpath(Invocation *invo);
void c_psearch(Invocation *invo);
void c_findpat(Invocation *invo);
void c_ptag(Invocation *invo);
void c_pedit(Invocation *invo);
void c_pbuffer(Invocation *invo);
void c_stag(Invocation *invo);
void c_tag(Invocation *invo);
int find_commline_var(Byte *src, Unt *usedlen);
CS evalVars(LineNr *lnump, CS *errorMsg, CS src, Byte *srcstart, Unt *usedlen, int *escaped, int empty_is_error);
CS expand_sfile(CS arg);
void dialog_msg(CS buff, CS format, CS fname);
void c_filetype(Invocation *invo);
void c_setfiletype(Invocation *invo);
void setHlsearch(Boole flag);
void c_nohlsearch(Invocation *invo);
void c_fold(Invocation *invo);
void c_foldopen(Invocation *invo);
void c_folddo(Invocation *invo);
int get_pressedreturn(void);
void set_pressedreturn(int val);
int commandFlagNoSpacesInExtra(void);
int commandFlagExpandWildcards(void);
int ask_yesno(Byte *str, int direct);
CS expand_env_save(CS src);
CS expand_env_save_opt(CS src, Boole one);
Unt doExpandEnv(Text dst, CS src);
Unt doExpandEnvVarsWithEscaped(Text dst, CS srcArg, Boole esc, Boole one, CS startstr);
CS eeglGetEnv(CS name);
void eeUnsetenv(CS var);
void eeSetenv_ext(Byte *name, Byte *val);
void eeSetenv(CS name, CS val);
void line_breakcheck(void);
void fast_breakcheck(void);
void veryfast_breakcheck(void);
int u_save_cursor(void);
int u_save(LineNr top, LineNr bot);
int u_savesub(LineNr lnum);
int u_savedel(LineNr lnum, long nlines);
int undo_allowed(void);
int u_savecommon(LineNr top, LineNr bot, LineNr newbot, int reload);
void u_compute_hash(CS hash);
void u_write_undo(Byte *name, int forceit, Book *book, Byte *hash);
void u_read_undo(Byte *name, Byte *hash, Byte *orig_name);
void u_undo(int count);
void u_redo(int count);
void undo_time(long step, int sec, int file, int absolute);
void u_sync(int force);
void c_undolist(Invocation *invo);
void c_undojoin(Invocation *invo);
void u_unchanged(Book *book);
void u_find_first_changed(void);
void u_update_save_nr(Book *book);
void invalidateUndoBufferAndFreeBlocks(Book *book);
void u_clearline(void);
void u_undoline(void);
Boole doWasBookChanged(Book *book);
Boole doWasAnyBookChanged(void);
int doWasCurBookChanged(void);
void f_undofile(Var *argvars, Var *returnVar);
void u_undofile_reset_and_delete(Book *book);
void f_undotree(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
