/* src/draw.c */
void drawInit(void);
Decoration getPortcolorDeco(Portal *po);
int screen_get_current_line_off(void);
void resetActiveDeco(void);
void screen_line(int row, int coloff, int endcol, int clear_width, ColNr last_vcol, Unt flags);
int stl_connected(Portal *po);
int drawGetKeymapStr(Portal *po, Text buf);
void screen_putchar(int c, Unt row, Unt col, char decoFlags);
void screen_getbytes(int row, int col, Byte *bytes, Byte *decoFlags);
void drawText(CS text, Unt row, Unt col, Byte decoFlags);
void drawTextLen(CS text, int textlen, Unt row, int col, Byte decoFlagsArg);
void end_search_hl(void);
void drawStopHilite(void);
void reset_cterm_colors(void);
void screen_draw_rectangle(int row, int col, int height, int width, Boole invert);
void fillRowsWithTwoChars(Unt start_row, Unt end_row, Unt start_col, Unt end_col, Unt c1, Unt c2, Decoration deco);
void check_for_delay(int check_msg_scroll);
Boole screen_valid(Boole doclear);
void screenalloc(Boole doclear);
void free_screenlines(void);
int screenclear(void);
void drawLineWasClobbered(int screen_lnum);
int can_clear(CS p);
void screen_start(void);
void windgoto(int row, int col);
void setcursor(void);
void setcursor_mayforce(int force);
int insertLinesIntoPortal(Portal *po, int row, int line_count, int invalid, int mayclear);
int deleteLinesFromPortal(Portal *po, int row, int line_count, int invalid, int mayclear, Unt clearHiId);
int drawInsertLines(int off, int row, int line_count, int end, int clearHiId, Portal *po);
int screen_del_lines(int off, int row, int line_count, int end, int force, Int clearHiId, Portal *po);
int skip_showmode(void);
int showmode(void);
void unshowmode(int force);
void clearmode(void);
void drawGetTranslatedBookName(Book *book);
Unt statusLineNextChar(Decoration *deco, Portal *po);
int redrawing(void);
int messaging(void);
void computeColumnsForRulerAndCommand(void);
int number_width(Portal *po);
int screen_screencol(void);
int screen_screenrow(void);
CS set_chars_option(CS newVal, Boole is_listchars, ErrBuilder *errb);
CS drawSetFillChars(CS newVal, ErrBuilder *errb);
CS drawSetListChars(CS newVal, ErrBuilder *errb);
CS get_fillchars_name(Expand *xp, int idx);
CS get_listchars_name(Expand *xp, int idx);
CS check_chars_options(CS newVal);
int drawUpdateScreen(Unt type_arg);
void redrawPortalStatusLine(Portal *po, Boole ignore_pum);
void showruler(int always);
void after_updating_screen(int may_resize_shell);
void drawUpdateCurBook(Unt type);
int redraw_asap(int type);
void redraw_after_callback(int call_drawUpdateScreen, int do_message);
void redraw_later(int type);
void redrawPortLater(Portal *po, Unt type);
void redraw_later_clear(void);
void redraw_all_later(Unt type);
void drawSetMustRedraw(Unt type);
void drawCurBookLater(int type);
void drawBookLater(Book *book, int type);
void drawBookLineLater(Book *book, LineNr lnum);
void drawBookAndStatusLater(Book *book, int type);
void status_redraw_all(void);
void drawAllStatusLinesOfCurBookLater(void);
void redraw_statuslines(void);
void redrawAllStatusLinesInFrame(Frame *fr);
void drawPortLineLater(Portal *po, LineNr lnum);
void redrawPortRangeLater(Portal *po, LineNr first, LineNr last);
int text_prop_position(Portal *po, TextProp *t, int vcol, int scr_col, int *countExtraBytes, Byte **extraBytes, int *numDecoCells, int *toSkipBeforeDeco, int do_skip);
int drawLineOnScreen(Portal *port, LineNr lnum, int startrow, int endrow, int drawingOnlyNumberCol);
void f_screenattr(Var *argvars, Var *returnVar);
void f_screenchar(Var *argvars, Var *returnVar);
void f_screenchars(Var *argvars, Var *returnVar);
void f_screencol(Var *argvars, Var *returnVar);
void f_screenrow(Var *argvars, Var *returnVar);
void f_screenstring(Var *argvars, Var *returnVar);
void drawMsgScrollUp(void);
void drawMsgSetCharAtOffset(Unt c, int off, ScreenCell cell);
Byte drawGetLineWrap(int row);
ColNr drawGetScreenCol(int offset);
ColNr drawGetOffset(int row);
Boole drawHasLines(void);
Byte drawGetLine(int offset);
CS drawGetLinesWithOffset(Unt row);
Unt drawGetScreenComposingChar(int offset, Unt composeInd);
Unt drawGetScreenUnicodeChar(int offset);
