/* src/draw.c */
Decoration getPortcolorDeco(Portal *po);
int screen_get_current_line_off(void);
void resetActiveDeco(void);
void screen_line(int row, int coloff, int endcol, int clear_width, ColNr last_vcol, int flags);
int stl_connected(Portal *po);
int get_keymap_str(Portal *po, CS fmt, CS buf, int len);
void screen_putchar(int c, Unt row, Unt col, char decoFlags);
void screen_getbytes(int row, int col, Byte *bytes, char *decoFlags);
void drawText(Byte *text, Unt row, Unt col, char decoFlags);
void drawTextLen(CS text, int textlen, Unt row, int col, char flagsArg);
void start_search_hl(void);
void end_search_hl(void);
void drawStopHilite(void);
void reset_cterm_colors(void);
void screen_char(unsigned off, int row, int col);
void screen_draw_rectangle(int row, int col, int height, int width, int invert);
void fillRowsWithTwoChars(Unt start_row, Unt end_row, Unt start_col, Unt end_col, int c1, int c2, char decoFlags);
void check_for_delay(int check_msg_scroll);
int screen_valid(int doclear);
void screenalloc(int doclear);
void free_screenlines(void);
int screenclear(void);
void line_was_clobbered(int screen_lnum);
int can_clear(CS p);
void screen_start(void);
void windgoto(int row, int col);
void setcursor(void);
void setcursor_mayforce(int force);
int insertLinesIntoPortal(Portal *po, int row, int line_count, int invalid, int mayclear);
int deleteLinesFromPortal(Portal *po, int row, int line_count, int invalid, int mayclear, Unt clearHiId);
int screen_ins_lines(int off, int row, int line_count, int end, int clearHiId, Portal *po);
int screen_del_lines(int off, int row, int line_count, int end, int force, Int clearHiId, Portal *po);
int skip_showmode(void);
int showmode(void);
void unshowmode(int force);
void clearmode(void);
void get_trans_bufname(Book *buf);
Unt statusLineNextChar(Decoration *deco, Portal *po);
int redrawing(void);
int messaging(void);
void computeColumnsForRulerAndCommand(void);
int number_width(Portal *po);
int screen_screencol(void);
int screen_screenrow(void);
CS set_chars_option(CS newVal, Boole is_listchars, ErrBuilder *errb);
CS drawSetFillChars(CS newVal, ErrBuilder *errb);
CS drawSetListChars(CS newVal, ErrBuilder *errb);
CS get_fillchars_name(Expand *xp, int idx);
CS get_listchars_name(Expand *xp, int idx);
CS check_chars_options(CS newVal);
int update_screen(int type_arg);
void redrawPortalStatusLine(Portal *po, int ignore_pum);
void showruler(int always);
void after_updating_screen(int may_resize_shell);
void update_curbuf(int type);
int redraw_asap(int type);
void redraw_after_callback(int call_update_screen, int do_message);
void redraw_later(int type);
void redrawPortLater(Portal *po, int type);
void redraw_later_clear(void);
void redraw_all_later(int type);
void set_must_redraw(int type);
void redraw_curbuf_later(int type);
void redraw_buf_later(Book *buf, int type);
void redraw_buf_line_later(Book *buf, LineNr lnum);
void redraw_buf_and_status_later(Book *buf, int type);
void status_redraw_all(void);
void status_redraw_curbuf(void);
void redraw_statuslines(void);
void redrawAllStatusLinesInFrame(Frame *fr);
void redrawWinline(Portal *po, LineNr lnum);
void redrawPortRangeLater(Portal *po, LineNr first, LineNr last);
int text_prop_position(Portal *po, TextProp *t, int vcol, int scr_col, int *countExtraBytes, Byte **extraBytes, int *numDecoCells, int *toSkipBeforeDeco, int do_skip);
int drawLineOnScreen(Portal *port, LineNr lnum, int startrow, int endrow, int drawingOnlyNumberCol, SpellVars *spv);
/* eegl: set ft=c : */
