/* src/fileio.c */
void init_homedir(void);
int file_is_readable(CS fname);
void f_chdir(Var *argvars, Var *returnVar);
void f_delete(Var *argvars, Var *returnVar);
void f_executable(Var *argvars, Var *returnVar);
void f_exepath(Var *argvars, Var *returnVar);
void f_filereadable(Var *argvars, Var *returnVar);
void f_filewritable(Var *argvars, Var *returnVar);
void f_finddir(Var *argvars, Var *returnVar);
void f_findfile(Var *argvars, Var *returnVar);
void f_fnamemodify(Var *argvars, Var *returnVar);
void f_getcwd(Var *argvars, Var *returnVar);
CS getfpermst(FileStat *st, CS perm);
void f_getfperm(Var *argvars, Var *returnVar);
void f_getfsize(Var *argvars, Var *returnVar);
void f_getftime(Var *argvars, Var *returnVar);
CS getftypest(FileStat *st);
void f_getftype(Var *argvars, Var *returnVar);
void f_glob(Var *argvars, Var *returnVar);
void f_glob2regpat(Var *argvars, Var *returnVar);
void f_globpath(Var *argvars, Var *returnVar);
void f_isdirectory(Var *argvars, Var *returnVar);
void f_isabsolutepath(Var *argvars, Var *returnVar);
void f_mkdir(Var *argvars, Var *returnVar);
void f_pathshorten(Var *argvars, Var *returnVar);
void f_readdir(Var *argvars, Var *returnVar);
void f_readdirex(Var *argvars, Var *returnVar);
void f_readblob(Var *argvars, Var *returnVar);
void f_readfile(Var *argvars, Var *returnVar);
void f_resolve(Var *argvars, Var *returnVar);
void f_tempname(Var *argvars, Var *returnVar);
void f_writefile(Var *argvars, Var *returnVar);
void f_browse(Var *argvars, Var *returnVar);
void f_browsedir(Var *argvars, Var *returnVar);
void f_filecopy(Var *argvars, Var *returnVar);
CS fiExpandAndCopy(CS fname, int force);
int eeFexists(CS fname);
int expand_wildcards_eval(CS *pattern, Unt flags, ExpandMatch *files);
int expand_wildcards(int num_pat, CS *pat, Unt flags, ExpandMatch *files);
int gen_expand_wildcards(int num_pat, CS *pat, Unt flags, ExpandMatch *matches);
void addFile(ExpandMatch *matches, CS fName, Unt flags);
int eeFullFileName(CS fname, CS buf, int len, Boole force);
int same_directory(CS f1, CS f2);
int fullpathcmp(CS s1, CS s2, int checkname, int expandenv);
int mch_dirname(CS buf, int len);
CS home_replace_save(Book *book, CS inputFname);
CS homeReplaceA(Book *book, CS inputFname, Arena *a);
int modify_fname(CS src, int tilde_file, Unt *usedlen, CS *fnamep, CS *bufp, Unt *fnamelen);
void home_replace(CS src, CS dst, int dstlen, Boole one);
FileSearchCtx *eeFindFile_init(CS path, Text filename, CS stopdirs, int level, Boole free_visited, Unt find_what, FileSearchCtx *search_ctx_arg, Boole tagfile, CS rel_fname);
int eeChdir(CS new_dir);
int eeChdirfile(CS fname, char *trigger_autocmd);
CS eeFindFile_stopdir(CS buf);
void eeFindFile_cleanup(FileSearchCtx *ctx);
CS eeFindFile(FileSearchCtx *search_ctx_arg);
CS findFileInPath(Text fname, Unt options, Boole first, CS rel_fname, Byte **file_to_find, FileSearchCtx **searchCtx);
void free_findfile(void);
CS grab_file_name(long count, LineNr *file_lnum);
CS file_name_at_cursor(int options, long count, LineNr *file_lnum);
CS file_name_in_line(CS line, int col, int options, long count, CS rel_fname, LineNr *file_lnum);
CS find_file_name_in_path(CS ptr, int len, Unt options, long count, CS rel_fname);
Unt simplify_filename(CS filename);
int mch_has_exp_wildcard(CS p);
int mch_has_wildcard(CS p);
void f_simplify(Var *argvars, Var *returnVar);
void fiGlobpath(CS path, CS file, ExpandMatch *matches, Unt expand_options, Boole onlyDirs);
int mch_chdir(CS path);
void filemess(Book *book, CS name, CS s, int attr);
int readfile(CS fname, CS sfname, LineNr from, LineNr lines_to_skip, LineNr lines_to_read, Invocation *invo, Unt flags);
int read_blob(FILE *fd, Var *returnVar, FileOffset offset, FileOffset size_arg);
int write_blob(FILE *fd, Blob *blob);
int is_dev_fd_file(CS fname);
int prep_exarg(Invocation *invo, Book *book);
void set_file_options(Invocation *invo);
int check_file_readonly(CS fname, Unt perm);
int eeFsync(int fd);
int set_rw_fname(CS fname, CS sfname);
void msg_add_fname(Book *book, CS fname);
void msg_add_lines(int insert_space, long lnum, FileOffset nchars);
void msg_add_eol(void);
int time_differs(FileStat *st, long mtime, long mtime_ns);
CS shorten_fname1(CS full_path);
CS shorten_fname(CS full_path, CS dir_name);
void shorten_buf_fname(Book *book, CS dirname, int force);
void shorten_fnames(Boole force);
CS fiAppendFileExtension(CS fname, CS ext, Boole prepend_dot);
int eeFgets(CS buf, int size, FILE *fp);
int eeRename(CS from, CS to);
int check_timestamps(int focus);
int fiCheckBookTimestamp(Book *book);
void buf_reload(Book *book, int orig_mode, int reload_options);
void buf_store_time(Book *book, FileStat *st, CS fname);
void write_lnum_adjust(LineNr offset);
int mch_isrealdir(CS name);
Boole mch_isdir(CS name);
int mch_nodetype(CS name);
void eeDelTempDir(void);
CS eeTempName(int extra_char, int keep);
int match_file_pat(CS pattern, RegProg **prog, CS fname, CS sfname, CS tail, Boole allow_dirs);
int match_file_list(CS list, CS sfname, CS ffname);
CS file_pat_to_reg_pat(CS pat, CS pat_end, Boole *allow_dirs);
Long fiReadEintr(int fd, void *buf, Unt bufsize);
long write_eintr(int fd, void *buf, Unt bufsize);
CS get_cmd_output(CS cmd, CS infile, Unt flags, int *ret_len);
void f_system(Var *argvars, Var *returnVar);
void f_systemlist(Var *argvars, Var *returnVar);
Text fiInitSwapDir(CS progName);
int filewritable(CS fname);
int get2c(FILE *fd);
int get3c(FILE *fd);
int get4c(FILE *fd);
CS read_string(FILE *fd, int cnt);
PolyWithStatus fiCallShell(Multistring *cmd, Unt opt);
long mch_getperm(CS name);
int mch_setperm(CS name, long perm);
void mch_copy_xattr(CS from_file, CS to_file);
int mch_fsetperm(int fd, long perm);
int mch_can_exe(CS name, CS *path, int use_path);
CS fiBuildSwapOrUndoFname(CS fname, Boole isUndo);
int xxdMain(int argc, char *argv[]);
