/* src/hilite.c */
int highlight_link_id(Short hiId);
void initHilite(int reset);
void doHilite(CS line, Boole forceit, Boole init);
UiColor hiColorByName(Text name);
UiColor toUiColor(int r, int g, int b);
Decoration combineDecorations(Decoration overlay, Decoration base);
CS hiliteHasFlag(Short hiId, char flag);
Text hiliteColor(Short hiId, DecoColor which);
Short hiliteGroupByName(Text name);
Decoration decosByHiliteName(CS name);
Boole hiliteExists(Text name);
CS syn_id2name(Unt id);
char decorationByHiliteId(Short hiId);
char syn_id2colors(Short hiId, UiColor *fgp, UiColor *bgp);
Short hiResolveLinks(Unt hiId);
void setCompletionContextInHiliteCommand(Expand *xp, CS arg);
Text getHiliteGroupName(Expand *xp, int id);
CS getHiliteGroupNameAsCString(Expand *xp, int id);
int expandHiliteGroup(Byte *pattern, Expand *xp, RegMatch *rmp, ExpandMatch *matches);
void f_hlget(Var *argvars, Var *returnVar);
char getDecoFlags(Short hiId);
Decoration getFullDecoration(Unt hiId);
Boole decoEq(Decoration a, Decoration b);
void restore_cterm_colors(void);
void syntaxStartLine(Portal *wp, LineNr lnum);
void synFreeBlock(SyntaxBlock *block);
void syn_stack_apply_changes(Book *book);
void syntax_end_parsing(Portal *wp, LineNr lnum);
int syntax_check_changed(LineNr lnum);
Decoration syntGetDeco(ColNr col, int keep_state);
void syntax_clear(SyntaxBlock *block);
void reset_synblock(Portal *wp);
Short syntaxClusterByName(Text line);
void c_syntax(Invocation *invo);
void c_ownsyntax(Invocation *invo);
int syntax_present(Portal *po);
void reset_expand_highlight(void);
void set_context_in_echohl_cmd(Expand *xp, CS arg);
void set_context_in_syntax_cmd(Expand *xp, CS arg);
Byte *get_syntax_name(Expand *xp, int idx);
int syn_get_id(Portal *wp, long lnum, ColNr col, int trans, int keep_state);
int get_syntax_info(int *seqnrp);
int syn_get_stack_item(int i);
int syn_get_foldlevel(Portal *po, long lnum);
/* eegl: set ft=c : */
