/* src/input.c */
CS get_recorded(void);
Text get_inserted(void);
Unt get_keystroke(void);
int get_number(int colon, int *mouse_used);
int stuff_empty(void);
int readbuf1_empty(void);
void typeahead_noflush(int c);
void flush_buffers(FlushBuffers flush_typeahead);
void ResetRedobuff(void);
void CancelRedo(void);
void saveRedobuff(SaveRedo *save_redo);
void restoreRedobuff(SaveRedo *save_redo);
void AppendToRedobuff(Byte *s);
void AppendToRedobuffLit(CS str, int len);
void AppendToRedobuffSpec(Byte *s);
void AppendCharToRedobuff(Unt c);
void AppendNumberToRedobuff(long n);
void stuffReadbuff(CS s);
void stuffRedoReadbuff(CS s);
void stuffReadbuffLen(CS s, long len);
void stuffReadbuffSpec(CS s);
void stuffcharReadbuff(Unt c);
void stuffnumReadbuff(long n);
void stuffescaped(Byte *arg, int literally);
int start_redo(long count, int old_redo);
int start_redo_ins(void);
void stop_redo_ins(void);
int noremap_keys(void);
int insertIntoTypebuf(CS str, Unt noremap, int offset, Boole nottyped, Boole silent);
int ins_char_typebuf(int c, int modifiers);
int typebuf_changed(int tb_change_cnt);
int typebuf_typed(void);
int typebuf_maplen(void);
void del_typebuf(int len, int offset);
void gotchars_ignore(void);
void ungetchars(int len);
int save_typebuf(void);
void save_typeahead(TypeaheadSave *tp);
void restore_typeahead(TypeaheadSave *tp, Boole overwrite);
void openscript(CS name, Boole directly);
void close_all_scripts(void);
int using_script(void);
void before_blocking(void);
Unt mergeModifierKey(Unt cArg, Unt *modifiers);
Unt vgetc(void);
Unt safe_vgetc(void);
Unt plain_vgetc(void);
Unt vpeekc(void);
int vpeekc_nomap(void);
Unt vpeekc_any(void);
int char_avail(void);
void f_getchar(Var *argvars, Var *returnVar);
void f_getcharstr(Var *argvars, Var *returnVar);
void f_getcharmod(Var *argvars, Var *returnVar);
void parse_queued_messages(void);
void vungetc(Unt c);
int fix_input_buffer(Byte *buf, int len);
int input_available(void);
void may_add_last_used_map_to_redobuff(void);
int do_cmdkey_command(Unt key, Unt flags);
void reset_last_used_map(MapBlock *mp);
CS inputInitCharLens(void);
int mb_get_class(CS p);
int inpGetClassForBook(CS p, Book *book);
int utf_uint2cells(Unt c);
int mb_char2cells(int c);
int mb_ptr2cells(Byte *p);
int mb_ptr2cells_len(Byte *p, int size);
int mb_string2cells(Byte *p, int len);
int mb_off2cells(unsigned off, unsigned max_off);
Unt mb_ptr2char(Byte const *p);
Unt inpAdvanceMultibyte(Byte **pp);
Unt mb_cptr2char_adv(CS *pp);
int utf_composinglike(CS p1, CS p2);
int utfc_ptr2char(CS p, int *pcc);
int utfc_ptr2char_len(CS p, int *pcc, int maxlen);
int utfc_char2bytes(int off, CS buf);
Unt utf_ptr2len(CS p);
Unt utf_byte2len(int b);
Unt utf_byte2len_zero(int b);
Unt utf_ptr2len_len(Byte const *p, int size);
Unt utfCharLen(CS p);
Unt utfCharLen_len(Byte const *p, int size);
Unt mb_char2len(Unt c);
int mb_char2bytes(Unt c, Byte *buf);
int utf_iscomposing_uint(Unt c);
Boole utf_iscomposing(Unt c);
int utf_printable(int c);
int utf_class(int c);
int utf_class_buf(int c, Book *book);
int utf_ambiguous_width(int c);
Unt utf_fold(Unt a);
Unt utf_toupper(Unt a);
Boole utf_islower(Unt a);
Unt utf_tolower(Unt a);
Boole utf_isupper(Unt a);
int caseInsensitiveCompareNChars2(CS s1, CS s2, Unt n1, Unt n2);
int caseInsensitiveCompareNChars(CS s1, CS s2, Unt nn);
void show_utf8(void);
int mb_head_off(CS base, CS p);
int utf_eat_space(int cc);
Boole utf_allow_break_before(Unt cc);
int utf_allow_break(Unt cc, Unt ncc);
void mb_copy_char(Byte **fp, Byte **tp);
int mb_off_next(CS base, CS p);
int mb_tail_off(CS base, CS p);
void utf_find_illegal(void);
int utf_valid_string(CS s, CS end);
void mb_adjust_cursor(void);
void mb_adjustpos(Book *book, Pos *lp);
CS mb_prevptr(CS line, CS p);
int mb_charlen(Byte *str);
int mb_charlen_len(CS str, int len);
CS mb_unescape(Byte **pp);
int mb_lefthalve(int row, int col);
Unt mb_fix_col(Unt col, Unt row);
void f_charclass(Var *argvars, Var *returnVar);
int do_mouse(Operator *oper, Unt c, Unt dir, long count, int fixindent);
void ins_mouse(int c);
void ins_mousescroll(int dir);
Boole is_mouse_key(Unt c);
Unt get_mouse_button(Unt code, Boole *is_click, Boole *is_drag);
void set_mouse_termcode(int n, Byte *s);
void del_mouse_termcode(int n);
void setmouse(void);
void mouseResetDragPortal(void);
int jump_to_mouse(int flags, int *inclusive, int which_button);
void nv_mousescroll(ActionArg *cap);
void nv_mouse(ActionArg *cap);
void reset_held_button(void);
int check_termcode_mouse(CS key_name, Unt *modifiers);
int mouse_comp_pos(Portal *port, int *rowp, int *colp, LineNr *lnump, int *plines_cache);
Portal *mouseFindPortal(int *rowp, int *colp, MouseFindKind popup);
int vcol2col(Portal *po, LineNr lnum, int vcol, ColNr *coladdp);
void f_getmousepos(Var *argvars, Var *returnVar);
void mch_setmouse(Boole on);
void mch_bevalterm_changed(void);
/* eegl: set ft=c : */
