/* src/juggle.c */
void change_warning(int col);
void changed(void);
void changed_internal(void);
int trim_to_int(Long x);
void f_listener_add(Var *argvars, Var *returnVar);
void f_listener_flush(Var *argvars, Var *returnVar);
void f_listener_remove(Var *argvars, Var *returnVar);
void may_invoke_listeners(Book *book, LineNr lnum, LineNr lnume, int added);
void invoke_listeners(Book *book);
void remove_listeners(Book *book);
void changed_bytes(LineNr lnum, ColNr col);
void inserted_bytes(LineNr lnum, ColNr col, int added);
void appended_lines(LineNr lnum, long count);
void appended_lines_mark(LineNr lnum, long count);
void deleted_lines(LineNr lnum, long count);
void deleted_lines_mark(LineNr lnum, long count);
void changed_lines_buf(Book *book, LineNr lnum, LineNr lnume, long xtra);
void changed_lines(LineNr lnum, ColNr col, LineNr lnume, long xtra);
void unchanged(Book *book, int always_inc_changedtick);
void ins_bytes(CS p);
void ins_bytes_len(CS p, int len);
void insertChar(Unt c);
void replaceChar(Unt c);
void opInsertCharBytes(CS targetLine, int charlen, Boole replace);
void ins_str(CS s, Unt slen);
int del_char(Boole fixpos);
int del_chars(long count, Boole fixpos);
int del_bytes(long count, Boole fixpos_arg, int use_delcombine);
int insertLine(int dir);
int get_leader_len(CS line, Byte **flags, int backward, int include_space);
int openLine(Unt flags, int second_line_indent);
int truncate_line(int fixpos);
void del_lines(long nlines, int undo);
Unt get_op_type(Unt char1, Unt char2);
int op_is_change(int op);
int get_op_char(int optype);
int get_extra_op_char(int optype);
void op_shift(Operator *oper, int curs_top, int amount);
void shift_line(int left, int round, int amount, Boole call_changed_bytes);
Unt gchar_pos(Pos *pos);
Unt gchar_cursor(void);
int op_delete(Operator *oper);
Boole swapchar(Unt opTy, Pos *pos);
void op_insert(Operator *oper, long count1);
int op_change(Operator *oper);
void adjust_cursor_eol(void);
CS skip_comment(Byte *line, int process, int include_space, int *is_comment);
int jugJoinLinesUnderCursor(long count, int insert_space, int save_undo, int use_formatoptions, int setmark);
void block_prep(Operator *oper, BlockDef *bdp, LineNr lnum, Boole is_del);
void jugCharwiseBlockPrep(Pos start, Pos end, BlockDef *bdp, LineNr lnum, int inclusive);
void op_addsub(Operator *oper, LineNr prenum1, int g_cmd);
void clear_oparg(Operator *oper);
void cursor_pos_info(Bag *dict);
CS did_set_operatorfunc(OptionChange *cha);
void opsFreeOperatorFnOption(void);
int set_ref_in_opfunc(int copyID);
void visualOperator(ActionArg *cap, int old_col, int clipbYank);
void beep_flush(void);
Tyme eeTime(void);
CS get_ctime(Tyme thetime, int add_newline);
void f_localtime(Var *argvars, Var *returnVar);
void f_reltime(Var *argvars, Var *returnVar);
void f_reltimefloat(Var *argvars, Var *returnVar);
void f_reltimestr(Var *argvars, Var *returnVar);
void f_strftime(Var *argvars, Var *returnVar);
void f_strptime(Var *argvars, Var *returnVar);
long proftime_time_left(ProfTime *due, ProfTime *now);
Timer *create_timer(long msec, int repeat);
void timer_start(Timer *timer);
long check_due_timer(void);
void stop_timer(Timer *timer);
int set_ref_in_timer(int copyID);
int timer_valid(Timer *timer);
void timer_free_all(void);
void f_timer_info(Var *argvars, Var *returnVar);
void f_timer_pause(Var *argvars, Var *returnVar);
void f_timer_start(Var *argvars, Var *returnVar);
void f_timer_stop(Var *argvars, Var *returnVar);
void f_timer_stopall(Var *argvars, Var *returnVar);
void time_push(void *tv_rel, void *tv_start);
void time_pop(void *tp);
void time_msg(CS mesg, void *tv_start);
Tyme get8ctime(FILE *fd);
int put_time(FILE *fd, Tyme the_time);
void time_to_bytes(Tyme the_time, CS buf);
void add_time(CS buf, Unt buflen, Tyme tt);
void profile_start(ProfTime *tm);
void profile_setlimit(long msec, ProfTime *tm);
int profile_passed_limit(ProfTime *tm);
void profile_end(ProfTime *tm);
void profile_sub(ProfTime *tm, ProfTime *tm2);
double profile_float(ProfTime *tm);
void profile_zero(ProfTime *tm);
CS profile_msg(ProfTime *tm);
void stop_timeout(void);
volatile sig_atomic_t *start_timeout(long msec);
void delete_timer(void);
int getviscol(void);
int coladvance_force(ColNr wcol);
int coladvance(ColNr wantcol);
int getvpos(Pos *pos, ColNr wantcol);
int inc_cursor(void);
int inc(Pos *lp);
int incl(Pos *lp);
int dec_cursor(void);
int dec(Pos *lp);
int decl(Pos *lp);
void check_pos(Book *book, Pos *pos);
long get_sw_value(Book *book);
long get_sw_value_indent(Book *book, int left);
long get_sw_value_col(Book *book, ColNr col, int left);
int get_indent(void);
int get_indent_lnum(LineNr lnum);
int get_indent_buf(Book *book, LineNr lnum);
int set_indent(int size, int flags);
int get_number_indent(LineNr lnum);
int getBreakindentForPort(Portal *po, CS line);
int inindent(int extra);
void op_reindent(Operator *oper, int (*how)(void));
int preprocs_left(void);
int may_do_si(void);
void ins_try_si(int c);
void opChangeIndent(int type, int amount, int round, Boole call_changed_bytes);
void c_retab(Invocation *eap);
int get_expr_indent(void);
int opsIsIndentationExpressionBased(void);
void fix_indent(void);
void f_indent(Var *argvars, Var *returnVar);
int is_pos_in_string(CS line, ColNr col);
Pos *find_start_comment(int ind_maxcomment);
void do_expr_indent(void);
/* eegl: set ft=c : */
