/* src/location.c */
int llInitFromFile(LocationStack *st, CS errorFName, CS errorformat, Boole newlist, CS title);
int qf_stack_get_bufnr(void);
void check_qfBusynessG(void);
void llInitStacksOnce(void);
LocationStack *getLocationStack(int ind);
void llJump(LocationStack *stack, Unt dir, int errornr, Boole forceit);
void c_list(Invocation *invo);
void c_llAge(Invocation *invo);
void qf_history(Invocation *invo);
void llAdjustEntries(LineNr line1, LineNr line2, long amount, long amount_after);
void llViewLocation(int split);
void c_cPortal(Invocation *invo);
void c_lClose(Invocation *invo);
void c_lOpen(Invocation *invo);
void c_lBottom(Invocation *invo);
LineNr llCurrentEntry(Portal *po);
CS setQuickfixtextfunc(OptionChange *cha);
int grepIsActuallyInternal(CommIndex id);
void c_elgrep(Invocation *invo);
void c_grep(Invocation *invo);
void initInProgressLl(void);
void c_make(Invocation *invo);
int llGetSize(Invocation *invo);
int llGetValidSize(Invocation *invo);
int llGetCurrIndex(Invocation *invo);
int llGetCurrValidIndex(Invocation *invo);
void c_lMove(Invocation *invo);
void c_lNext(Invocation *invo);
void c_lBelow(Invocation *invo);
void c_lFile(Invocation *invo);
void c_vimgrep(Invocation *invo);
int setLocationList(LocationStack *stack, List *newContent, LocListAction action, CS title, Bag *specific);
Boole llSetRef(int copyId);
void c_lbook(Invocation *invo);
CS cexpr_get_auname(CommIndex id);
int trigger_cexpr_autocmd(int id);
int cexpr_core(Invocation *invo, Var *tv);
void c_lExpr(Invocation *invo);
void c_helpgrep(Invocation *invo);
void free_quickfix(void);
void f_getloclist(Var *argvars, Var *returnVar);
void f_setloclist(Var *argvars, Var *returnVar);
