/* src/mark.c */
int setmark(int c);
int setmark_pos(int c, Pos *pos, int fnum);
void mark_forget_file(Portal *wp, int fnum);
void setpcmark(void);
void checkpcmark(void);
Pos *movemark(int count);
Pos *movechangelist(int count);
Pos *getmark_buf(Book *book, int c, int changefile);
Pos *getmark(int c, int changefile);
Pos *getmark_buf_fnum(Book *book, int c, int changefile, int *fnum);
Pos *getnextmark(Pos *startpos, int dir, int begin_line);
void fmarks_check_names(Book *book);
int check_mark(Pos *pos);
void clrallmarks(Book *book);
Byte *fm_getname(FileMark *fmark, int lead_len);
void c_marks(Invocation *invo);
void c_delmarks(Invocation *invo);
void c_jumps(Invocation *invo);
void c_clearjumps(Invocation *invo);
void c_changes(Invocation *invo);
void mark_adjust(LineNr line1, LineNr line2, long amount, long amount_after);
void mark_adjust_nofold(LineNr line1, LineNr line2, long amount, long amount_after);
void mark_col_adjust(LineNr lnum, ColNr mincol, long lnum_amount, long col_amount, int spaces_removed);
void cleanup_jumplist(Portal *wp, int loadfiles);
void copy_jumplist(Portal *from, Portal *to);
void free_jumplist(Portal *wp);
void set_last_cursor(Portal *port);
void free_all_marks(void);
FileMarkExt *get_namedfm(void);
void f_getmarklist(Var *argvars, Var *returnVar);
void init_signs(void);
int markGetSignDecorations(Portal *wp, LineNr lnum, SignHilite *signHilites);
LineNr buf_delsign(Book *buf, LineNr atlnum, int id, Byte *group);
int buf_findsign(Book *buf, int id, Byte *group);
int buf_findsign_id(Book *buf, LineNr lnum, Byte *groupname);
int buf_findsigntype_id(Book *buf, LineNr lnum, int typenr);
void buf_delete_signs(Book *buf, Byte *group);
void sign_mark_adjust(LineNr line1, LineNr line2, long amount, long amount_after);
int sign_define_by_name(Byte *name, Byte *linehl, Byte *textt, Byte *texthl, Byte *culhl, Byte *numhl, int prio);
int sign_exists_by_name(Byte *name);
int sign_undefine_by_name(Byte *name, Boole give_error);
int sign_place(int *sign_id, Byte *sign_group, Byte *sign_name, Book *buf, LineNr lnum, int prio);
void c_sign(Invocation *invo);
void markGetBookSigns(Book *book, List *l);
void free_signs(void);
Byte *get_sign_name(Expand *xp, int idx);
void set_context_in_sign_cmd(Expand *xp, CS arg);
void f_sign_define(Var *argvars, Var *returnVar);
void f_sign_getdefined(Var *argvars, Var *returnVar);
void f_sign_getplaced(Var *argvars, Var *returnVar);
void f_sign_jump(Var *argvars, Var *returnVar);
void f_sign_place(Var *argvars, Var *returnVar);
void f_sign_placelist(Var *argvars, Var *returnVar);
void f_sign_undefine(Var *argvars, Var *returnVar);
SignEntry *get_first_valid_sign(Portal *wp);
Boole isSigncolumnOn(Portal *wp);
void f_sign_unplace(Var *argvars, Var *returnVar);
void f_sign_unplacelist(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
