/* src/message.c */
CS msg_strtrunc(CS s, int force);
void trunc_string(Byte *s, Byte *builder, int room_in, int buflen);
void msg_start(void);
void msg_starthere(void);
void msg_putchar(Unt c);
void msgPutcharDeco(Unt c, char flags);
void msg_outnum(long n);
void msg_home_replace(Byte *fname);
void msg_home_replace_hl(Byte *fname);
int msg_outtrans(Byte *str);
int msgOuttransDeco(CS str, Byte flags);
int msgTranslatedSlice(Text slice);
CS msgOneChar(CS p, char flags);
int msgOuttransLenDeco(Text slice, char flags);
void msg_make(CS arg);
int msg_outtrans_special(CS strstart, int from, int maxlen);
CS str2special_save(Byte *str, int replace_spaces, int replace_lt);
CS str2special(Byte **sp, int replace_spaces, int replace_lt);
void str2specialbuf(Byte *sp, Byte *builder, int len);
void msg_prt_line(CS s, int list);
int msg(CS s);
int verb_msg(CS s);
int msgDeco(CS s, char flags);
int msgAndKeep(CS s, char flags, int keep);
void reset_last_sourcing(void);
CS msgTruncDeco(CS s, char flags);
CS msg_may_trunc(CS s);
void msg_source(char flags);
void ignore_error_for_testing(Byte *error);
int emsg(CS s);
void internalErrMsg(CS s);
void internal_error(CS where);
void internal_error_no_abort(CS where);
void emsg_invreg(int name);
void emsg_namelen(CS msg, CS name, int len);
int delete_first_msg(void);
int messagesopt_changed(CS new);
void c_messages(Invocation *invo);
void wait_return(Boole redraw);
void set_keep_msg(Byte *s, char flags);
void msgmore(long n);
void set_keep_msg_from_hist(void);
int do_dialog(int type, Byte *title, Byte *message, Byte *buttons, int dfltbutton, Byte *textfield, int ex_cmd);
int eeDialog_yesno(int type, Byte *title, Byte *message, int dflt);
int eeDialog_yesnocancel(int type, Byte *title, Byte *message, int dflt);
int eeDialog_yesnoallcancel(int type, Byte *title, Byte *message, int dflt);
void msg_puts(CS s);
void msg_puts_title(CS s);
void outputShortenedToALine(Text slice, char flags);
void msgPutsDeco(CS s, char flags);
int message_filtered(Byte *msg);
int msg_use_printf(void);
void mch_errmsg(CS errMsg);
void mch_msg(CS str);
void repeat_message(void);
void msg_clr_eos(void);
void msg_clr_eos_force(void);
void msgClearCommline(void);
int msg_end(void);
void msg_check(void);
int redirecting(void);
void verbose_enter(void);
void verbose_leave(void);
void verbose_enter_scroll(void);
void verbose_leave_scroll(void);
void verbose_stop(void);
int verbose_open(void);
void give_warning(Byte *message, int hl);
void give_warning_with_source(Byte *message, int hl, int with_source);
void give_warning2(Byte *message, Byte *a1, int hl);
void msg_advance(int col);
void msg_warn_missing_clipboard(void);
void may_clear_sb_text(void);
void sb_text_start_cmdline(void);
void sb_text_restart_cmdline(void);
void sb_text_end_cmdline(void);
void clear_sb_text(int all);
void show_sb_text(void);
void msg_sb_eol(void);
/* eegl: set ft=c : */
