int highest_patch(void);
void c_version(Invocation* invo);
void maybe_intro_message(void);
void c_intro(Invocation* invo UNUSED);
int libMain(void);
void init0(void);
void init1(OUT MainParams* par);
int appMain(int argc, char** argv);
int is_not_a_term(void);
int is_not_a_term_or_gui(void);
void free_vbuf(void);
void may_trigger_safestate(Boole safe);
void state_no_longer_safe(CS reason);
Boole get_was_safe_state(void);
void may_trigger_safestateagain(void);
int work_pending(void);
void mainLoop(Boole inCommPort);
void exitEegl(int exitval);
void mainerr_arg_missing(CS str);
CS mainProgramVersion();
void __attribute__((noinline)) __bp();
