/* src/normal.c */
int findsent(int dir, long count);
int normFindNextParagraf(Boole *pincl, int dir, long count, int what, int both);
int startPS(LineNr lnum, int para, int both);
int fwd_word(long count, int bigword, int eol);
int bck_word(long count, int bigword, int stop);
int end_word(long count, int bigword, int stop, int empty);
int bckend_word(long count, int bigword, int eol);
int current_word(Operator *oper, long count, int include, int bigword);
int current_sent(Operator *oper, long count, int include);
int current_tagblock(Operator *oper, long count_arg, int include);
int current_par(Operator *oper, long count, int include, int type);
int current_quote(Operator *oper, long count, int include, int quotechar);
int virtual_active(void);
Bag *get_v_event(SaveVEvent *sve);
void restore_v_event(Bag *v_event, SaveVEvent *sve);
void get_mode(CS buf);
void may_trigger_modechanged(void);
int get_real_state(void);
int check_text_or_curbuf_locked(Operator *oper);
void normalAction(Operator *oper, Boole toplevel);
void check_visual_highlight(void);
void end_visual_mode(void);
void end_visual_mode_keep_button(void);
void reset_VIsual_and_resel(void);
void reset_VIsual(void);
void restore_visual_mode(void);
int find_ident_under_cursor(Byte **text, int find_type);
int find_ident_at_pos(Portal *wp, LineNr lnum, ColNr startcol, Byte **text, int *textcol, int find_type);
void prep_redo(int regname, long num, int cmd1, int cmd2, int cmd3, int cmd4, int cmd5);
void prep_redo_num2(int regname, long num1, int cmd1, int cmd2, long num2, int cmd3, int cmd4, int cmd5);
void clearop(Operator *oper);
void clearopbeep(Operator *oper);
void may_clear_cmdline(void);
void clear_showcmd(void);
int add_to_showcmd(Unt c);
void add_to_showcmd_c(Unt c);
void push_showcmd(void);
void pop_showcmd(void);
void normPostProcessScrollbind(int check);
void check_scrollbind(LineNr topline_diff, long leftcol_diff);
int find_decl(CS ptr, int len, int locally, int thisblock, Unt flags_arg);
int get_visual_text(ActionArg *aArg, CS *pp, int *lenp);
void start_selection(void);
int unadjust_for_sel_inner(Pos *pp);
void set_cursor_for_append_to_line(void);
int nv_screengo(Operator *oper, Unt dir, long dist);
void nv_scroll_line(ActionArg *aArg);
void do_nv_ident(int c1, int c2);
void nv_g_home_m_cmd(ActionArg *aArg);
void a_linewiseOperator(ActionArg *aArg);
int adjust_plines_for_skipcol(Portal *po);
int sms_marker_overlap(Portal *po, int extra2);
void update_topline_redraw(void);
void update_topline(void);
void update_curswant(void);
void check_cursor_moved(Portal *po);
void didChangePortalSettingCurPor(void);
void didChangePortalSetting(Portal *po);
void didChangePortalSettingBuf(Book *book);
void didChangePortalSettingAll(void);
void set_topline(Portal *po, LineNr lnum);
void changed_cline_bef_curs(void);
void changed_cline_bef_curs_win(Portal *po);
void changed_line_abv_curs(void);
void changed_line_abv_curs_win(Portal *po);
void normInvalidateDisplayOfChangedBookLine(Book *book);
void validate_botline(void);
void validate_botline_win(Portal *po);
void invalidate_botline(void);
void invalidate_botline_win(Portal *po);
void approximate_botline_win(Portal *po);
int cursor_valid(void);
void validate_cursor(void);
void validate_virtcol(void);
void validate_virtcol_win(Portal *po);
void validate_cheight(void);
void validate_cursor_col(void);
int normalPortalColumnOffset(Portal *po);
int curPor_col_off(void);
void curs_columns(int may_scroll);
void textpos2screenpos(Portal *po, Pos *pos, int *rowp, int *scolp, int *ccolp, int *ecolp);
void f_screenpos(Var *argvars, Var *returnVar);
void f_virtcol2col(Var *argvars, Var *returnVar);
void scroll_redraw(int up, long count);
void scrolldown(long line_count, int byfold);
void scrollup(long line_count, int byfold);
void adjust_skipcol(void);
void check_topfill(Portal *po, int down);
void scrolldown_clamp(void);
void scrollup_clamp(void);
void set_empty_rows(Portal *po, int used);
void scroll_cursor_bot(int min_scroll, int set_topbot);
void scroll_cursor_halfway(int atend, int prefer_above);
void cursor_correct(void);
int pagescroll(int dir, long count, int half);
void do_check_cursorbind(void);
MapBlock *getMappingTableList(int state, int c);
MapBlock *getBufMappingTableList(int state, int c);
int isMappingTableValid(void);
int do_map(int maptype, CS arg, Unt mode, int abbrev);
void mapClearAllMappingsInMode(Book *book, int modeClearFrom, Boole localOnly, Boole abbr);
int mode_str2flags(CS modechars);
int map_to_exists(CS str, CS modechars, int abbr);
Boole map_to_exists_mode(CS rhs, int mode, int abbr);
CS set_context_in_map_cmd(Expand *xp, CS cmd, CS arg, Boole forceit, Boole isabbrev, Boole isunmap, CommIndex id);
int expandMappings(CS pat, RegMatch *regmatch, ExpandMatch *matches);
Boole check_abbr(Unt c, CS ptr, int col, int mincol);
CS eval_map_expr(MapBlock *mp, int c);
CS copyStr_escape_csi(CS p);
void eeUnescapeCsi(CS p);
int makemap(FILE *fd, Book *book);
int put_escstr(FILE *fd, CS strstart, int what);
void check_map_keycodes(void);
CS norCheckMapping(CS keys, int mode, int exact, int ign_mod, int abbr, MapBlock **mp_ptr, int *local_ptr);
void f_hasmapto(Var *argvars, Var *returnVar);
void f_maplist(Var *argvars, Var *returnVar);
void f_maparg(Var *argvars, Var *returnVar);
void f_mapcheck(Var *argvars, Var *returnVar);
void f_mapset(Var *argvars, Var *returnVar);
void add_map(CS map, int mode, int nore);
int langmap_adjust_mb(int c);
void langmap_init(void);
CS setLangmap(OptionChange *args);
void c_abbreviate(Invocation *invo);
void c_map(Invocation *invo);
void c_unmap(Invocation *invo);
void c_mapclear(Invocation *invo);
void c_abclear(Invocation *invo);
void copyFoldingState(Portal *wp_from, Portal *wp_to);
int hasAnyFolding(Portal *po);
int getFolds(LineNr lnum, LineNr *firstp, LineNr *lastp);
int getFoldsPortal(Portal *po, LineNr lnum, LineNr *firstp, LineNr *lastp, int cache, FoldInfo *infop);
int lineFolded(Portal *po, LineNr lnum);
long foldedCount(Portal *po, LineNr lnum, FoldInfo *infop);
void closeFold(LineNr lnum, long count);
void opFoldRange(LineNr first, LineNr last, int opening, int recurse, int had_visual);
void openFold(LineNr lnum, long count);
void foldOpenCursor(void);
void newFoldLevel(void);
void foldCheckClose(void);
int foldManualAllowed(int create);
void foldCreate(LineNr start, LineNr end);
void deleteFold(LineNr start, LineNr end, int recursive, int had_visual);
void clearFolding(Portal *po);
void foldUpdate(Portal *wp, LineNr top, LineNr bot);
void foldUpdateAll(Portal *po);
void normInitFoldForPortal(Portal *newPort);
int find_wl_entry(Portal *po, LineNr lnum);
void foldAdjustVisual(void);
void cloneFoldArrayList(ArrayList *from, ArrayList *to);
void deleteFoldRecurse(ArrayList *gap);
void foldMarkAdjust(Portal *wp, LineNr line1, LineNr line2, long amount, long amount_after);
CS get_foldtext(Portal *wp, LineNr lnum, LineNr lnume, FoldInfo *foldinfo, CS buffer);
void foldMoveRange(ArrayList *gap, LineNr line1, LineNr line2, LineNr dest);
int put_folds(FILE *fd, Portal *wp);
void f_foldclosed(Var *argvars, Var *returnVar);
void f_foldclosedend(Var *argvars, Var *returnVar);
void f_foldlevel(Var *argvars, Var *returnVar);
void f_foldtext(Var *argvars, Var *returnVar);
void f_foldtextresult(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
