/* src/option.c */
void optSetStringDefault(CS name, CS val);
void set_number_default(CS name, long val);
void optFreeAllOptions(void);
void optionInit1(void);
CS optSetByName(CS name, OptionValue newVal, SetScope setScope);
Unt stringToChar(CS arg, Boole multi_byte);
ScriptPos *optGetScriptPos(CS name);
OptionValue optGetValue(Unt *flagsp, CS name, int scope);
Boole optIsFnOption(Unt flags);
void optSetFromVar(CS varname, Var *varp);
int optExpandForSet(Expand *xp, RegMatch *regmatch, ExpandMatch *matches);
Boole optWasSet(CS name);
int makefoldset(FILE *fd);
CS optSetBinary(OptionChange *cha);
CS setModifiable(OptionChange *cha);
void optChangeAndReportError(CS name, OptionValue newValue, SetScope setScope);
void portCopyOptions(Portal *to, Portal *from);
void afterCopyPortOpt(Portal *po);
void copyPortOpt(PortLocal *t, PortLocal *s);
void optClearPortOptions(PortLocal *t);
void optInitExpandContextForSet(Expand *xp, CS arg, SetScope setScope);
int optExpandOldOption(ExpandMatch *matches);
Boole shortmess(int x);
int reset_optWasSet(CS name);
long get_sidescrolloff_value(void);
int optSetCallback(Callback *cb, CS new);
CS setShowTabpanel(OptionChange *cha);
void initPortalOptions(PortLocal *o);
void updateStringRef(OptionChange *cha);
void optMakeStringOptionsNonnull(void);
void optionInit0(void);
int writeOptionsAsSet(FILE *fd);
void optSetLocalOptionsToDefault(Portal *wp, Boole doBook);
void c_get(Invocation *invo);
void c_set(Invocation *invo);
Bag *getBookOrPortOptions(Boole bufopt);
void optsCopyToBook(Book *book, Unt flags);
int optExpandOption(Expand *xp, RegMatch *regmatch, CS fuzzystr, Boole canFuzzy, ExpandMatch *matches);
void optInitScriptPostprocess(CS fname, CS envname);
Boole optImmutableMode(void);
void optCheckBookOptions(BookLocal *t);
void free_string_option(CS p);
void clearStringOption(Byte **pp);
void optChangeStringOptionDirect(CS name, CS val, SetScope scope, ScriptId set_sid);
void optSetStringOptionDirectInPort(Portal *po, CS name, CS val, Unt optFlags, int set_sid);
void optSetStringOptionDirectInBook(Book *book, CS name, CS val, Unt optFlags, int set_sid);
void save_clear_shm_value(void);
void restore_shm_value(void);
CS get_mess_lang(void);
void set_lang_var(void);
void init_locale(void);
void c_language(Invocation *invo);
void free_locales(void);
CS get_lang_arg(Expand *xp, int idx);
CS get_locales(Expand *xp, int idx);
/* eegl: set ft=c : */
