/* src/option.c */
void _incRefCount(void *a);
void _decRefCount(void *a);
Unt _getRefCount(void *a);
void optSetStringDefault(CS name, CS val);
void optFreeAllOptions(void);
void optInit1(void);
CS optSetByName(CS name, OptionValue newVal, SetScope setScope);
Unt stringToChar(CS arg, Boole multi_byte);
ScriptPos *optGetScriptPos(CS name);
OptionValue optGetValue(Unt *flagsp, CS name, int scope);
Boole optIsFnOption(Unt flags);
void optSetFromVar(CS varname, Var *varp);
int optExpandForSet(Expand *xp, RegMatch *regmatch, ExpandMatch *matches);
Boole optWasSet(CS name);
int makefoldset(FILE *fd);
CS optSetBinary(OptionChange *cha);
CS setModifiable(OptionChange *cha);
void optChangeAndReportError(CS name, OptionValue newValue, SetScope setScope);
void afterCopyPortOpt(Portal *po);
void copyPortOpt(PortalOptions *t, PortalOptions *s);
void optClearPortOptions(PortalOptions *t);
void optInitExpandContextForSet(Expand *xp, CS arg, SetScope setScope);
int optExpandOldOption(ExpandMatch *matches);
int reset_optWasSet(CS name);
long get_sidescrolloff_value(void);
int optSetCallback(Callback *cb, CS new);
CS setShowTabpanel(OptionChange *cha);
void initPortalOptions(PortalOptions *o);
void updateStringRef(OptionChange *cha);
void optInit0(void);
int writeOptionsAsSet(FILE *fd);
void optSetLocalOptionsToDefault(Portal *wp, Boole doBook);
void c_get(Invocation *invo);
void c_set(Invocation *invo);
Bag *getBookOrPortOptions(Boole bufopt);
void optCopyBetweenPortals(Portal *to, Portal *from);
void optCopyGlobalToPortal(Portal *to);
void optFreeBookCallbacks(Book *book);
void optsCopyToBook(Book *book, Unt flags);
int optExpandOption(Expand *xp, RegMatch *regmatch, CS fuzzystr, Boole canFuzzy, ExpandMatch *matches);
Boole optImmutableMode(void);
void optChangeStringOptionDirect(CS name, CS val, SetScope scope, ScriptId set_sid);
void optSetStringOptionDirectInPort(Portal *po, CS name, CS val, Unt optFlags, int set_sid);
void optSetStringOptionDirectInBook(Book *book, CS name, CS val, Unt optFlags, int set_sid);
CS get_mess_lang(void);
void set_lang_var(void);
void init_locale(void);
void c_language(Invocation *invo);
void free_locales(void);
CS get_lang_arg(Expand *xp, int idx);
CS get_locales(Expand *xp, int idx);
