/* src/portal.c */
void portalLayout_lock(void);
void portalLayout_unlock(void);
Boole portalLayout_locked(CommIndex cmd);
Boole portCheckCanSetCurBookDisabled(void);
Boole portCheckCanSetCurBookForceIt(Boole forceit);
Portal *prevPor_curPor(void);
Portal *switchBufGotoPortalIntoBuf(Book *book);
void doPortal(int nchar, long prenum, Unt xchar);
void getPortCommAddressType(CS arg, Invocation *invo);
int check_split_disallowed(Portal *po);
int splitPortal(int size, int flags);
int splitPortal_ins(int size, int flags, Portal *newPort, int dir, Frame *to_flatten);
int portalValidPopup(Portal *port);
int portalIsValid(Portal *port);
Portal *portFindById(int id);
int doesPortalExistInAnyTab(Portal *port);
int portCount(void);
int makePortals(int count, int vertical);
int splitPortalmove(Portal *po, int size, Unt flags);
void portMoveAfter(Portal *port0, Portal *port1);
void portEqualizeHeight(Portal *next_curPor, int current, Unt dir);
void leavingPortal(Portal *port);
void enteringPortal(Portal *port);
void curPor_init(void);
void closePortalsInto(Book *book, Boole keep_curPor);
int lastPortal(void);
int onePortal(void);
Unt closePortal(Portal *port, int free_buf);
void trigger_tabclosedpre(Tab *t, int directly);
void portSnapshotScrollSizes(void);
void may_make_initial_scroll_size_snapshot(void);
void may_trigger_win_scrolled_resized(void);
void closePortal_othertab(Portal *port, int free_buf, Tab *t);
void portFreeAll(void);
Portal *portRemoveFrame(Portal *port, Unt *dirp, Tab *t, Frame **unflat_altfr);
void close_others(Boole message);
void unloadTab(Tab *t);
void loadTab(Tab *t);
int portAllocFirst(void);
Portal *portAllocPopup(void);
void initPopupPortal(Portal *po, Book *book);
void portalInitSize(void);
void freeTab(Tab *t);
int portNewTab(int after);
int make_tabpages(int maxcount);
int isTabValid(Tab *tpc);
int areTabAndPortalValid(Tab *tpc);
void closeTab(Tab *tab);
Tab *getTab(int n);
Unt indexOfTab(Tab *needle);
void gotoTabById(int n);
void gotoTab(Tab *t, int trigger_enter_autocmds, int trigger_leave_autocmds);
int goto_tabpage_lastused(void);
void goto_tab_port(Tab *t, Portal *po);
void moveTab(Unt nr);
void gotoPortal(Portal *po);
Portal *portHorizNeighbor(Tab *t, Portal *po, int left, long count);
void enterPortal(Portal *po, int undo_sync);
void portFixCurrentDir(void);
Portal *portTryFindOpenBook(Book *book);
Portal *buf_jump_open_tab(Book *book);
int portUnlisted(Portal *po);
void portFreePopup(Portal *port);
void removePortal(Portal *port, Tab *t);
void allocLinesPortal(Portal *po);
void freePortalLsizes(Portal *po);
void shell_new_rows(void);
void shell_new_columns(void);
void portalSaveSizes(ArrayList *gap);
void portRestoreSize(ArrayList *gap);
void computePosPortal(void);
void portEnsureSize(void);
void portSetHeight(int height, Portal *port);
void portSetWidth(int width, Portal *po);
void portDragStatusLine(Portal *dragwin, int offset);
void portDragVsepLine(Portal *dragwin, int offset);
void set_fraction(Portal *po);
void check_cursor_lnum(void);
void check_cursor_col(void);
int set_leftcol(ColNr leftcol);
void check_cursor_col_win(Portal *po);
void check_cursor(void);
void check_visual_pos(void);
void adjust_cursor_col(void);
int plines(LineNr lnum);
int plines_win(Portal *wp, LineNr lnum, int limit_winheight);
int plines_nofill(LineNr lnum);
int plines_win_nofill(Portal *wp, LineNr lnum, int limit_winheight);
int plines_win_nofold(Portal *wp, LineNr lnum);
int plines_m_win(Portal *wp, LineNr first, LineNr last, int max);
void scroll_to_fraction(Portal *po, int prevHeight);
void portComputeScroll(Portal *po);
void command_height(void);
void last_status(int morePorts);
int last_stl_height(int morePorts);
int min_rows(void);
Unt minRowsForAllTabs(void);
Boole onlyOnePortal(void);
void check_lnums(int do_curPor);
void check_lnums_nested(int do_curPor);
void reset_lnums(void);
int make_snapshot(int idx);
void restore_snapshot(int idx, int close_curPor);
int getLastPortId(void);
int portalLocked(Portal *po);
Portal *getPortalById(int id);
Portal *getPortAndTab(int id, Tab **tpp);
Portal *portFindByNr(Var *vp, Tab *t);
Portal *portFindByNrOrId(Var *vp);
Portal *find_tabwin(Var *wvp, Var *tvp, Tab **ptp);
void f_gettabinfo(Var *argvars, Var *returnVar);
void f_getwininfo(Var *argvars, Var *returnVar);
void f_getwinpos(Var *argvars, Var *returnVar);
void f_getwinposx(Var *argvars, Var *returnVar);
void f_getwinposy(Var *argvars, Var *returnVar);
void f_tabpagenr(Var *argvars, Var *returnVar);
void f_tabpagewinnr(Var *argvars, Var *returnVar);
void f_win_execute(Var *argvars, Var *returnVar);
void f_win_findbuf(Var *argvars, Var *returnVar);
void f_win_getid(Var *argvars, Var *returnVar);
void f_gotoPortalid(Var *argvars, Var *returnVar);
void f_win_id2tabwin(Var *argvars, Var *returnVar);
void f_win_id2win(Var *argvars, Var *returnVar);
void f_win_move_separator(Var *argvars, Var *returnVar);
void f_win_move_statusline(Var *argvars, Var *returnVar);
void f_win_screenpos(Var *argvars, Var *returnVar);
void f_splitPortalmove(Var *argvars, Var *returnVar);
void f_win_gettype(Var *argvars, Var *returnVar);
void f_getcmdwintype(Var *argvars, Var *returnVar);
void f_winbufnr(Var *argvars, Var *returnVar);
void f_wincol(Var *argvars, Var *returnVar);
void f_winheight(Var *argvars, Var *returnVar);
void f_winlayout(Var *argvars, Var *returnVar);
void f_winline(Var *argvars, Var *returnVar);
void f_winnr(Var *argvars, Var *returnVar);
void f_winrestcmd(Var *argvars, Var *returnVar);
void f_winrestview(Var *argvars, Var *returnVar);
void f_winsaveview(Var *argvars, Var *returnVar);
void f_winwidth(Var *argvars, Var *returnVar);
int portSwitch(SwitchPort *switchPort, Portal *port, Tab *t, int no_display);
int portSwitchNoblock(SwitchPort *switchPort, Portal *port, Tab *t, int no_display);
void portRestore(SwitchPort *switchPort, int no_display);
void portRestoreNoblock(SwitchPort *switchPort, int no_display);
int popup_on_border(Portal *po, int row, int col);
int popup_close_if_on_X(Portal *po, int row, int col);
void popup_start_drag(Portal *po, int row, int col);
void popup_drag(Portal *po);
void popup_set_firstline(Portal *po);
int popup_is_in_scrollbar(Portal *po, int row, int col);
void popup_handle_scrollbar_click(Portal *po, int row, int col);
int popup_top_extra(Portal *po);
int popup_left_extra(Portal *po);
int popup_height(Portal *po);
int popup_width(Portal *po);
int popup_extra_width(Portal *po);
int parse_previewpopup(Portal *po);
int parse_completepopup(Portal *po);
void popup_set_wantpos_cursor(Portal *po, int width, Bag *d);
void popup_set_wantpos_rowcol(Portal *po, int row, int col);
void popup_redraw_all(void);
Portal *createPopup(Var *argvars, Var *returnVar, PopupKind kind);
void f_popup_clear(Var *argvars, Var *returnVar);
void f_createPopup(Var *argvars, Var *returnVar);
void f_popup_atcursor(Var *argvars, Var *returnVar);
void f_popup_beval(Var *argvars, Var *returnVar);
void popup_close_with_retval(Portal *po, int retval);
void popup_close_for_mouse_click(Portal *po);
void popup_handle_mouse_moved(void);
void f_popup_filter_menu(Var *argvars, Var *returnVar);
void f_popup_filter_yesno(Var *argvars, Var *returnVar);
void f_popup_dialog(Var *argvars, Var *returnVar);
void f_popup_menu(Var *argvars, Var *returnVar);
void f_popup_notification(Var *argvars, Var *returnVar);
void f_popup_close(Var *argvars, Var *returnVar);
void popup_hide(Portal *po);
void f_popup_hide(Var *argvars, Var *returnVar);
void popup_show(Portal *po);
void f_popup_show(Var *argvars, Var *returnVar);
void f_popup_settext(Var *argvars, Var *returnVar);
void f_popup_setbuf(Var *argvars, Var *returnVar);
Boole portErrorIfPopup(Boole also_with_term);
int popup_close(int id, int force);
int popupCloseTab(Tab *tab, int id, int force);
void close_all_popups(int force);
void f_popup_move(Var *argvars, Var *returnVar);
void f_popup_setoptions(Var *argvars, Var *returnVar);
void f_popup_getpos(Var *argvars, Var *returnVar);
void f_popup_list(Var *argvars, Var *returnVar);
void f_popup_locate(Var *argvars, Var *returnVar);
void f_popup_getoptions(Var *argvars, Var *returnVar);
Boole portErrorIfTermPopup(void);
void popup_reset_handled(int handled_flag);
Portal *find_next_popup(int lowest, int handled_flag);
int popup_do_filter(Unt c);
int popup_no_mapping(void);
void popup_check_cursor_pos(void);
void may_update_popup_mask(int type);
void may_update_popup_position(void);
void update_popups(void (*win_update)(Portal *po));
int set_ref_in_popups(int copyID);
int popup_is_popup(Portal *po);
Portal *popupFindPreviewPortal(void);
Portal *popupFindInfoPortal(void);
void f_popup_findecho(Var *argvars, Var *returnVar);
void f_popup_findinfo(Var *argvars, Var *returnVar);
void f_popup_findpreview(Var *argvars, Var *returnVar);
int portalCreatePreviewPortal(int info);
void popup_close_preview(void);
void popup_close_info(void);
int popup_overlaps_cmdline(void);
Portal *popup_get_messagePort(void);
void popup_show_messagePort(void);
int popup_message_win_visible(void);
void popup_hide_messagePort(void);
void start_echowindow(int time_sec);
void end_echowindow(void);
void setPopupTitle(Portal *po);
void popup_update_preview_title(void);
void showNotification(CS text);
Boole canStartDrag(Portal *po, int row, int col);
Boole isInfoPopup(Portal *po);
void pum_display(PopupItem *array, Unt size, int selected);
void pum_callUpdateScreen(void);
int pum_under_menu(int row, int col, int only_redrawing);
void pum_redraw(void);
void pum_undisplay(void);
void pum_clear(void);
int pum_visible(void);
int pum_redraw_in_same_position(void);
void pum_may_redraw(void);
int pum_get_height(void);
void pum_set_event_info(Bag *bag);
Unt balloonSplitMessage(CS mesg, PopupItem **array);
void ui_remove_balloon(void);
void ui_post_balloon(CS mesg, List *list);
void ui_may_remove_balloon(void);
int find_word_under_cursor(int mouserow, int mousecol, int getword, int flags, Portal **winp, LineNr *lnump, Byte **textp, int *colp, int *startcolp);
int get_beval_info(BalloonEval *beval, int getword, Portal **winp, LineNr *lnump, Byte **textp, int *colp);
void post_balloon(BalloonEval *beval, CS mesg, List *list);
void general_beval_cb(BalloonEval *beval, int state);
/* eegl: set ft=c : */
