/* src/script.c */
void estack_init(void);
Estack *estack_push(CallFrame type, CS name, long lnum);
Estack *estack_push_ufunc(UserFunc *ufunc, long lnum);
int estack_top_is_ufunc(UserFunc *ufunc, long lnum);
Estack *estack_pop(void);
CS estack_sfile(EstackArg which);
List *stacktrace_create(void);
void f_getstacktrace(Var *argvars, Var *returnVar);
void c_runtime(Invocation *invo);
void set_context_in_runtime_cmd(Expand *xp, CS arg);
int find_script_by_name(Byte *name);
int get_new_scriptitem_for_fname(int *error, Byte *fname);
void check_script_symlink(int sid);
int doInPath(CS path, CS prefix, CS name, int flags, void (*callback)(Byte *fname, void *ck), void *cookie);
int do_in_runtimepath(Byte *name, int flags, void (*callback)(Byte *fname, void *ck), void *cookie);
int source_runtime(Byte *name, int flags);
int source_in_path(CS path, CS name, int flags, int *ret_sid);
int find_script_in_rtp(Byte *name);
void load_start_packages(void);
void c_packloadall(Invocation *invo);
void c_packadd(Invocation *invo);
void remove_duplicates(ExpandMatch *matches);
int expandRuntimeDir(CS pat, Unt flags, CS *dirnames, ExpandMatch *matches);
void c_source(Invocation *invo);
void c_options(Invocation *invo);
LineNr *source_breakpoint(void *cookie);
int *source_dbg_tick(void *cookie);
int source_level(void *cookie);
Byte *source_nextline(void *cookie);
int may_load_script(int sid, int *loaded);
int scriptRunFile(CS fname, int *retSid);
void c_scriptnames(Invocation *invo);
Byte *get_scriptname(ScriptId id);
void free_scriptnames(void);
void free_autoload_scriptnames(void);
LineNr get_sourced_lnum(LineGetter fgetline, void *cookie);
void f_getscriptinfo(Var *argvars, Var *returnVar);
CS getsourceline(Unt c, void *cookie, int indent, GetlineAlgo options);
int sourcing_a_script(Invocation *invo);
void c_finish(Invocation *invo);
void do_finish(Invocation *invo, int reanimate);
int sourceFileIsFinished(LineGetter fgetline, void *cookie);
CS get_autoload_prefix(ScriptItem *si);
Byte *may_prefix_autoload(Byte *name);
CS autoload_name(Byte *name);
int scriautoload(CS name, int reload);
TypeSpec *alloc_type(TypeSpec *type);
void free_type(TypeSpec *type);
CS toNameEnd(Byte *arg, int use_namespace);
Byte *to_name_const_end(Byte *arg);
int assignment_len(Byte *p, int *heredoc);
void import_check_sourced_sid(int *sid);
Svar *find_typval_in_script(Var *dest, ScriptId sid, int must_find);
int has_watchexpr(void);
void do_debug(Byte *comm);
void c_debug(Invocation *invo);
void dbg_check_breakpoint(Invocation *invo);
int dbg_check_skipped(Invocation *invo);
void c_breakadd(Invocation *invo);
void c_debuggreedy(Invocation *invo);
int debug_has_expr_breakpoint(void);
void c_breakdel(Invocation *invo);
void c_breaklist(Invocation *invo);
LineNr dbg_find_breakpoint(int file, Byte *fname, LineNr after);
void dbg_breakpoint(Byte *name, LineNr lnum);
Boole scrIsCommlineFuzzyCompletable(CS fuzzystr);
void expandEscape(Expand *xp, CS str, int options, ExpandMatch *files);
void cmdline_pum_display(void);
int cmdline_pum_active(void);
void cmdline_pum_remove(CommlineInfo *cclp, int defer_redraw);
void cmdline_pum_cleanup(CommlineInfo *cclp);
int cmdline_compl_startcol(void);
CS cmdline_compl_pattern(void);
int cmdline_compl_is_fuzzy(void);
CS expandWildcard(Expand *xp, CS str, CS orig, Unt options, int mode);
void expandInit(Expand *xp);
void scrExpandCleanup(Expand *xp);
void clear_commlineSaved(void);
int showmatches(Expand *xp, int wildmenu, int noselect);
CS addstar(Text fname, Unt context);
void set_expand_context(Expand *xp);
void setCompletionContextForCommand(Expand *xp, Text searchPattern, int col, Boole use_ccline);
int expandCommline(Expand *xp, CS str, int col, ExpandMatch *matches);
int expandFromContext(Expand *xp, CS pat, Unt options, ExpandMatch *matches);
int expandGeneric(CS pat, Expand *xp, RegMatch *regmatch, CS (*fn)(Expand *, int), int escaped, ExpandMatch *matches);
int wildmenu_process_key(CommlineInfo *cclp, Unt key, Expand *xp);
void wildmenu_cleanup(CommlineInfo *cclp);
void f_getcompletion(Var *argvars, Var *returnVar);
void f_getcompletiontype(Var *argvars, Var *returnVar);
void f_cmdcomplete_info(Var *argvars, Var *returnVar);
int getHistLen(void);
HistoryEntry *get_histentry(int hist_type);
void set_histentry(int hist_type, HistoryEntry *entry);
int *get_hisidx(int hist_type);
int *get_hisnum(int hist_type);
int hist_char2type(int c);
CS get_history_arg(Expand *xp, int idx);
void init_history(void);
void clear_hist_entry(HistoryEntry *hisptr);
int in_history(int type, Byte *str, int move_to_front, int sep, int writing);
void add_to_history(int histype, Byte *new_entry, Unt new_entrylen, int in_map, int sep);
void f_histadd(Var *argvars, Var *returnVar);
void f_histdel(Var *argvars, Var *returnVar);
void f_histget(Var *argvars, Var *returnVar);
void f_histnr(Var *argvars, Var *returnVar);
void remove_key_from_history(void);
void c_history(Invocation *invo);
int parse_pattern_and_range(Pos *incsearch_start, Unt *searchDelim, int *skiplen, int *patlen);
void cmdline_init(void);
CS getCommline(Unt firstc, long count, int indent, GetlineAlgo do_concat);
Byte *getcmdline_prompt(Unt firstc, CS prompt, char deco, int context, CS completionFn);
int check_opt_wim(void);
int text_locked(void);
void text_locked_msg(void);
CS get_text_locked_msg(void);
int text_or_buf_locked(void);
int curBookLocked(void);
int allbuf_locked(void);
CS getexline(Unt c, void *cookie, int indent, GetlineAlgo options);
int cmdline_overstrike(void);
int cmdline_at_end(void);
ColNr cmdline_getvcol_cursor(void);
int reallocateCommBuf(int len);
void free_arshape_buf(void);
void putcmdline(int c, int shift);
void unputcmdline(void);
int put_on_cmdline(Byte *str, int len, int redraw);
void cmdline_paste_str(CS s, int literally);
void redrawCommline(void);
void redrawCommlineEx(int do_compute_cmdrow);
void redrawcmd(void);
void compute_cmdrow(void);
void cursorcmd(void);
void gotoCommline(int clr);
CS copyStr_fnameescape(CS fname, Unt what);
void escape_fname(Byte **pp);
void tilde_replace(CS orig_pat, ExpandMatch *files);
CommlineInfo *getCommlineInfo(void);
void f_getcmdcomplpat(Var *argvars, Var *returnVar);
void f_getcmdcompltype(Var *argvars, Var *returnVar);
void f_getCommline(Var *argvars, Var *returnVar);
void f_getcmdpos(Var *argvars, Var *returnVar);
void f_getcmdprompt(Var *argvars, Var *returnVar);
void f_getcmdscreenpos(Var *argvars, Var *returnVar);
void f_getcmdtype(Var *argvars, Var *returnVar);
void f_setcmdline(Var *argvars, Var *returnVar);
void f_setcmdpos(Var *argvars, Var *returnVar);
int get_cmdline_firstc(void);
int get_list_range(Byte **str, int *num1, int *num2);
int inCommPort(void);
CS script_get(Invocation *invo, Byte *comm);
void get_user_input(Var *argvars, Var *returnVar, int inputdialog, int secret);
void f_wildtrigger(Var *argvars, Var *returnVar);
CS find_ucmd(Invocation *invo, Byte *p, int *full, Expand *xp, Unt *context);
CS set_context_in_user_cmd(Expand *xp, CS arg_in);
CS set_context_in_user_cmdarg(CS comm, CS arg, long argFlags, Unt context, Expand *xp, Boole forceit);
CS expand_user_command_name(int idx);
CS get_user_commands(Expand *xp, int idx);
CS get_user_command_name(int idx, int id);
CS get_user_cmd_addr_type(Expand *xp, int idx);
CS get_user_cmd_flags(Expand *xp, int idx);
CS get_user_cmd_nargs(Expand *xp, int idx);
CS get_user_cmd_complete(Expand *xp, int idx);
CS cmdcomplete_type_to_str(int expand, CS compl_arg);
int cmdcomplete_str_to_type(Byte *complete_str);
CS uc_fun_cmd(void);
int parse_compl_arg(CS value, int vallen, int *context, long *argFlags, CS *compl_arg);
void c_command(Invocation *invo);
void c_comclear(Invocation *invo);
void uc_clear(ArrayList *gap);
void c_delcommand(Invocation *invo);
Unt add_win_cmd_modifiers(CS builder, CommandModifier *cmod, int *multi_mods);
void do_ucmd(Invocation *invo);
void func_init(void);
EeSet *func_tbl_get(void);
CS make_ufunc_name_readable(Byte *name, Byte *builder, Unt bufsize);
Text get_lambda_name(void);
Byte *register_cfunc(cfunc_T cb, cfunc_free_T cb_free, void *state);
int get_lambda_tv(Byte **arg, Var *returnVar, EvalCtx *evalarg);
Text deref_func_name(Text name, PartiallyApplied **partialp, TypeSpec **type, Boole no_autoload, Boole *found_var);
void emsg_funcname(CS ermsg, Byte *name);
int get_func_arguments(Byte **arg, EvalCtx *evalarg, int partial_argc, Var *argvars, int *argcount);
int get_func_tv(CS name, int len, Var *returnVar, Byte **arg, EvalCtx *evalarg, FnExe *funcexe);
Byte *fname_trans_sid(Byte *name, Byte *fname_buf, Byte **tofree, FnError *error);
void func_name_with_sid(CS name, int sid, CS builder);
UserFunc *find_func_even_dead(CS name, int flags);
UserFunc *find_func(CS name, Boole is_global);
int func_is_global(UserFunc *ufunc);
int func_requires_g_prefix(UserFunc *ufunc);
int func_name_refcount(Byte *name);
void func_clear_free(UserFunc *fp, int force);
int funcdepth_increment(void);
void funcdepth_decrement(void);
int funcdepth_get(void);
void funcdepth_restore(int depth);
FnCall *create_funccal(UserFunc *fp, Var *returnVar);
void remove_funccal(void);
FnError check_user_func_argcount(UserFunc *fp, int argcount);
FnError call_user_func_check(UserFunc *fp, int argcount, Var *argvars, Var *returnVar, FnExe *funcexe, Bag *selfdict);
void save_funccal(FnCallEntry *entry);
void restore_funccal(void);
FnCall *get_current_funccal(void);
int at_script_level(void);
void delete_scrifntions(int sid);
void free_all_functions(void);
int func_call(Byte *name, Var *args, PartiallyApplied *partial, Bag *selfdict, Var *returnVar);
int get_callback_depth(void);
int call_callback(Callback *callback, int len, Var *returnVar, int argcount, Var *argvars);
Long call_callback_retnr(Callback *callback, int argcount, Var *argvars);
void user_func_error(FnError error, Byte *name, int found_var);
int call_func(Byte *funcname, int len, Var *returnVar, int argcount_in, Var *argvars_in, FnExe *funcexe);
int call_simple_func(CS funcname, Unt len, Var *returnVar);
CS printable_func_name(UserFunc *fp);
CS trans_function_name(CS *name, Boole *is_global, Boole skip, Unt flags);
CS get_scriptlocal_funcname(CS funcname);
CS alloc_printable_func_name(Byte *fname);
CS save_function_name(CS *name, Boole *is_global, Boole skip, Unt flags, FuncDict *fudi);
void list_functions(RegMatch *regmatch);
int get_func_arity(CS name, int *required, int *optional, int *varargs);
int scriptCheckScriptPrefix(CS p);
int translated_function_exists(CS name, Boole is_global);
int has_varargs(UserFunc *ufunc);
int function_exists(CS name, int no_deref);
CS get_user_func_name(Expand *xp, int idx);
void c_delfunction(Invocation *invo);
void func_unref(CS name);
void func_ptr_unref(UserFunc *fp);
void func_ref(CS name);
void func_ptr_ref(UserFunc *fp);
void c_return(Invocation *invo);
int can_add_defer(void);
int add_defer(CS name, int argcount_arg, Var *argvars);
void invoke_all_defer(void);
void c_call(Invocation *invo);
int do_return(Invocation *invo, int reanimate, int is_cmd, void *returnVar);
void discard_pending_return(void *returnVar);
CS get_return_cmd(void *returnVar);
CS get_func_line(Unt c, void *cookie, int indent, GetlineAlgo options);
int func_has_ended(void *cookie);
int func_has_abort(void *cookie);
Bag *make_partial(Bag *selfdict_in, Var *returnVar);
CS func_name(void *cookie);
LineNr *func_breakpoint(void *cookie);
int *func_dbg_tick(void *cookie);
int func_level(void *cookie);
int current_func_returned(void);
int free_unref_funccal(int copyID, int testing);
EeSet *get_funccal_local_ht(void);
DictItem *get_funccal_local_var(void);
EeSet *get_funccal_args_ht(void);
DictItem *get_funccal_args_var(void);
void list_func_vars(int *first);
Bag *get_current_funccal_dict(EeSet *ht);
EeSetItem *find_hi_in_scoped_ht(CS name, EeSet **pht);
DictItem *findVar_in_scoped_ht(Text name, Boole no_autoload);
int set_ref_in_previous_funccal(int copyID);
int set_ref_in_call_stack(int copyID);
int set_ref_in_functions(int copyID);
int set_ref_in_func_args(int copyID);
int set_ref_in_func(CS name, UserFunc *fp_in, int copyID);
UserFunc *define_function(Invocation *invo, ArrayList *lines_to_free);
void c_function(Invocation *invo);
int var_wrong_func_name(Text name, int new_var);
void scrRemoveAutocommsFromBook(Book *book);
Boole auGroupExists(CS name);
void do_augroup(CS arg, Boole del_group);
void autocmd_init(void);
void free_all_autocmds(void);
int is_autoCommPort(Portal *port);
Boole event_ignored(AutoEvent event, CS evIgn);
int check_ei(CS evIgn);
CS au_event_disable(CS what);
void au_event_restore(CS old_ei);
void do_autocmd(Invocation *invo, CS arg_in, int forceit);
int autoEventImpl(AutoEvent event, CS pat, AutoCommCreation creation);
int do_doautocmd(CS arg_start, Boole do_msg, Boole *didSomething);
void c_doautoall(Invocation *invo);
void auCommPrepareBook(AutocommSave *aco, Book *book);
void auCommRestoreBook(AutocommSave *aco);
int apply_autocmds(AutoEvent event, CS fname, CS fname_io, Boole force, Book *book);
int auCommApplyWithInvo(AutoEvent event, CS fname, CS fname_io, Boole force, Book *book, Invocation *invo);
int apply_autocmds_retval(AutoEvent event, CS fname, CS fname_io, Boole force, Book *book, int *retval);
int trigger_cursorhold(void);
int has_winresized(void);
int has_winscrolled(void);
int has_cmdundefined(void);
int has_textyankpost(void);
int has_completechanged(void);
int has_modechanged(void);
void block_autocmds(void);
void unblock_autocmds(void);
int areAutocommsBlocked(void);
CS getnextac(Unt c, void *cookie, int indent, GetlineAlgo options);
int has_autocmd(AutoEvent event, CS sfname, Book *book);
CS get_event_name(Expand *xp, int idx);
CS get_event_name_no_group(Expand *xp, int idx, int win);
int has_tabclosedpre(void);
int autocmd_supported(CS name);
int au_exists(CS arg);
void f_autocmd_add(Var *argvars, Var *returnVar);
void f_autocmd_delete(Var *argvars, Var *returnVar);
void f_autocmd_get(Var *argvars, Var *returnVar);
/* eegl: set ft=c : */
