/* src/search.c */
int search_regcomp(CS pat, Unt patlen, CS *used_pat, int pat_save, int pat_use, int options, RegMultilineMatch *regmatch);
CS get_search_pat(void);
void save_re_pat(int idx, CS pat, Unt patlen, int magic);
void save_search_patterns(void);
void restore_search_patterns(void);
void free_search_patterns(void);
void save_last_search_pattern(void);
void restore_last_search_pattern(void);
CS last_search_pattern(void);
Unt last_search_patternLen(void);
int ignorecase(CS pat);
int ignorecase_opt(Byte *pat, int ic_in, int scs);
int pat_has_uppercase(CS pat);
Byte *last_csearch(void);
int last_csearch_forward(void);
int last_csearch_until(void);
void set_last_csearch(int c, CS s, int len);
void set_csearch_direction(int cdir);
void set_csearch_until(int t_cmd);
CS last_search_pat(void);
void reset_search_dir(void);
void set_last_search_pat(Byte *s, int idx, int magic, int setlast);
void last_pat_prog(RegMultilineMatch *regmatch);
int searchit(Portal *port, Book *book, Pos *pos, Pos *end_pos, Unt dir, CS pat, Unt patlen, long count, int options, int pat_use, SearchitArg *extra_arg);
void set_search_direction(int cdir);
int do_search(Operator *oap, int dirc, int search_delim, CS pat, Unt patlen, long count, int options, SearchitArg *sia);
int search_for_exact_line(Book *book, Pos *pos, int dir, Byte *pat);
int searchc(ActionArg *cap, int t_cmd);
Pos *findmatch(Operator *oap, int initc);
Pos *findmatchlimit(Operator *oap, Unt initc, int flags, int maxtravel);
int check_linecomment(CS line);
int current_search(long count, int forward);
int linewhite(LineNr lnum);
void find_pattern_in_path(CS ptr, int dir, int len, int whole, int skip_comments, int type, long count, int action, LineNr start_lnum, LineNr end_lnum, int forceit, int silent);
SearchPattern *getPrevSearchPattern(int idx);
int getPrevSearchOrSubstPattern(void);
void f_searchcount(Var *argvars, Var *returnVar);
void clear_matches(Portal *wp);
void init_search_hl(Portal *wp, Match *search_hl);
void prepare_search_hl(Portal *wp, Match *search_hl, LineNr lnum);
Boole searchPrepareHiliteLine(Portal *wp, LineNr lnum, ColNr mincol, CS *line, Match *search_hl, Short *searchHiId);
Short update_search_hl(Portal *wp, LineNr lnum, ColNr col, CS *line, Match *search_hl, int didLineDecorations, int lcs_eol_one, Boole *onLastCol);
int get_prevcol_hl_flag(Portal *wp, Match *search_hl, long curcol);
void get_search_match_hl(Portal *wp, Match *search_hl, long col, Short *charHiId);
void f_clearmatches(Var *argvars, Var *returnVar);
void f_getmatches(Var *argvars, Var *returnVar);
void f_setmatches(Var *argvars, Var *returnVar);
void f_matchadd(Var *argvars, Var *returnVar);
void f_matchaddpos(Var *argvars, Var *returnVar);
void f_matcharg(Var *argvars, Var *returnVar);
void f_matchdelete(Var *argvars, Var *returnVar);
void c_match(Invocation *invo);
void c_help(Invocation *invo);
void c_helpclose(Invocation *invo);
CS check_help_lang(CS arg);
int help_heuristic(CS matched_string, int offset, int wrong_case);
int find_help_tags(CS arg, int keep_lang, ExpandMatch *matches);
void cleanup_help_tags(ExpandMatch *matches);
void prepare_help_buffer(void);
void searchFixHelpBook(void);
void c_exusage(Invocation *invo);
void c_usage(Invocation *invo);
void c_helptags(Invocation *invo);
/* eegl: set ft=c : */
