/* src/spelling.c */
int spell_check(Portal *wp, Byte *ptr, Unt *retDeco, int *capcol, int docount);
int match_checkcompoundpattern(Byte *ptr, int wlen, ArrayList *gap);
int can_compound(SpellLang *slang, Byte *word, Byte *flags);
int match_compoundrule(SpellLang *slang, Byte *compflags);
int valid_word_prefix(int totprefcnt, int arridx, int flags, Byte *word, SpellLang *slang, int cond_req);
int spell_valid_case(int wordflags, int treeflags);
int isSpellcheckingEnabledInPortal(Portal *wp);
int spell_move_to(Portal *wp, Unt dir, SpellMoveTo behaviour, int curline, Unt *retDeco);
void spell_cat_line(Byte *buf, Byte *line, int maxlen);
SpellLang *slang_alloc(Byte *lang);
void slang_free(SpellLang *lp);
void slang_clear(SpellLang *lp);
void slang_clear_sug(SpellLang *lp);
void count_common_word(SpellLang *lp, Byte *word, int len, int count);
int byte_in_str(Byte *str, int n);
int init_syl_tab(SpellLang *slang);
CS parse_spelllang(Portal *wp);
int captype(Byte *word, Byte *end);
void spell_delete_wordlist(void);
void spell_free_all(void);
void spell_reload(void);
Book *open_spellbuf(void);
void close_spellbuf(Book *buf);
void clear_spell_chartab(SpellTab *sp);
void init_spell_chartab(void);
int spell_iswordp(Byte *p, Portal *wp);
int spell_casefold(Portal *wp, Byte *str, int len, Byte *buf, int buflen);
void c_spellrepall(Invocation *invo);
void onecap_copy(Byte *word, Byte *wcopy, int upper);
void allcap_copy(Byte *word, Byte *wcopy);
int nofold_len(Byte *fword, int flen, Byte *word);
void make_case_word(Byte *fword, Byte *cword, int flags);
CS eval_soundfold(Byte *word);
void spell_soundfold(SpellLang *slang, Byte *inword, int folded, Byte *res);
void c_spellinfo(Invocation *invo);
void c_spelldump(Invocation *invo);
void spell_dump_compl(CS pat, int ic, Unt *dir, int dumpflags_arg);
Byte *spell_to_word_end(Byte *start, Portal *win);
int spell_word_start(int startcol);
int expand_spelling(LineNr lnum, CS pat, ExpandMatch *matches);
int valid_spelllang(CS val);
int valid_spellfile(CS val);
CS did_set_spell_option(void);
SpellLang *spell_load_file(Byte *fname, Byte *lang, SpellLang *old_lp, int silent);
void suggest_load_files(void);
int spell_check_msm(void);
void c_mkspell(Invocation *invo);
void mkspell(ExpandMatch files, int ascii, int over_write, int added_word);
void c_spell(Invocation *invo);
void spell_add_word(Byte *word, int len, int what, int idx, int undo);
int spell_check_sps(void);
void spell_suggest(int count);
void spell_suggest_list(ArrayList *gap, Byte *word, int maxcount, int interactive);
/* eegl: set ft=c : */
