/* src/strings.c */
void trans_characters(CS buf, int bufsize);
CS sanitizeStr(CS s);
CS str_foldcase(CS str, Unt orglen, CS buf, Unt bufLen);
unsigned nr2hex(unsigned c);
void transchar_hex(CS buf, int c);
int eeglStrNsize(CS s, int len);
int eeglStrSize(CS s);
int eeIsFnameChar_or_wc(Unt c);
CS skipwhite(CS q);
CS skipSpace(CS q);
CS skipwhite_and_nl(CS q);
int getwhitecols_curline(void);
int getwhitecols(CS p);
CS skipdigits(CS q);
CS skipbin(CS q);
CS skiphex(CS q);
CS skiptobin(CS q);
CS skiptodigit(CS q);
CS skiptohex(CS q);
int eeIsDigit(int c);
int eeIsXDigit(Unt c);
Boole eeIsLower(Unt c);
int eeIsUpper(Unt c);
int eeglIsAlfa(int c);
int eeglToUpper(Unt c);
int eeglToLower(Unt c);
CS skiptowhite(CS p);
CS skiptowhite_esc(CS p);
CS skipToLastSpace(CS p);
long parseLong(CS *pp);
long parseLong_quoted(CS *pp);
int eeIsBlankLine(CS lbuf);
void readLongNumber(CS start, int *prep, int *len, int what, Long *nptr, Ulong *unptr, int maxlen, Boole strict, Boole *overflow);
int hex2nr(int c);
int hexhex2nr(CS p);
int rem_backslash(CS filename);
void backslash_halve(CS p);
CS backslash_halve_save(CS p);
Unt utfCharLen(CS p);
Unt utfCharLen_len(Byte *p, int size);
Boole eq_CString_CString(CS a, CS b);
CS findWordStart(CS ptr);
CS skipToComma(CS s);
CS skip_to_option_part(CS p);
CS copyStr(CS string);
CS copySubstr(CS string, Unt len);
CS copyStr_escaped(CS string, CS escChars);
CS *splitByCharIntoArray(CS inp, Byte delimiter, Unt *len);
CS copyStr_shellescape(CS string, int do_special, int do_newline);
CS copyStr_up(CS string);
CS copySubstr_up(CS string, Unt len);
int isSpace(int x);
void asciiToUpper(CS p);
CS strlow_save(CS orig);
void del_trailing_spaces(CS ptr);
void concatenateStrings(CS to, CS from, Unt tosize);
int compareAscii(CS s1, CS s2, Unt len);
CS firstOccurrence(CS string, Unt c);
CS firstByteOccurrence(CS string, Byte b);
CS eeStrbyte(CS string, Unt c);
CS lastOccurrence(CS string, int c);
void sortStrings(CS *files, int count);
int has_non_ascii(CS s);
CS concat_str(CS str0, CS str1);
CS reverse_text(CS s);
CS string_quote(CS str, int function);
long string_count(CS haystack, CS needle, int ic);
long char_idx2byte(CS str, Unt str_len, Long idx);
Boole startsWith(CS longerStr, CS shorterStr);
int fuzzy_match(CS str, CS pat_arg, int matchseq, int *outScore, Unt *matches, int maxMatches);
int fuzzyMatchStr(CS str, CS pat);
CS find_word_end(CS ptr);
CS find_line_end(CS ptr);
CS encodeBase64(void const *binaryData_, int inputLen);
int same_directory(CS f1, CS f2);
CS remove_tail(CS p, CS pend, CS name);
Boole after_pathsep(CS fileName, CS afterSep);
Boole path_is_url(CS p);
Boole path_with_url(CS fname);
Boole has_format_option(int x);
void internal_format(int textwidth, int second_indent, int flags, int format_only, Unt c);
void auto_format(int trailblank, int prev_line);
void check_auto_format(int end_insert);
int comp_textwidth(int ff);
int valid_name(CS val, CS allowed);
int isValidForScriptName(int c);
int isValidForScriptName1(int c);
int isValidForFirstCharDictKey(int c);
int xxdMain(int argc, char *argv[]);
