/* src/strings.c */
void trans_characters(CS buf, int bufsize);
CS sanitizeStr(CS s);
CS str_foldcase(CS str, Unt orglen, CS buf, Unt bufLen);
unsigned nr2hex(unsigned c);
void transchar_hex(CS buf, int c);
int eeglStrNsize(CS s, int len);
int eeglStrSize(CS s);
int eeIsFnameChar_or_wc(Unt c);
CS skipwhite(CS q);
CS skipSpace(CS q);
CS skipwhite_and_nl(CS q);
int getwhitecols_curline(void);
int getwhitecols(CS p);
CS skipdigits(CS q);
CS skipbin(CS q);
CS skiphex(CS q);
CS skiptobin(CS q);
CS skiptodigit(CS q);
CS skiptohex(CS q);
int eeIsDigit(int c);
int eeIsXDigit(Unt c);
Boole eeIsLower(Unt c);
int eeIsUpper(Unt c);
int eeglIsAlfa(int c);
int eeglToUpper(Unt c);
int eeglToLower(Unt c);
CS skiptowhite(CS p);
CS skiptowhite_esc(CS p);
CS skipToLastSpace(CS p);
long parseLong(CS *pp);
long parseLong_quoted(CS *pp);
int eeIsBlankLine(CS lbuf);
void readLongNumber(CS start, int *prep, int *len, int what, Long *nptr, ULong *unptr, int maxlen, Boole strict, Boole *overflow);
int hex2nr(int c);
int hexhex2nr(CS p);
int rem_backslash(CS filename);
void backslash_halve(CS p);
CS backslash_halve_save(CS p);
void appendSubDir(char *subDir, DirName *dn);
Boole removeSubDir(DirName *restrict dn);
CS toFullFileName(Text fileName, DirName *dn);
ChunkyString *createChunkyString(Byte const *c, Arena *a);
void appendToChunkyString(Byte const *c, ChunkyString *chunky);
CS toStringChunky(ChunkyString *chunky);
Text mbText(CS b);
Text text(CS b);
Boole eq_Text_Text(Text a, Text b);
Boole eq_Text_CString(Text a, CS b);
Boole eq_CString_CString(CS a, CS b);
Text skipTo(Text inp, CS t);
CS findWordStart(CS ptr);
CS skipToComma(CS s);
CS skip_to_option_part(CS p);
CS copyStr(CS string);
CS copySubstr(CS string, Unt len);
Sbuf sbuf(Unt cap);
void concatToBuf(Text s, Sbuf *buf);
CS copySubstrA(CS string, Unt len, Arena *a);
Text copyText(Text slice);
CS copyStrA(CS string, Arena *a);
CS copyStr_escaped(CS string, CS escChars);
CS copyStrEscapedA(CS string, CS escChars, Arena *a);
CS copyStr_escaped_ext(CS string, CS esc_chars, Unt cc, Boole bsl, Arena *a);
CS *splitByCharIntoArray(CS inp, Byte delimiter, Unt *len);
ArrayList splitBySpace(CS inp);
CS copyStr_shellescape(CS string, int do_special, int do_newline);
CS copyStr_up(CS string);
CS copySubstr_up(CS string, Unt len);
int isSpace(int x);
void asciiToUpper(CS p);
Text skipQuoted(Text s);
Text skipSingleQuoted(Text s);
CS strlow_save(CS orig);
void del_trailing_spaces(CS ptr);
void copySubstrToAllocation(CS to, Text from);
void concatenateStrings(CS to, CS from, Unt tosize);
int compareAscii(CS s1, CS s2, Unt len);
CS firstOccurrence(CS string, Unt c);
CS firstByteOccurrence(CS string, Byte b);
CS eeStrbyte(CS string, Unt c);
CS lastOccurrence(CS string, int c);
void sortStrings(CS *files, int count);
int has_non_ascii(CS s);
CS concat_str(CS str0, CS str1);
CS reverse_text(CS s);
CS string_quote(CS str, int function);
long string_count(CS haystack, CS needle, int ic);
void string_filter_map(CS str, FilterMap filtermap, Var *expr, Var *returnVar);
void string_reduce(Var *argvars, Var *expr, Var *returnVar);
void f_byteidx(Var *argvars, Var *returnVar);
void f_byteidxcomp(Var *argvars, Var *returnVar);
void f_charidx(Var *argvars, Var *returnVar);
void f_blob2str(Var *argvars, Var *returnVar);
void f_str2blob(Var *argvars, Var *returnVar);
void f_str2list(Var *argvars, Var *returnVar);
void f_str2nr(Var *argvars, Var *returnVar);
void f_strgetchar(Var *argvars, Var *returnVar);
void f_stridx(Var *argvars, Var *returnVar);
void f_string(Var *argvars, Var *returnVar);
void f_strlen(Var *argvars, Var *returnVar);
void f_strcharlen(Var *argvars, Var *returnVar);
void f_strchars(Var *argvars, Var *returnVar);
void f_strdisplaywidth(Var *argvars, Var *returnVar);
void f_strwidth(Var *argvars, Var *returnVar);
void f_strcharpart(Var *argvars, Var *returnVar);
void f_strpart(Var *argvars, Var *returnVar);
void f_strridx(Var *argvars, Var *returnVar);
void f_strtrans(Var *argvars, Var *returnVar);
void f_tolower(Var *argvars, Var *returnVar);
void f_toupper(Var *argvars, Var *returnVar);
void f_tr(Var *argvars, Var *returnVar);
void f_trim(Var *argvars, Var *returnVar);
long char_idx2byte(CS str, Unt str_len, Long idx);
CS concatStrArray(CS *arr, Unt len, Text separator, Arena *a);
CS fileExtension(Text fName);
Boole startsWith(CS longerStr, CS shorterStr);
void addFuzzyMatch(FuzzyMatch m, Fuzzy *t);
int fuzzy_match(CS str, CS pat_arg, int matchseq, int *outScore, Unt *matches, int maxMatches);
void f_matchfuzzy(Var *argvars, Var *returnVar);
void f_matchfuzzypos(Var *argvars, Var *returnVar);
void fuzzySortByScore(Fuzzy *fuzzy);
int fuzzyMatchStr(CS str, CS pat);
ArrayList *fuzzyMatchStr_with_pos(CS str, CS pat);
CS find_word_end(CS ptr);
CS find_line_end(CS ptr);
int fuzzyMatchStr_in_line(Byte **ptr, CS pat, int *len, Pos *current_pos, int *score);
int search_for_fuzzy_match(Book *book, Pos *pos, CS pattern, int dir, Pos *start_pos, int *len, CS *ptr, int *score);
void fuzmatch_str_free(FuzzyMatch *fuzmatch, int count);
int defuzz(ExpandMatch *matches, Fuzzy fuzzy, Boole funcsort);
CS encodeBase64(void const *binaryData_, int inputLen);
ArrayList decodeBase64(Byte const *base64, int inputLen);
int same_directory(CS f1, CS f2);
CS remove_tail(CS p, CS pend, CS name);
Boole after_pathsep(CS fileName, CS afterSep);
int path_is_url(CS p);
int path_with_url(CS fname);
Boole has_format_option(int x);
void internal_format(int textwidth, int second_indent, int flags, int format_only, Unt c);
void auto_format(int trailblank, int prev_line);
void check_auto_format(int end_insert);
int comp_textwidth(int ff);
void op_format(Operator *oper, int keep_cursor);
void op_formatexpr(Operator *oper);
int fex_format(LineNr lnum, long count, int c);
void format_lines(LineNr line_count, int avoid_fex);
UiColor decode_hex_color(Text hex);
UiColor decodeHexColorLengthGuaranteed(CS hex);
int valid_name(CS val, CS allowed);
int isValidForScriptName(int c);
int isValidForScriptName1(int c);
int isValidForFirstCharDictKey(int c);
int xxdMain(int argc, char *argv[]);
/* eegl: set ft=c : */
