/* src/term.c */
UiColor termgui_mch_get_rgb(UiColor color);
void init_term_props(int all);
void f_terminalprops(Var *argvars, Var *returnVar);
int set_termname(CS termName);
void free_cur_term(void);
void getlinecol(long *cp, long *rp);
int add_termcap_entry(CS name, int force);
void termInitTerminfo(CS name);
void out_flush(void);
void out_char(unsigned c);
void out_str_nf(CS s);
void out_str(CS s);
void term_windgoto(int row, int col);
void term_cursor_right(int i);
void term_append_lines(int line_count);
void term_delete_lines(int line_count);
void term_enable_mouse(int enable);
void term_set_winpos(int x, int y);
int term_get_winpos(int *x, int *y, Long timeout);
void term_set_winsize(int height, int width);
void term_font(int n);
void term_fg_color(int n);
void term_bg_color(int n);
void term_ul_color(int n);
void term_fgRgb_color(UiColor rgb);
void term_bgRgb_color(UiColor rgb);
void term_underlRgb_color(UiColor rgb);
void ttest(int pairs);
void add_long_to_buf(Ulong val, Byte *dst);
int get_bytes_from_buf(CS buffer, CS bytes, int num_bytes);
void check_shellsize(void);
void clampScreenSize(void);
void win_new_shellsize(void);
void shell_resized(void);
void shell_resized_check(void);
void set_shellsize(int width, int height, int mustset);
void out_str_t_TE(void);
void out_str_t_TI(void);
void out_str_t_BE(void);
void may_send_t_RK(void);
void termSetMode(TermInputMode tmode);
void starttermcap(void);
void termStopTerminfo(void);
void may_req_termresponse(void);
void check_terminal_behavior(void);
void may_req_bg_color(void);
int swapping_screen(void);
void scroll_start(void);
void cursor_on_force(void);
void cursor_on(void);
void cursor_off(void);
void cursor_sleep(void);
void cursor_unsleep(void);
void term_cursor_mode(int forced);
void term_cursor_color(CS color);
int blink_state_is_inverted(void);
void term_cursor_shape(int shape, int blink);
void scroll_region_set(Portal *wp, int off);
void scroll_region_reset(void);
void clear_termcodes(void);
void add_termcode(CS name, CS string, Boole isAtcFromTerm);
CS find_termcode(CS name);
CS get_termcode(int i);
int get_termcode_len(int idx);
void del_termcode(Byte *name);
void set_mouse_topline(Portal *wp);
int is_mouse_topline(Portal *wp);
int termPutStrIntoTypebuf(int offset, int slen, CS string, int new_slen, CS buffer, int bufsize, int *bufLen);
Unt decode_modifiers(int n);
int check_termcode(int max_offset, CS buffer, int bufsize, int *bufLen);
void term_get_fg_color(Byte *r, Byte *g, Byte *b);
void term_get_bg_color(Byte *r, Byte *g, Byte *b);
void get_stty(void);
int get_tty_info(int fd, TtyInfo *info);
void mch_termSetMode(TermInputMode tmode);
void check_mouse_termcode(void);
CS get_key_name(int i);
CS replace_termcodes(CS from, CS *bufP, ScriptId sid_arg, int flags, Boole *didSimplify, Boole recognizeRawKeycodes);
Unt simplify_key(Unt key, Unt *modifiers);
void show_termcodes(Unt flags);
CS get_special_key_name(Unt c, int modifiers);
int get_special_key_code(CS name);
int show_one_termcode(CS name, CS code, int printit);
void ansi_color2rgb(int nr, Byte *r, Byte *g, Byte *b, Byte *ansi_idx);
void cterm_color2rgb(int nr, Byte *r, Byte *g, Byte *b, Byte *ansi_idx);
int term_replace_keycodes(CS ta_buf, int ta_len, int len_arg);
int find_special_key(Byte **srcp, int *modp, int flags, Boole *didSimplify);
int find_special_key_in_table(int c);
int special_to_buf(Unt key, int modifiers, int escape_ks, Byte *dst);
int trans_special(Byte **srcp, Byte *dst, int flags, int escape_ks, Boole *didSimplify);
int setup_slavepty(int fd);
int openpty(char **ttyn);
int mch_isatty(int fd);
/* eegl: set ft=c : */
