/* src/term.c */
void _incRefCount(void *a);
void _decRefCount(void *a);
Unt _getRefCount(void *a);
void termInitProps(Boole all);
void f_terminalprops(Var *argvars, Var *returnVar);
int set_termname(CS termName);
void free_cur_term(void);
void getlinecol(long *cols, long *rows);
int add_termcap_entry(CS name, int force);
void termInitTerminfo(CS name);
void out_flush(void);
void out_char(unsigned c);
void out_str_nf(CS s);
void out_str(CS s);
void term_windgoto(int row, int col);
void term_cursor_right(int i);
void term_append_lines(int line_count);
void term_delete_lines(int line_count);
void term_enable_mouse(int enable);
void term_set_winpos(int x, int y);
int term_get_winpos(int *x, int *y, Long timeout);
void term_set_winsize(int height, int width);
void termApplyFgColor(Byte n);
void termApplyBgColor(Byte n);
void termApplyUnderColor(Byte n);
void ttest(int pairs);
void add_long_to_buf(Ulong val, CS dst);
int get_bytes_from_buf(CS buffer, CS bytes, int num_bytes);
void check_shellsize(void);
void clampScreenSize(void);
void win_new_shellsize(void);
void shell_resized(void);
void shell_resized_check(void);
void set_shellsize(int width, int height, int mustset);
void out_str_t_TE(void);
void out_str_t_TI(void);
void out_str_t_BE(void);
void may_send_t_RK(void);
void termSetMode(TermInputMode tmode);
void starttermcap(void);
void termStopTerminfo(void);
void check_terminal_behavior(void);
int termIsScreenBeingSwapped(void);
void scroll_start(void);
void cursor_on_force(void);
void cursor_on(void);
void cursor_off(void);
void cursor_sleep(void);
void cursor_unsleep(void);
void term_cursor_mode(int forced);
void term_cursor_color(CS color);
int blink_state_is_inverted(void);
void termSetCursorShape(int shape, int blink);
void scroll_region_set(Portal *wp, int off);
void scroll_region_reset(void);
void clear_termcodes(void);
void termAddRecognizedTermcode(CS name, CS string, Boole isAtcFromTerm);
CS find_termcode(CS name);
void del_termcode(CS name);
void set_mouse_topline(Portal *po);
int is_mouse_topline(Portal *po);
int termPutStrIntoTypeBuf(int offset, int slen, Text newText);
Unt decode_modifiers(int n);
int termTryParseTermcode(int max_offset, Text buffer, int *bufLen);
void get_stty(void);
int get_tty_info(int fd, TtyInfo *info);
void mch_termSetMode(TermInputMode tmode);
void check_mouse_termcode(void);
CS get_key_name(int i);
CS replace_termcodes(CS from, CS *bufP, ScriptId sid_arg, Unt flags, Boole *didSimplify, Boole recognizeRawKeycodes);
Unt simplify_key(Unt key, Unt *modifiers);
void show_termcodes(Unt flags);
CS get_special_key_name(Unt c, int modifiers);
int get_special_key_code(CS name);
int show_one_termcode(CS name, CS code, int printit);
void ansi_color2rgb(int nr, Byte *r, Byte *g, Byte *b, Byte *ansi_idx);
void cterm_color2rgb(int nr, Byte *r, Byte *g, Byte *b, Byte *ansi_idx);
int term_replace_keycodes(CS ta_buf, int ta_len, int len_arg);
int termFindSpecialKey(Byte **srcp, Unt *modp, Unt flags, Boole *didSimplify);
int termFindSpecialKey_in_table(int c);
int special_to_buf(Unt key, Unt modifiers, int escape_ks, CS dst);
int trans_special(Byte **srcp, CS dst, Unt flags, int escape_ks, Boole *didSimplify);
int setup_slavepty(int fd);
int openpty(char **ttyn);
int mch_isatty(int fd);
