/* src/ui.c */
void _incRefCount(void *a);
void _decRefCount(void *a);
Unt _getRefCount(void *a);
void init_job_options(JobOptions *opt);
void c_terminal(Invocation *invo);
int expand_terminal_opt(CS pat, Expand *xp, RegMatch *rmp, ExpandMatch *matches);
int term_write_session(FILE *fd, Portal *po, EeSet *terminal_bufs);
int term_should_restore(Book *book);
void free_terminal(Book *book);
void free_unused_terminals(void);
void write_to_term(Book *book, CS msg, Channel *channel);
int term_job_running(Terminal *term);
int term_job_running_not_none(Terminal *term);
int term_none_open(Terminal *term);
int term_confirm_stop(Book *book);
int term_try_stop_job(Book *book);
int term_check_timers(int next_due_arg, ProfTime *now);
int term_in_normal_mode(void);
void term_enter_job_mode(void);
void check_no_reduce_keys(void);
int send_keys_to_term(Terminal *term, Unt c, int modmask, int typed);
int terminal_is_active(void);
int term_use_loop(void);
void term_enterPortaled(void);
void term_focus_change(int in_focus);
int terminal_loop(int blocking);
Decoration cellToDecoration(VTermDeco flags, VTermColor fg, VTermColor bg);
int may_close_term_popup(void);
void term_channel_closing(Channel *ch);
void term_channel_closed(Channel *ch);
void term_check_channel_closed_recently(void);
int termDoUpdatePortal(Portal *po);
void termUpdatePortal(Portal *po);
void termDidUpdatePortal(Portal *po);
int term_is_finished(Book *book);
int term_shobuffer(Book *book);
void uiBeforeLeavingTerminal(void);
Decoration uiGetDeco(Portal *po, LineNr lnum, int col);
void term_update_colors_all(void);
CS term_get_status_text(Terminal *term);
void term_clear_status_text(Terminal *term);
int set_ref_in_term(int copyID);
void f_term_dumpwrite(Var *argvars, Var *returnVar);
int term_swap_diff(void);
void f_term_dumpdiff(Var *argvars, Var *returnVar);
void f_term_dumpload(Var *argvars, Var *returnVar);
void f_term_getaltscreen(Var *argvars, Var *returnVar);
void f_term_getcursor(Var *argvars, Var *returnVar);
void f_term_getjob(Var *argvars, Var *returnVar);
void f_term_getline(Var *argvars, Var *returnVar);
void f_term_getscrolled(Var *argvars, Var *returnVar);
void f_term_getsize(Var *argvars, Var *returnVar);
void f_term_setsize(Var *argvars, Var *returnVar);
void f_term_getstatus(Var *argvars, Var *returnVar);
void f_term_gettitle(Var *argvars, Var *returnVar);
void f_term_gettty(Var *argvars, Var *returnVar);
void f_term_list(Var *argvars, Var *returnVar);
void f_term_scrape(Var *argvars, Var *returnVar);
void f_term_sendkeys(Var *argvars, Var *returnVar);
void f_term_setapi(Var *argvars, Var *returnVar);
void f_term_setrestore(Var *argvars, Var *returnVar);
void f_term_setkill(Var *argvars, Var *returnVar);
void f_term_start(Var *argvars, Var *returnVar);
void f_term_wait(Var *argvars, Var *returnVar);
void term_send_eof(Channel *ch);
Job *term_getjob(Terminal *term);
void preserve_exit(void);
int realWaitForChar(int fd, long msec, int *check_for_gpm, int *interrupted);
int mch_input_isatty(void);
void uiInit(void);
void ui_write(CS s, int len, int console);
void ui_inBytendo(CS s, int len);
int ui_inchar(CS buf, int maxlen, long wtime, int changeCnt);
int inchar_loop(CS buf, int maxlen, long wtime, int changeCnt, int (*wait_func)(long wtime, int *interrupted, int ignore_input), int (*resize_func)(int check_only));
int waitForChar(long msec, int *interrupted, int ignore_input);
int ui_char_avail(void);
void ui_delay(long msec_arg, int ignoreinput);
int ui_get_shellsize(void);
void ui_set_shellsize(int mustset);
int uiGetPortPos(int *x, int *y, Long timeout);
void ui_breakcheck(void);
void ui_breakcheck_force(Boole force);
int eeIsInputBufFull(void);
int eeIsInputBufEmpty(void);
int eeglFree_in_input_buf(void);
CS get_input_buf(void);
void set_input_buf(CS p, Boole overwrite);
void add_to_input_buf(CS s, int len);
void add_to_input_buf_csi(CS str, int len);
void trash_input_buf(void);
int read_from_input_buf(CS buf, long maxlen);
void fill_input_buf(Boole exit_on_error);
void read_error_exit(void);
void ui_cursor_shape(void);
Unt check_col(Unt col);
Unt check_row(Unt row);
long scroll_line_len(LineNr lnum);
LineNr ui_find_longest_lnum(void);
void ui_focus_change(int in_focus);
int mch_report_winsize(int fd, int rows, int cols);
void mch_set_shellsize(void);
void mch_calc_cell_size(CellSize *cs_out);
int mch_get_shellsize(void);
int uiValidateTabpanelopt(CS new);
int tabpanel_width(void);
int tabpanel_leftcol(void);
void draw_tabpanel(void);
Unt get_tabNr_on_tabpanel(void);
