// Name:         darkblue
// Description:  For those who prefer dark background
// Author:       Original author Bohdan Vlasyuk <bohdan@vstu.edu.ua>
// Maintainer:   Original author Bohdan Vlasyuk <bohdan@vstu.edu.ua>
// Website:      https://github.com/vim/colorschemes
// License:      Same as Vim
// Last Change:  2025 Jan 07

// Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'darkblue'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#8b0000', '#90f020', '#ffa500', '#00008b', '#8b008b', '#008b8b', '#c0c0c0', '#808080', '#ffa0a0', '#90f020', '#ffff60', '#0030ff', '#ff00ff', '#90fff0', '#ffffff']
endif
hi! link Terminal Normal
hi! link PopupSelected PmenuSel
hi! link CursorColumn CursorLine
hi! link CursorIM Cursor
hi! link EndOfBuffer NonText
hi! link ErrorMsg Error
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link CursorLineFold CursorLine
hi! link CursorLineSign CursorLine
hi! link TabLineFill TabLine
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link Debug Special
hi! link Added String
hi! link Removed WarningMsg
hi! link diffOnly WarningMsg
hi! link diffNoEOL WarningMsg
hi! link diffIsA WarningMsg
hi! link diffIdentical WarningMsg
hi! link diffDiffer WarningMsg
hi! link diffCommon WarningMsg
hi! link diffBDiffer WarningMsg
hi! link lCursor Cursor
hi! link CurSearch Search
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
hi Normal fg=#c0c0c0 bg=#000040 deco=NONE cterm=NONE
hi Conceal fg=#008b8b bg=NONE deco=NONE cterm=NONE
hi ColorColumn fg=#c0c0c0 bg=#8b0000 deco=NONE cterm=NONE
hi Cursor fg=#000000 bg=#ffff60 deco=NONE cterm=NONE
hi QuickFixLine fg=#000000 bg=#ff80ff deco=NONE cterm=NONE
hi Error fg=#ffa0a0 bg=NONE deco=reverse cterm=reverse
hi FoldColumn fg=#808080 bg=NONE deco=bold cterm=NONE
hi Folded fg=#808080 bg=NONE deco=bold cterm=NONE
hi IncSearch fg=#ffffff bg=#0030ff deco=reverse cterm=reverse
hi LineNr fg=#90f020 bg=NONE deco=NONE cterm=NONE
hi MatchParen fg=NONE bg=NONE deco=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
hi ModeMsg fg=#90fff0 bg=NONE deco=NONE cterm=NONE
hi MoreMsg fg=#006400 bg=NONE deco=NONE cterm=NONE
hi NonText fg=#0030ff bg=NONE deco=NONE cterm=NONE
hi Pmenu fg=#ffffff bg=#0030ff deco=NONE cterm=NONE
hi PmenuSbar fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PmenuSel fg=#0030ff bg=#ffffff deco=NONE cterm=NONE
hi PmenuThumb fg=NONE bg=#ffffff deco=NONE cterm=NONE
hi PmenuMatch fg=#ff80ff bg=#0030ff deco=NONE cterm=NONE
hi PmenuMatchSel fg=#ff00ff bg=#ffffff deco=NONE cterm=NONE
hi Question fg=#90f020 bg=NONE deco=NONE cterm=NONE
hi SignColumn fg=#808080 bg=NONE deco=NONE cterm=NONE
hi SpecialKey fg=#008b8b bg=NONE deco=NONE cterm=NONE
hi SpellBad fg=#ff0000 bg=NONE guisp=#ff0000 deco=undercurl cterm=underline
hi SpellCap fg=#90f020 bg=NONE guisp=#90f020 deco=undercurl cterm=underline
hi SpellLocal fg=#90fff0 bg=NONE guisp=#90fff0 deco=undercurl cterm=underline
hi SpellRare fg=#ff00ff bg=NONE guisp=#ff00ff deco=undercurl cterm=underline
hi StatusLine fg=#000040 bg=#c0c0c0 deco=NONE cterm=NONE
hi StatusLineNC fg=#000000 bg=#808080 deco=NONE cterm=NONE
hi TabLine fg=#000000 bg=#808080 deco=NONE cterm=NONE
hi ToolbarButton fg=#ffffff bg=#0030ff deco=NONE cterm=NONE
hi ToolbarLine fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi VertSplit fg=#000000 bg=#808080 deco=NONE cterm=NONE
hi Visual fg=#8080ff bg=#ffffff deco=reverse cterm=reverse
hi VisualNOS fg=#8080ff bg=#c0c0c0 deco=reverse,underline cterm=reverse,underline
hi WarningMsg fg=#ff0000 bg=NONE deco=NONE cterm=NONE
hi WildMenu fg=#ffff60 bg=#000000 deco=NONE cterm=NONE
hi debugBreakpoint fg=#90f020 bg=#00008b deco=reverse cterm=reverse
hi debugPC fg=#90fff0 bg=#00008b deco=reverse cterm=reverse
hi Directory fg=#008b8b bg=NONE deco=NONE cterm=NONE
hi Title fg=#ff00ff bg=NONE deco=NONE cterm=NONE
hi Comment fg=#80a0ff bg=NONE deco=NONE cterm=NONE
hi Constant fg=#ffa0a0 bg=NONE deco=NONE cterm=NONE
hi Identifier fg=#90fff0 bg=NONE deco=NONE cterm=NONE
hi Ignore fg=#000040 bg=#c0c0c0 deco=NONE cterm=NONE
hi PreProc fg=#ff80ff bg=NONE deco=NONE cterm=NONE
hi Special fg=#ffa500 bg=NONE deco=NONE cterm=NONE
hi Statement fg=#ffff60 bg=NONE deco=NONE cterm=NONE
hi Todo fg=NONE bg=NONE deco=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
hi Type fg=#90f020 bg=NONE deco=NONE cterm=NONE
hi Underlined fg=#80a0ff bg=NONE deco=underline cterm=underline
hi TabLineSel fg=#000040 bg=#c0c0c0 deco=NONE cterm=NONE
hi CursorLine fg=NONE bg=#666666 deco=NONE cterm=NONE
hi CursorLineNr fg=#ffff60 bg=#666666 deco=NONE cterm=NONE
hi Search fg=#90fff0 bg=#0030ff deco=NONE cterm=NONE
hi DiffAdd fg=#ffffff bg=#5f875f deco=NONE cterm=NONE
hi DiffChange fg=#ffffff bg=#5f87af deco=NONE cterm=NONE
hi DiffText fg=#000000 bg=#c6c6c6 deco=NONE cterm=NONE
hi DiffDelete fg=#ffffff bg=#af5faf deco=NONE cterm=NONE

// Background: dark
// Color: white         #FFFFFF           231               white
// Color: black         #000000           16                black
// Color: diffc         #0087af           31                darkcyan
// Color: difft         #005f87           24                cyan
// Color: cursorl       #666666           59                darkgrey
// Color: ogDeepBlue    #000040           17                black
// Color: ogDarkBlue    #00008b           18                darkblue
// Color: ogBlue        #0030ff           27                blue
// Color: ogLightBlue   #287eff           33                blue
// Color: ogDarkGrey    #a9a9a9           248               grey
// Color: ogGrey        #808080           102               darkgrey
// Color: ogLightGrey   #c0c0c0           252               grey
// Color: ogDarkViolet  #404080           61                darkblue
// Color: ogViolet      #8080ff           105               blue
// Color: ogLightViolet #80a0ff           111               blue
// Color: ogDarkGreen   #006400           22                darkgreen
// Color: ogGreen       #90f020           118               green
// Color: ogDarkCyan    #008b8b           30                darkcyan
// Color: ogCyan        #90fff0           123               cyan
// Color: ogLightCyan   #b0ffff           159               cyan
// Color: ogDarkerRed   #8b0000           88                darkred
// Color: ogDarkRed     #d14a14           166               darkred
// Color: ogRed         #ff0000           196               red
// Color: ogLightRed    #ffa0a0           217               red
// Color: ogDarkMag     #8b008b           90                darkmagenta
// Color: ogMagenta     #ff00ff           201               darkmagenta
// Color: ogLightMag    #ff80ff           213               magenta
// Color: ogOrange      #ffa500           214               darkyellow
// Color: ogYellow      #ffff60           227               yellow
// Term colors: black  ogDarkerRed ogGreen ogOrange ogDarkBlue ogDarkMag ogDarkCyan ogLightGrey
// Term colors: ogGrey ogLightRed  ogGreen ogYellow ogBlue     ogMagenta    ogCyan     white
// Color: bgDiffA     #5F875F        65             darkgreen
// Color: bgDiffC     #5F87AF        67             blue
// Color: bgDiffD     #AF5FAF        133            magenta
// Color: bgDiffT     #C6C6C6        251            grey
// Color: fgDiffW     #FFFFFF        231            white
// Color: fgDiffB     #000000        16             black
// Color: bgDiffC8    #5F87AF        67             darkblue
// Color: bgDiffD8    #AF5FAF        133            darkmagenta
// vim: et ts=8 sw=2 sts=2
