" Name:         koehler
" Author:       original author Ron Aaron <ron@ronware.org>
" Maintainer:   original maintainer Ron Aaron <ron@ronware.org>
" Website:      https://www.github.com/vim/colorschemes
" License:      Same as Vim
" Last Change:  2024 Aug 15

" Generated by Colortemplate v2.2.3

set background=dark

hi clear
let g:colors_name = 'koehler'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)

hi! link Terminal Normal
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Number
hi! link Function Identifier
hi! link Include PreProc
hi! link IncSearch Visual
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor
hi! link CurSearch Search
hi! link CursorLineFold CursorLine
hi! link CursorLineSign CursorLine
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#cd0000', '#00cd00', '#cdcd00', '#0000ee', '#cd00cd', '#00cdcd', '#e5e5e5', '#7f7f7f', '#ff0000', '#00ff00', '#ffff00', '#5c5cff', '#ff00ff', '#00ffff', '#ffffff']
endif
hi Normal fg=#ffffff bg=#000000 deco=NONE cterm=NONE
hi ColorColumn fg=NONE bg=#8b0000 deco=NONE cterm=NONE
hi CursorColumn fg=NONE bg=#555555 deco=NONE cterm=NONE
hi CursorLine fg=NONE bg=#555555 deco=NONE cterm=NONE
hi CursorLineNr fg=#ffff00 bg=NONE deco=bold cterm=bold
hi Folded fg=#00cdcd bg=#666666 deco=NONE cterm=NONE
hi QuickFixLine fg=#000000 bg=#ffff00 deco=NONE cterm=NONE
hi Conceal fg=#666666 bg=NONE deco=NONE cterm=NONE
hi Cursor fg=#000000 bg=#00ff00 deco=NONE cterm=NONE
hi Directory fg=#cc8000 bg=NONE deco=NONE cterm=NONE
hi EndOfBuffer fg=#cd0000 bg=NONE deco=bold cterm=bold
hi ErrorMsg fg=#cd0000 bg=#ffffff deco=reverse cterm=reverse
hi FoldColumn fg=#00cdcd bg=NONE deco=NONE cterm=NONE
hi LineNr fg=#ffff00 bg=NONE deco=NONE cterm=NONE
hi MatchParen fg=NONE bg=#0000ff deco=NONE cterm=NONE
hi ModeMsg fg=#ffffff bg=#0000ff deco=bold cterm=bold
hi MoreMsg fg=#2e8b57 bg=NONE deco=bold cterm=bold
hi NonText fg=#cd0000 bg=NONE deco=bold cterm=bold
hi Pmenu fg=#ffffff bg=#444444 deco=NONE cterm=NONE
hi PmenuSbar fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi PmenuSel fg=#000000 bg=#00cdcd deco=NONE cterm=NONE
hi PmenuThumb fg=NONE bg=#ffffff deco=NONE cterm=NONE
hi PmenuMatch fg=#ff00ff bg=#444444 deco=NONE cterm=NONE
hi PmenuMatchSel fg=#ff0000 bg=#00cdcd deco=NONE cterm=NONE
hi Question fg=#5c5cff bg=NONE deco=bold cterm=bold
hi Search fg=#ffffff bg=#ff0000 deco=NONE cterm=NONE
hi SignColumn fg=#00ffff bg=NONE deco=NONE cterm=NONE
hi SpecialKey fg=#cd0000 bg=NONE deco=NONE cterm=NONE
hi SpellBad fg=#ff0000 bg=NONE guisp=#ff0000 deco=undercurl cterm=underline
hi SpellCap fg=#60ff60 bg=NONE guisp=#60ff60 deco=undercurl cterm=underline
hi SpellLocal fg=#00ffff bg=NONE guisp=#00ffff deco=undercurl cterm=underline
hi SpellRare fg=#ff00ff bg=NONE guisp=#ff00ff deco=undercurl cterm=underline
hi StatusLine fg=#0000ff bg=#ffffff deco=bold cterm=bold
hi StatusLineNC fg=#0000ff bg=#e5e5e5 deco=NONE cterm=NONE
hi TabLine fg=#0000ff bg=#ffffff deco=bold cterm=bold
hi TabLineFill fg=#0000ff bg=#ffffff deco=bold cterm=bold
hi TabLineSel fg=#ffffff bg=#0000ff deco=bold cterm=bold
hi Title fg=#ff00ff bg=NONE deco=bold cterm=bold
hi VertSplit fg=#0000ff bg=#e5e5e5 deco=NONE cterm=NONE
hi Visual fg=NONE bg=#666666 deco=reverse cterm=reverse
hi VisualNOS fg=NONE bg=#000000 deco=bold,underline cterm=underline
hi WarningMsg fg=#ff0000 bg=NONE deco=NONE cterm=NONE
hi WildMenu fg=#000000 bg=#ffff00 deco=NONE cterm=NONE
hi Comment fg=#80a0ff bg=NONE deco=NONE cterm=NONE
hi Constant fg=#ffa0a0 bg=NONE deco=NONE cterm=NONE
hi Error fg=#cd0000 bg=#ffffff deco=reverse cterm=reverse
hi Identifier fg=#40ffff bg=NONE deco=NONE cterm=NONE
hi Ignore fg=#000000 bg=#000000 deco=NONE cterm=NONE
hi PreProc fg=#ff80ff bg=NONE deco=NONE cterm=NONE
hi Special fg=#ffa500 bg=NONE deco=NONE cterm=NONE
hi Statement fg=#ffff60 bg=NONE deco=bold cterm=bold
hi Todo fg=#0000ff bg=#ffff00 deco=NONE cterm=NONE
hi Type fg=#60ff60 bg=NONE deco=bold cterm=bold
hi Underlined fg=#add8e6 bg=NONE deco=bold,underline cterm=underline
hi CursorIM fg=NONE bg=fg deco=NONE cterm=NONE
hi ToolbarLine fg=NONE bg=NONE deco=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi ToolbarButton fg=#000000 bg=#e5e5e5 deco=bold cterm=bold
hi DiffAdd fg=#ffffff bg=#5f875f deco=NONE cterm=NONE
hi DiffChange fg=#ffffff bg=#5f87af deco=NONE cterm=NONE
hi DiffText fg=#000000 bg=#c6c6c6 deco=NONE cterm=NONE
hi DiffDelete fg=#ffffff bg=#af5faf deco=NONE cterm=NONE

if s:t_Co >= 256
  hi Normal ctermfg=231 ctermbg=16 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=88 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=240 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=240 cterm=NONE
  hi CursorLineNr ctermfg=226 ctermbg=NONE cterm=bold
  hi Folded ctermfg=44 ctermbg=59 cterm=NONE
  hi QuickFixLine ctermfg=16 ctermbg=226 cterm=NONE
  hi Conceal ctermfg=59 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=16 ctermbg=46 cterm=NONE
  hi Directory ctermfg=172 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=160 ctermbg=NONE cterm=bold
  hi ErrorMsg ctermfg=160 ctermbg=231 cterm=reverse
  hi FoldColumn ctermfg=44 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=226 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=21 cterm=NONE
  hi ModeMsg ctermfg=231 ctermbg=21 cterm=bold
  hi MoreMsg ctermfg=29 ctermbg=NONE cterm=bold
  hi NonText ctermfg=160 ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=231 ctermbg=238 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=16 ctermbg=44 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=231 cterm=NONE
  hi PmenuMatch ctermfg=201 ctermbg=238 cterm=NONE
  hi PmenuMatchSel ctermfg=196 ctermbg=44 cterm=NONE
  hi Question ctermfg=63 ctermbg=NONE cterm=bold
  hi Search ctermfg=231 ctermbg=196 cterm=NONE
  hi SignColumn ctermfg=51 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=160 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=196 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=83 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=51 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=201 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=21 ctermbg=231 cterm=bold
  hi StatusLineNC ctermfg=21 ctermbg=254 cterm=NONE
  hi TabLine ctermfg=21 ctermbg=231 cterm=bold
  hi TabLineFill ctermfg=21 ctermbg=231 cterm=bold
  hi TabLineSel ctermfg=231 ctermbg=21 cterm=bold
  hi Title ctermfg=201 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=21 ctermbg=254 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=59 cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=16 cterm=underline
  hi WarningMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=16 ctermbg=226 cterm=NONE
  hi Comment ctermfg=111 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=217 ctermbg=NONE cterm=NONE
  hi Error ctermfg=160 ctermbg=231 cterm=reverse
  hi Identifier ctermfg=87 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=16 ctermbg=16 cterm=NONE
  hi PreProc ctermfg=213 ctermbg=NONE cterm=NONE
  hi Special ctermfg=214 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=227 ctermbg=NONE cterm=bold
  hi Todo ctermfg=21 ctermbg=226 cterm=NONE
  hi Type ctermfg=83 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=153 ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=16 ctermbg=254 cterm=bold
  hi DiffAdd ctermfg=231 ctermbg=65 cterm=NONE
  hi DiffChange ctermfg=231 ctermbg=67 cterm=NONE
  hi DiffText ctermfg=16 ctermbg=251 cterm=NONE
  hi DiffDelete ctermfg=231 ctermbg=133 cterm=NONE
  unlet s:t_Co
  finish
endif

if s:t_Co >= 16
  hi Normal ctermfg=white ctermbg=black cterm=NONE
  hi ColorColumn ctermfg=white ctermbg=darkred cterm=NONE
  hi CursorLineNr ctermfg=yellow ctermbg=NONE cterm=underline
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi Folded ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi QuickFixLine ctermfg=black ctermbg=yellow cterm=NONE
  hi Conceal ctermfg=darkgrey ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=black ctermbg=green cterm=NONE
  hi Directory ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=darkred ctermbg=NONE cterm=bold
  hi ErrorMsg ctermfg=darkred ctermbg=white cterm=reverse
  hi FoldColumn ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=yellow ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=darkblue cterm=NONE
  hi ModeMsg ctermfg=white ctermbg=darkblue cterm=bold
  hi MoreMsg ctermfg=darkgreen ctermbg=NONE cterm=bold
  hi NonText ctermfg=darkred ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=white ctermbg=darkgrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
  hi PmenuSel ctermfg=black ctermbg=darkcyan cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=white cterm=NONE
  hi PmenuMatch ctermfg=white ctermbg=darkgrey cterm=bold
  hi PmenuMatchSel ctermfg=black ctermbg=darkcyan cterm=bold
  hi Question ctermfg=blue ctermbg=NONE cterm=bold
  hi Search ctermfg=white ctermbg=red cterm=NONE
  hi SignColumn ctermfg=cyan ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=darkred ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=red ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=green ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=cyan ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=magenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=darkblue ctermbg=white cterm=bold
  hi StatusLineNC ctermfg=darkblue ctermbg=grey cterm=NONE
  hi TabLine ctermfg=darkblue ctermbg=white cterm=bold
  hi TabLineFill ctermfg=darkblue ctermbg=white cterm=bold
  hi TabLineSel ctermfg=white ctermbg=darkblue cterm=bold
  hi Title ctermfg=magenta ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=darkblue ctermbg=grey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=darkgrey cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=black cterm=underline
  hi WarningMsg ctermfg=red ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=black ctermbg=yellow cterm=NONE
  hi Comment ctermfg=blue ctermbg=NONE cterm=NONE
  hi Constant ctermfg=darkred ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=white cterm=reverse
  hi Identifier ctermfg=cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=black ctermbg=black cterm=NONE
  hi PreProc ctermfg=magenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=yellow ctermbg=NONE cterm=bold
  hi Todo ctermfg=darkblue ctermbg=yellow cterm=NONE
  hi Type ctermfg=green ctermbg=NONE cterm=bold
  hi Underlined ctermfg=blue ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=black ctermbg=grey cterm=bold
  hi DiffAdd ctermfg=white ctermbg=darkgreen cterm=NONE
  hi DiffChange ctermfg=white ctermbg=blue cterm=NONE
  hi DiffText ctermfg=black ctermbg=grey cterm=NONE
  hi DiffDelete ctermfg=white ctermbg=magenta cterm=NONE
  unlet s:t_Co
  finish
endif

if s:t_Co >= 8
  hi Normal ctermfg=grey ctermbg=black cterm=NONE
  hi ColorColumn ctermfg=grey ctermbg=darkred cterm=NONE
  hi CursorLineNr ctermfg=darkyellow ctermbg=NONE cterm=underline
  hi CursorColumn ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
  hi Folded ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi QuickFixLine ctermfg=black ctermbg=darkyellow cterm=NONE
  hi Conceal ctermfg=grey ctermbg=NONE cterm=NONE
  hi Directory ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=darkred ctermbg=NONE cterm=bold
  hi ErrorMsg ctermfg=darkred ctermbg=grey cterm=bold,reverse
  hi FoldColumn ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=darkblue cterm=NONE
  hi ModeMsg ctermfg=white ctermbg=darkblue cterm=bold
  hi MoreMsg ctermfg=darkgreen ctermbg=NONE cterm=bold
  hi NonText ctermfg=darkred ctermbg=NONE cterm=bold
  hi Pmenu ctermfg=grey ctermbg=darkgrey cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=grey cterm=NONE
  hi PmenuSel ctermfg=black ctermbg=darkcyan cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=darkcyan cterm=NONE
  hi PmenuMatch ctermfg=grey ctermbg=darkgrey cterm=bold
  hi PmenuMatchSel ctermfg=black ctermbg=darkcyan cterm=bold
  hi Question ctermfg=darkblue ctermbg=NONE cterm=bold
  hi Search ctermfg=grey ctermbg=darkred cterm=NONE
  hi SignColumn ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=darkred ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=darkred ctermbg=darkyellow cterm=reverse
  hi SpellCap ctermfg=darkgreen ctermbg=NONE cterm=reverse
  hi SpellLocal ctermfg=darkcyan ctermbg=NONE cterm=reverse
  hi SpellRare ctermfg=darkmagenta ctermbg=darkyellow cterm=reverse
  hi StatusLine ctermfg=grey ctermbg=darkblue cterm=bold,reverse
  hi StatusLineNC ctermfg=grey ctermbg=darkblue cterm=reverse
  hi TabLine ctermfg=grey ctermbg=darkblue cterm=bold,reverse
  hi TabLineFill ctermfg=darkblue ctermbg=grey cterm=bold
  hi TabLineSel ctermfg=grey ctermbg=darkblue cterm=bold
  hi Title ctermfg=darkmagenta ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=darkblue ctermbg=grey cterm=NONE
  hi Visual ctermfg=NONE ctermbg=NONE cterm=reverse
  hi VisualNOS ctermfg=NONE ctermbg=black cterm=underline
  hi WarningMsg ctermfg=darkred ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=black ctermbg=darkyellow cterm=NONE
  hi Comment ctermfg=darkblue ctermbg=NONE cterm=NONE
  hi Constant ctermfg=darkred ctermbg=NONE cterm=NONE
  hi Error ctermfg=darkred ctermbg=grey cterm=reverse
  hi Identifier ctermfg=darkcyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=black ctermbg=black cterm=NONE
  hi PreProc ctermfg=darkmagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=darkyellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=darkyellow ctermbg=NONE cterm=bold
  hi Todo ctermfg=darkblue ctermbg=darkyellow cterm=NONE
  hi Type ctermfg=darkgreen ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=grey ctermbg=black cterm=bold,reverse
  hi DiffAdd ctermfg=white ctermbg=darkgreen cterm=NONE
  hi DiffChange ctermfg=white ctermbg=darkblue cterm=NONE
  hi DiffText ctermfg=black ctermbg=grey cterm=NONE
  hi DiffDelete ctermfg=white ctermbg=darkmagenta cterm=NONE
  unlet s:t_Co
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  hi CurSearch term=reverse
  hi CursorLineFold term=underline
  hi CursorLineSign term=underline
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co
  finish
endif

" Background: dark
" Color: xterm0         #000000          16                black
" Color: xterm1         #cd0000          160               darkred
" Color: xterm2         #00cd00          40                darkgreen
" Color: xterm3         #cdcd00          184               darkyellow
" Color: xterm4         #0000ee          20                darkblue
" Color: xterm5         #cd00cd          164               darkmagenta
" Color: xterm6         #00cdcd          44                darkcyan
" Color: xterm7         #e5e5e5          254               grey
" Color: xterm8         #7f7f7f          102               darkgrey
" Color: xterm9         #ff0000          196               red
" Color: xterm10        #00ff00          46                green
" Color: xterm11        #ffff00          226               yellow
" Color: xterm12        #5c5cff          63                blue
" Color: xterm13        #ff00ff          201               magenta
" Color: xterm14        #00ffff          51                cyan
" Color: xterm15        #ffffff          231               white
" Color: Pmenu          #444444          238               darkgrey
" Color: rgbGrey40      #666666          59                darkgrey
" Color: rgbDarkGrey    #a9a9a9          145               grey
" Color: rgbDarkBlue    #00008b          20                darkblue
" Color: rgbDarkMagenta #8b008b          90                darkmagenta
" Color: rgbBlue        #0000ff          21                darkblue
" Color: rgbDarkCyan    #008b8b          44                darkcyan
" Color: rgbSeaGreen    #2e8b57          29                darkgreen
" Color: rgbGrey        #bebebe          250               grey
" Color: StatusLineTerm #90ee90          120               darkgreen
" Color: ToolbarLine    #7f7f7f          244               darkgrey
" Color: Comment        #80a0ff          111               blue
" Color: Constant       #ffa0a0          217               darkred
" Color: Special        #ffa500          214               darkyellow
" Color: Identifier     #40ffff          87                cyan
" Color: Statement      #ffff60          227               yellow
" Color: PreProc        #ff80ff          213               magenta
" Color: Type           #60ff60          83                green
" Color: koeDirectory   #cc8000          172               darkyellow
" Color: koeCursorLine  #555555          240               black
" Color: koeLightBlue   #ADD8E6          153               blue
" Color: koeDarkRed     #8b0000          88                darkred
" Term colors: xterm0 xterm1 xterm2 xterm3 xterm4 xterm5 xterm6 xterm7
" Term colors: xterm8 xterm9 xterm10 xterm11 xterm12 xterm13
" Term colors: xterm14 xterm15
" Color: bgDiffA     #5F875F        65             darkgreen
" Color: bgDiffC     #5F87AF        67             blue
" Color: bgDiffD     #AF5FAF        133            magenta
" Color: bgDiffT     #C6C6C6        251            grey
" Color: fgDiffW     #FFFFFF        231            white
" Color: fgDiffB     #000000        16             black
" Color: bgDiffC8    #5F87AF        67             darkblue
" Color: bgDiffD8    #AF5FAF        133            darkmagenta
" vim: et ts=8 sw=2 sts=2
